# **Análise exploratória de dados** {#analise-exploratoria}

<br>

## Análise exploratória de dados

<br>

### O que é análise exploratória de dados?

-   Análise exploratória de dados consiste em um processo iterativo de elaboração e interpretação da síntese de dados, tabelas e gráficos, considerando os aspectos teóricos do estudo.[@Ferketich1986]

-   Análise exploratória deve ser separada da análise inferencial de testes de hipóteses; a decisão sobre os modelos a testar deve ser feita *a priori*.[@zuur2009]

<br>

### Por que conduzir a análise exploratória de dados?

-   A condução de análise exploratória de dados pode ajudar a identificar padrões e pode orientar trabalhos futuros, mas os resultados não devem ser interpretados como inferências sobre uma população.[@zuur2009]

-   A análise exploratória não deve ser usada para definir as questões e hipóteses científicas do estudo.[@zuur2009]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *explore*[@explore] fornece a função [*explore*](https://www.rdocumentation.org/packages/explore/versions/1.0.2/topics/explore) para análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *dataMaid*[@dataMaid] fornece a função [*makeDataReport*](https://www.rdocumentation.org/packages/dataMaid/versions/1.4.1/topics/makeDataReport) para criar um relatório de análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *DataExplorer*[@DataExplorer] fornece a função [*create_report*](https://www.rdocumentation.org/packages/DataExplorer/versions/0.8.2/topics/create_report) para criar um relatório de análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *SmartEDA*[@SmartEDA] fornece a função [*ExpReport*](https://www.rdocumentation.org/packages/SmartEDA/versions/0.3.9/topics/ExpReport) para criar um relatório de análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *gtExtras*[@gtExtras] fornece a função [*gt_plt_summary*](https://www.rdocumentation.org/packages/gtExtras/versions/0.5.0/topics/gt_plt_summary) para criar uma tabela descritiva síntese com histogramas ou gráficos de barra a partir de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *radiant*[@radiant] fornece a função [*radiant*](https://www.rdocumentation.org/packages/radiant/versions/1.5.0/topics/radiant) para executar uma interface interativa para análise exploratória de dados.
:::

<br>

### Quais etapas constituem a análise exploratória de dados?

-   Cada combinação de problema de pesquisa e delineamento de estudo pode demandar um plano de análise exploratório distinto.[@zuur2009]

-   Verifique a existência e/ou influência de valores discrepantes ("fora da curva" ou *outliers*):[@chatfield1986; @Ferketich1986; @zuur2009]

    -   Boxplots

    -   Gráficos quantil-quantil (Q-Q)

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *graphics*[@graphics] fornece a função [*boxplot*](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/boxplot) para construção de gráficos *boxplot*.
:::

<br>

-   Verifique a homocedasticidade (homogeneidade da variância):[@zuur2009]

    -   Boxplots condicionais (por fator de análise)

    -   Análise dos resíduos do modelo de regressão

    -   Gráfico resíduos vs. valores ajustados

<br>

-   Verifique a normalidade da distribuição dos dados:[@chatfield1986; @zuur2009]

    -   Histograma das variáveis (por fator de análise)

    -   Histograma dos resíduos da regressão

<br>

-   Verifique a existência de grande quantidade de valores nulos (=0):[@zuur2009]

    -   Histograma das variáveis (por fator de análise)

<br>

-   Verifique a existência de colinearidade entre variáveis independentes de um modelo de regressão:[@zuur2009]

    -   Fator de inflação de variância (*variance inflation factor*, VIF)

    -   Coeficiente de correlação de Pearson ($r$)

    -   Gráfico de dispersão entre variáveis

<br>

-   Verifique possíveis relações entre as variáveis dependente(s) e independente(s) de um modelo de regressão:[@zuur2009]

    -   Gráfico de dispersão entre variáveis independente e dependente

<br>

-   Verifique possíveis interações entre as variáveis dependente(s) de um modelo de regressão:[@zuur2009]

    -   Gráfico *coplot* de dispersão entre variáveis dependentes

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *graphics*[@graphics] fornece a função [*coplot*](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/coplot) para construção de gráficos *boxplot* condicionais.
:::

<br>

-   Verifique por dependência entre variáveis de um modelo de regressão:[@zuur2009]

    -   Gráfico de série temporal das variáveis

    -   Gráfico de autocorrelação entre as variáveis

<br>

```{r, echo=FALSE, warning=FALSE, results='asis'}
cat(readLines("citation.html"), sep = "\n")
```

<br>
