# **Análise inicial de dados** {#analise-inicial-dados-cap}

<br>

## Análise inicial de dados {#analise-inicial}

<br>

### O que é análise inicial de dados?

-   Análise inicial de dados[@chatfield1986] é uma sequência de procedimentos que visam principalmente a transparência e integridade das pré-condições do estudo para conduzir a análise estatística apropriada de modo responsável para responder aos problemas da pesquisa.[@Baillie2022]

-   O objetivo da análise inicial de dados é propiciar dados prontos para análise estatística, incluindo informações confiáveis sobre as propriedades dos dados.[@Baillie2022]

-   A análise inicial de dados pode ser dividida nas seguintes etapas:[@Baillie2022]

    -   Configuração dos metadados

    -   Limpeza dos dados

    -   Verificação dos dados

    -   Relatório inicial dos dados

    -   Refinamento e atualização do plano de análise estatística

    -   Documentação e relatório da análise inicial de dados

-   A análise inicial de dados não deve ser confundida com análise exploratória[@Ferketich1986], nem deve ser utilizada para hipotetizar após os dados serem coletados (conhecido como *Hypothesizing After Results are Known*, HARKing)[@Kerr1998].

<br>

### Como conduzir uma análise inicial de dados?

-   Desenvolva um plano de análise inicial de dados consistente com os objetivos da pesquisa. Por exemplo, verifique a distribuição e escala das variáveis, procure por observações não-usuais ou improváveis, avalie possíveis padrões de dados perdidos.[@Baillie2022]

-   Não altere diretamente os dados de uma tabela obtida de uma fonte. Use scripts para implementar eventuais alterações, de modo a manter o registro de todas as modificações realizadas no banco de dados.[@Baillie2022]

-   Use os metadados do estudo para guiar a análise inicial dos dados e compartilhe com os dados para maior transparência e reprodutibilidade.[@Baillie2022]

-   Representação gráfica dos dados pode ajudar a identificar características e padrões no banco de dados, tais como suposições e tendências.[@Baillie2022]

-   Verifique a frequência e proporção de dados perdidos em cada variável, e depois examine por padrões de dados perdidos simultaneamente por duas ou mais variáveis.[@Baillie2022]

-   Verifique a frequência e proporção de dados perdidos em cada variável, e depois examine por padrões de dados perdidos simultaneamente por duas ou mais variáveis.[@Baillie2022]

-   Exclusão de dados *ad hoc* baseada no desfecho pode influenciar os resultados do estudo, portanto os critérios de exclusão de dados antes da análise estatística (descritiva e/ou inferencial) devem ser reportados.[@Landis2012]

<br>

### Quais problemas podem ser detectados na análise inicial de dados?

-   Registros duplicados, que devem ser excluídos para não inflar a amostra.[@huebner2016]

-   Codificação 0 ou 1 para variáveis dicotômicas para representar a direção esperada da associação entre elas.[@huebner2016]

-   Ordenação cronológica de variáveis com registros temporais (retrospectivos ou prospectivos).[@huebner2016]

-   A distribuição das variáveis para verificação das suposições das análises planejadas.[@huebner2016]

-   Ocorrência de efeitos teto e piso nas variáveis.[@huebner2016]

<br>
