# **Análise descritiva** {#analise-descritiva}

<br>

## Análise descritiva {#descritiva}

<br>

### O que é análise descritiva?

-   A análise descritiva utiliza métodos para calcular, descrever e resumir os dados coletados da(s) amostra(s) de modo que sejam interpretadas adequadamente.[@vetter2017]

-   As análises descritivas geralmente compreendem a apresentação quantitativa (numérica) em tabelas e/ou gráficos.[@vetter2017]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *explore*[@explore] fornece a função [*explore*](https://www.rdocumentation.org/packages/explore/versions/1.0.2/topics/explore) para análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *dataMaid*[@dataMaid] fornece a função [*makeDataReport*](https://www.rdocumentation.org/packages/dataMaid/versions/1.4.1/topics/makeDataReport) para criar um relatório de análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *DataExplorer*[@DataExplorer-2] fornece a função [*create_report*](https://www.rdocumentation.org/packages/DataExplorer/versions/0.8.2/topics/create_report) para criar um relatório de análise exploratória de um banco de dados.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *SmartEDA*[@SmartEDA] fornece a função [*ExpReport*](https://www.rdocumentation.org/packages/SmartEDA/versions/0.3.9/topics/ExpReport) para criar um relatório de análise exploratória de um banco de dados.
:::

<br>

### Como apresentar os resultados descritivos?

-   Variáveis categóricas: Reporte valores de frequência absoluta e relativa (n, %).[@Cummings2003]

-   Organização das tabelas: as variáveis são exibidas em linhas e os grupos são exibidos em colunas.[@Cummings2003]

-   Calcule percentagens para as colunas (isto é, entre grupos) e não entre linhas.[@Cummings2003]

-   Em caso de dados perdidos, não inclua uma linha com total de dados perdidos, pois distorce as proporções entre colunas e as análises de tabela de contingência. Neste caso, indique no texto ou em uma coluna separada o total de dados perdidos por variável.[@Cummings2003]

<br>

## Tabelas {#tabelas}

<br>

### Por que usar tabelas?

-   Tabelas complementam o texto (e vice-versa), e podem apresentar os dados de modo mais acessível e informativo.[@Inskip2017]

<br>

### Que informações incluir nas tabelas?

-   Título ou legenda, uma síntese descritiva (geralmente por meio de parâmetros descritivos), intervalos de confiança e/ou P-valores conforme necessário para adequada interpretação.[@Inskip2017; @Kwak2021]

<br>

### Quais são os erros mais comuns de preenchimento de tabelas?

-   Erros tipográficos.[@barnett2023]

-   Ausência de rótulos ou unidades nas variáveis.[@barnett2023]

-   Relatar estatísticas incorretamente, tais como rotular variáveis contínuas como porcentagens.[@barnett2023]

-   Estatísticas descritivas de tendência central (ex.: médias) relatadas sem a estatística de dispersão correspondente (ex.: desvio-padrão).[@barnett2023]

-   Desvio-padrão nulo ($\sigma=0$).[@barnett2023]

-   Valores porcentuais que não correspondem ao numerador dividido pelo denominador.[@barnett2023]

<br>

### Como exportar tabelas em formato DOCX?

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *table1*[@flextable] fornece as funções [*as_flextable*](https://www.rdocumentation.org/packages/flextable/versions/0.9.2/topics/as_flextable) e [*save_as_docx*](https://www.rdocumentation.org/packages/flextable/versions/0.9.2/topics/save_as_docx) para salvar tabelas em formato DOCX.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *gtsummary*[@gtsummary-2] fornece a função [*tbl_summary*](https://www.rdocumentation.org/packages/gtsummary/versions/1.6.3/topics/tbl_summary) para construção de tagelas com dados descritivos.
:::

<br>

## Tabela 1 {#tabela-1}

<br>

### O que é a 'Tabela 1'?

-   A 'Tabela 1' descreve as características demográficas, sociais e clínicas da amostra, completa ou agrupada por algum fator, geralmente por meio de parâmetros de tendência central e dispersão.[@Westreich2013; @chen2020]

<br>

### Qual a utilidade da 'Tabela 1'?

-   Descrever (conhecer) as características da amostra e dos grupos sendo comparados, quando aplicável.[@chen2020]

-   Verificar aderência ao protocolo do estudo, incluindo critérios de inclusão/exclusão, tamanho da amostra e perdas amostrais.[@chen2020]

-   Permitir a replicação do estudo.[@chen2020]

-   Meta-analisar os dados junto a estudos similares.[@chen2020]

-   Avaliar a generalização (validade externa) das conclusões do estudo.[@chen2020]

<br>

### O que é a falácia da 'Tabela 1'?

-   Falácia da Tabela 1 ocorre pela interpretação errônea dos P-valores na comparação entre grupos, na linha de base, de um ensaio clínico aleatorizado.[@pijls2022]

<br>

### Como construir a 'Tabela 1'?

-   A Tabela 1 geralmente é utilizada para descrever as características da amostra estudada, possibilitando a análise de ameaças à validade interna e/ou externa ao estudo.[@greenhalgh1997; @Hayes-Larson2019]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *table1*[@table1] fornece a função [*table1*](https://www.rdocumentation.org/packages/table1/versions/1.4.3/topics/table1) para construção de tabelas.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *gtsummary*[@gtsummary-2] fornece a função [*tbl_summary*](https://www.rdocumentation.org/packages/gtsummary/versions/1.6.3/topics/tbl_summary) para construção da 'Tabela 1' com dados descritivos.
:::

<br>

## Tabela 2 {#tabela-2}

<br>

### O que é a 'Tabela 2'?

-   .[REF]

<br>

### Qual a utilidade da 'Tabela 2'?

-   A Tabela 2 mostra associações ajustadas multivariadas com o resultado para variáveis resumidas na Tabela 1.[@Westreich2013]

<br>

### O que é a falácia da 'Tabela 2'?

-   A Tabela 2 pode induzir ao erro de interpretação pelas estimativas de efeitos para covariáveis do modelo também serem utilizados para controlar a confusão da exposição.[@Westreich2013; @bandoli2018]

-   Ao apresentar estimativas de efeito ajustadas para covariáveis juntamente com a estimativa de efeito ajustada para a exposição primária, a Tabela 2 sugere implicitamente que todas estas estimativas podem ser interpretadas de forma semelhante, se não de forma idêntica, como estimativa do efeito total.[@Westreich2013; @bandoli2018]

-   A falácia da Tabela 2 pode ser evitada limitando-se a tabela a estimativas das medidas primárias do efeito de exposição nos diferentes modelos, com as covariáveis secundárias de "ajuste" relatadas em uma nota de rodapé, juntamente com a forma como foram categorizadas ou modeladas.[@Westreich2013]

<br>

### Como construir a 'Tabela 2'?

-   A Tabela 2 pode ser utilizada para apresentar estimativas de múltiplos efeitos ajustados de um mesmo modelo estatístico.[@Westreich2013]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *table1*[@table1] fornece a função [*table1*](https://www.rdocumentation.org/packages/table1/versions/1.4.3/topics/table1) para construção de tabelas.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *gtsummary*[@gtsummary-2] fornece a função [*tbl_summary*](https://www.rdocumentation.org/packages/gtsummary/versions/1.6.3/topics/tbl_summary) para construção da 'Tabela 2' com análises inferenciais.
:::

<br>

## Gráficos {#graficos}

<br>

### O que são gráficos?

-   Gráficos são utilizados para apresentar dados (geralmente em grande quantidade) de modo mais intuitivo e fácil de compreender.[@Park2022]

<br>

### Qual a utilidade dos gráficos?

-   .[REF]

<br>

### Que elementos incluir em gráficos?

-   Título, eixos horizontal e vertical com respectivas unidades, escalas em intervalos representativos das variáveis, legenda com símbolos, síntese descritiva dos valores e respectiva margem de erro, conforme necessário para adequada interpretação.[@Park2022]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
Os pacotes *ggplot2*[@ggplot2], *plotly*[@plotly] e *corrplot*[@corrplot] fornecem diversas funções para construção de gráficos tais como [*ggplot*](https://www.rdocumentation.org/packages/ggplot2/versions/3.4.3/topics/ggplot), [*plot_ly*](https://www.rdocumentation.org/packages/plotly/versions/4.10.2/topics/plot_ly) e [*corrplot*](https://www.rdocumentation.org/packages/corrplot/versions/0.92/topics/corrplot) respectivamente.
:::

<br>

### Para que servem as barras de erro em gráficos?

-   Barras de erro ajudam ao autor a apresentar as informações que descrevem os dados (por exemplo, em uma análise descritiva) ou sobre as inferências ou conclusões tomadas a partir de dados.[@Cumming2007]

-   Barras de erro mais longas representam mais imprecisão (maiores erros), enquanto barras mais curtas representam mais precisão na estimativa.[@Cumming2007]

-   Barras de erro descritivas geralmente apresentam a amplitude (mínimo-máximo) ou desvio-padrão.[@Cumming2007]

-   Barras de erro inferenciais geralmente apresentam o erro-padrão ou intervalo de confiança (por exemplo, de 95%).[@Cumming2007]

-   O comprimento das barras de erro sugere graficamente a imprecisão dos dados do estudo, uma vez que o valor verdadeiro da população pode estar em qualquer nível do intervalo da barra.[@Cumming2007]

<br>

### Quais são as boas práticas na elaboração de gráficos?

-   O tamanho da amostra total e subgrupos, se houver, deve estar descrito na figura ou na sua legenda.[@Cumming2007]

-   Para análise inferencial de figuras, as barras de erro representadas por erro-padrão ou intervalo de confiança são preferíveis à amplitude ou desvio-padrão.[@Cumming2007]

-   Evite gráficos de barra e mostre a distribuição dos dados sempre que possível.[@Weissgerber2019]

-   Exiba os pontos de dados em boxplots.[@Weissgerber2019]

-   Use *jitter* simétrico em gráficos de pontos para permitir a visualização de todos os dados.[@Weissgerber2019]

-   Prefira palhetas de cor adaptadas para daltônicos.[@Weissgerber2019]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *ggsci*[@ggsci] fornece palhetas de cores tais como [*pal_lancet*](https://www.rdocumentation.org/packages/ggsci/versions/3.0.0/topics/pal_lancet), [*pal_nejm*](https://www.rdocumentation.org/packages/ggsci/versions/3.0.0/topics/pal_nejm) e [*pal_npg*](https://www.rdocumentation.org/packages/ggsci/versions/3.0.0/topics/pal_npg) inspiradas em publicações científicas para uso em gráficos.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *grDevices*[@grDevices] fornece a função [*dev.new*](https://www.rdocumentation.org/packages/grDevices/versions/3.6.2/topics/dev) para controlar diversos aspectos do gráfico, tais como tamanho e resolução.
:::

<br>

### Como exportar figuras em formato TIFF?

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *tiff*[@tiff] fornece a função [*writeTIFF*](https://www.rdocumentation.org/packages/tiff/versions/0.1-11/topics/writeTIFF) para exportar gráficos em formato TIFF.
:::

<br>
