# **Análise inferencial** {#analise-inferencial}

<br>

## Hipóteses científicas {#ideias-hipoteses}

<br>

### O que é hipótese científica?

-   Hipótese científica é uma ideia que pode ser testada.[@Curran-Everett2009]

<br>

### Quais são as principais fontes de ideias para gerar hipóteses científicas?

-   Revisão das práticas atuais.[@Vandenbroucke2018]

-   Desafio a ideias aceitas.[@Vandenbroucke2018]

-   Conflito entre ideias divergentes.[@Vandenbroucke2018]

-   Variações regionais, temporais e populacionais.[@Vandenbroucke2018]

-   Experiências dos próprios pesquisadores.[@Vandenbroucke2018]

-   Imaginação sem fronteiras ou limites convencionais.[@Vandenbroucke2018]

<br>

### Ausência de evidência ou evidência de ausência?

-   Em estudos (geralmente com amostras grandes), resultados estatisticamente significativos (com P-valores menores do limiar pré-estabelecido, $P<\alpha$) podem não ser clinicamente relevantes.[@altman1995]

-   Em estudos (geralmente com amostras pequenas), resultados estatisticamente não significativos (com P-valores iguais ou maiores do limiar pré-estabelecido, $P≥\alpha$) não devem ser interpretados como evidência de inexistência do efeito.[@altman1995]

-   Geralmente é razoável aceitar uma nova conclusão apenas quando há dados a seu favor ('resultados positivos'). Também é razoável questionar se apenas a ausência de dados a seu favor ('resultados negativos') justifica suficientemente a rejeição de tal conclusão.[@altman1995]

<br>

## Interpretação de análsie inferencial

<br>

### Como interpretar uma análise inferencial?

-   Testes de hipótese nula ($H_{0}$) vs. alternativa ($H_{1}$) a partir de um nível de significância ($\alpha$) pré-especificado.[@goodman2016]

-   P-valor como evidência estatística sobre ($H_{0}$).[@goodman2016]

-   Estimação de intervalos de confiança de um nível de significância ($\alpha$) pré-especificado ($IC_{\alpha}$).[@goodman2016]

- Análise Bayesiana.[@goodman2016]

<br>

### O que é significância estatística?

-   A expressão "significância estatística" sugere apenas que um experimento merece ser repetido, uma vez que um baixo P-valor (calculado a partir dos dados, modelos e demais suposições do estudo) sugere ser improvável que os dados coletados sejam coletados no contexto de que a hipótese nula $H_{0}$ assumida é verdadeira.[@aylmerfisher1926]

<br>

## Testes de hipóteses {#erros-inferencia}

<br>

### O que é hipótese nula?

-   A hipótese nula ($H_{0}$) é uma expressão que representa o estado atual do conhecimento (*status quo*), em geral a não existência de um determinado efeito.[@kanji2006]

<br>

### O que é hipótese alternativa?

-   A hipótese alternativa ($H_{1}$) é uma expressão que contém as situações que serão testadas, de modo que um resultado positivo indique alguma ação a ser conduzida.[@kanji2006]

<br>

### Qual hipótese está sendo testada?

-   A hipótese nula ($H_{0}$) é a hipótese sob teste em análises inferenciais.[@Ali2016]

-   Pode-se concluir sobre rejeitar ou não rejeitar a hipótese nula ($H_{0}$).[@Ali2016]

-   Não se conclui sobre a hipótese alternativa ($H_{1}$).[@kanji2006]

-   Para testar a hipótese nula, deve-se selecionar o nível de significância crítica (p-valor de corte); a probabilidade de rejeitarmos uma hipótese nula verdadeira ($\alpha$); e a probabilidade de não rejeitarmos uma hipótese nula falsa ($\beta$).[@Curran-Everett2009]

<br>

### Quais são os tipos de teste de hipóteses?

-   Teste (clássico) de significância da hipótese nula.[@lakens2018]

-   Teste de mínimos efeitos.[@lakens2018]

-   Teste de equivalência.[@lakens2018]

-   Teste de inferioridade.[@lakens2018]

-   Teste de não-inferioridade.[REF]

-   Teste de superioridade.[REF]

<br>

### O que são testes unicaudais e bicaudais?

-   .[REF]

<br>

### O que são resultados 'positivos' e 'negativos' em teste de hipótese?

-   .[REF]

<br>

### Qual a importância de resultados 'negativos'?

-   Conhecer resultados negativos contribui com uma visão mais ampla do campo de estudo junto aos resultados positivos.[@weintraub2016]

-   Resultados negativos permitem um melhor planejamento das pesquisas futuras e pode aumentar suas chances de sucesso.[@weintraub2016]

<br>

## Testes paramétrico e não paramétrico {#parametric-naoparametrico}

<br>

### O que é um teste paramétrico?

-   Testes paramétricos possuem suposições sobre as características e/ou parâmetros da distribuição dos dados na população.[@vetter2017]

-   Testes paramétricos assumem que: a variável é quantitativa numérica (contínua); os dados foram amostrados de uma população com distribuição normal; a variância da(S) amostra(s) é igual à da população; as amostras foram selecionadas de modo aleatório na população; os valores de cada amostra são independentes entre si.[@Ali2016; @vetter2017]

<br>

### O que é um teste não paramétrico?

-   Testes não-paramétricos fazem poucas suposições, ou menos rigorosas, sobre as características e/ou parâmetros da distribuição dos dados na população.[@Ali2016; @vetter2017]

-   Testes não-paramétricos são úteis quando as suposições de normalidade não podem ser sustentadas.[@Ali2016]

<br>

### Por que os testes paramétricos são preferidos?

-   Em geral, testes paramétricos são mais robustos (isto é, possuem menores erros tipo I e II) que seus testes não-paramétricos correspondentes.[@vetter2017]

-   Testes não-paramétricos apresentam menor poder estatístico (maior erro tipo II) comparados aos testes paramétricos correspondentes.[@Ali2016]

<br> \## Análise inferencial {#inferencial}

<br>

### O que é análise inferencial?

-   Na análise inferencial são utilizados dados da(s) amostra(s) para fazer uma inferência válida (isto é, estimativa) sobre os parâmetros populacionais desconhecidos.[@vetter2017]

-   No paradigma de Jerzy Neyman e Egon Pearson, um teste de hipótese científica envolve a tomada de decisão sobre hipóteses nulas ($H_{0}$) e alternativa ($H_{1}$) concorrentes e mutuamente exclusivas.[@Curran-Everett2009]

<br>

### O que é uma análise ad hoc?

-   .[REF]

<br>

### O que é uma análise post hoc?

-   .[REF]

<br>

### O que reportar após um teste de hipótese?

-   P-valores, como estimativa da significância estatística.[@Sullivan2012]

-   Tamanho do efeito, como estimativa de significância substantiva (clínica).[@Sullivan2012]

<br>

## P-valor {#p-valor}

<br>

### O que é o P-valor?

-   P-valor é a probabilidade, assumindo-se um dado modelo estatístico, de que um efeito calculado a partir dos dados seria igual ou mais extremo do que o seu valor observado.[@wasserstein2016]

### Como interpretar o P-valor?

-   P-valores podem indicar quantitativamente a incompatibilidade entre os dados obtidos e o modelo estatístico especificado a priori (geralmente constituído pela hipótese nula $H_{0}$).[@wasserstein2016]

-   P-valores menores/maiores do que o nível de significância estatístico pré-estabelecido não devem ser utilizados como única fonte de informação para tomada de decisão em ciência.[@wasserstein2016]

-   P-valor sozinho não provê informação suficiente sobre a evidência sobre um modelo teórico. A sua interpretação correta requer uma descrição ampla sobre o delineamento, métodos e análises estatísticas aplicados no estudo.[@wasserstein2016]

-   Evidência estatística de significância não provê informação sobre a magnitude do efeito observado e não necessariamente implica que o efeito é robusto.[@Landis2012]

<br>

### O que o P-valor não é?

-   P-valor não representa a probabilidade de que a hipótese nula $H_{0}$) seja verdadeira, nem a probabilidade de que os dados tenham sido produzidos pelo acaso.[@wasserstein2016]

-   P-valor não mede o tamanho do efeito ou a relevância da sua observação.[@wasserstein2016]

<br>

### Quais são os complementos ou alternativas ao P-valor?

-   Intervalos de confiança, credibilidade ou predição.[@wasserstein2016]

-   Razão de verossimilhança.[@wasserstein2016]

-   Métodos Bayesianos, fator Bayes.[@wasserstein2016]

<br>

## Tamanho do efeito {#tamanho-efeito}

<br>

### O que é o tamanho do efeito?

-   Tamanho do efeito quantifica a magnitude de um efeito real da análise, expressando uma importância descritiva dos resultados.[@Kim2015]

<br>

### Como interpretar um tamanho do efeito?

-   Tamanhos de efeito podem ser comparadores entre diferentes estudos.[@Sullivan2012]

<br>

### Quais são os tipos de tamanho do efeito?

-   Diferenças padronizadas entre grupos:[@Sullivan2012; @Kim2015]

    -   Cohen's d

    -   Glass's $\Delta$

    -   Razão de chances ($RC$ ou $OR$)

    -   Risco relativo ou razão de risco ($RR$)

-   Medidas de associação:[@Sullivan2012; @Kim2015]

    -   Coeficiente de correlação de Pearson ($r$)

    -   Coeficiente de determinação ($R^2$)

<br>

### Como converter um tamanho de efeito em outro?

-   .[@Kim2015]

<br>

## Poder do teste {#poder-teste}

<br>

### O que é poder do teste?

-   Poder do teste é a probabilidade de rejeitar corretamente a hipótese nula ($H_{0}$) quando esta é falsa.[@Curran-Everett2009]

-   Poder do teste pode ser calculado como ($1 - \beta$).[@Curran-Everett2009]

<br>

### O que é análise de poder do teste?

-   Poder é a probabilidade de que um dado tamanho de efeito será observado em um experimento futuro sob um conjunto de hipóteses - tamanho de efeito real e erro tipo I - para um dado tamanho de amostra.[@heckman2022]

-   O objetivo geral da análise de poder ao projetar um estudo é escolher um tamanho de amostra que controle os 2 tipos de erros de inferência estatística: tipo I ($\alpha$, resultado falso-positivo) e tipo II ($\beta$, resultado falso-negativo).[@heckman2022]

-   Numericamente, o poder de um estudo é calculado como $1-\beta$ e reportado em valor percentual.[@heckman2022]

<br>

### Quando realizar a análise de poder do teste?

-   Na fase de projeto de pesquisa: a análise de poder para determinar o tamanho da amostra objetiva que o tamanho da amostra permita uma probabilidade razoável de detectar um efeito significativo pré-especificado.[@heckman2022]

-   Após a coleta de dados: a análise de poder objetiva informar estudos futuros a respeito do tamanho da amostra necessário para a detectação de um efeito significativo pré-especificado.[@heckman2022]

<br>

### Porque a análise de poder do teste *post hoc* é inadequada?

-   A análise do poder é teoricamente incorreta, uma vez que a probabilidade calculada $1-\beta$ expressa a probabilidade de um evento futuro, o que não é mais relevante quando o evento de interesse já ocorreu.[@Cummings2003; @heckman2022]

<br>

### O que pode ser realizado ao invés da análise de poder?

-   Após a coleta e análise de dados, recomenda-se realizar a análise e interpretação dos resultados a partir do tamanho do efeito e do seu intervalo de confiança no nível de significância $\alpha$ pré-estabelecido.[@heckman2022]

<br>

## Erros de inferência

<br>

### O que são erros de inferência estatística?

-   Um erro de inferência é a tomada de decisão incorreta, seja a favor ou contra a hipótese nula.[@Curran-Everett2009]

<br>

### O que é erro amostral?

-   .[REF]

<br>

### O que é erro tipo I?

-   Erro tipo I significa a rejeição de uma hipótese nula ($H_{0}$) quando esta é verdadeira.[@Curran-Everett2009]

<br>

### O que é erro tipo II?

-   Erro tipo II significa a não rejeição de uma hipótese nula ($H_{0}$) quando esta é falsa.[@Curran-Everett2009]

<br>

### Qual a relação entre os erros tipo I e II?

-   .[REF]

<br>
