# **Análise robusta**

<br>

## Raciocínio inferencial robusto

<br>

### O que é análise robusta?

- Análise robusta é uma abordagem estatística que busca fornecer resultados confiáveis mesmo quando as suposições clássicas dos modelos estatísticos são violadas, como normalidade e homocedasticidade. Ela utiliza métodos que são menos sensíveis a outliers e outras irregularidades nos dados.[@WRS2]

<br>

### Por que usar análise robusta?

- Métodos clássicos como ANOVA e regressão por mínimos quadrados assumem normalidade e homocedasticidade — suposições frequentemente violadas na prática. Violações dessas suposições podem comprometer os resultados, reduzindo o poder estatístico, distorcendo os intervalos de confiança e obscurecendo as reais diferenças entre grupos.[@WRS2]

- Testar previamente as suposições não é suficiente: testes de homocedasticidade têm baixo poder e não garantem segurança analítica.[@WRS2]

- Métodos estatísticos robustos oferecem uma solução mais segura e eficaz, lidando melhor com dados não ideais.[@WRS2]

### Quando usar análise robusta?

<br>

- Em alguns casos, os métodos robustos confirmam os resultados clássicos; em outros, revelam interpretações completamente diferentes. A única forma de saber o impacto real dos métodos robustos é usá-los e comparar com os métodos tradicionais.[@WRS2]

<br>

### O que é Winsorização?

- Winsorização é uma técnica que substitui os valores extremos (outliers) por valores menos extremos, preservando a estrutura dos dados. Isso é feito definindo limites superior e inferior e substituindo os valores que ultrapassam esses limites pelos próprios limites.[@WRS2]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *WRS2*[@WRS2-2] fornece as funções [*winmean*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/trimse) e [*winvar*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/trimse) para calcular a média e variância Winsorizadas.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *WRS2*[@WRS2-2] fornece a função [*yuen*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/yuen) para realizar o teste de comparação de Yuen de médias Winsorizadas para amostras independentes ou dependentes.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *WRS2*[@WRS2-2] fornece a função [*wincor*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/pbcor) para calcular a correlação Winsorizada.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *WRS2*[@WRS2-2] fornece as funções [*t1way*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/t1way), [*t2way*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/t2way) e [*t3way*](https://www.rdocumentation.org/packages/WRS2/versions/1.1-6/topics/t3way) para realizar testes de comparação de médias Winsorizadas para análise de variância para 1, 2 ou 3 fatores, respectivamente.
:::

<br>
