# **Computação estatística** {#computacao-estatistica}

<br>

## Programa de computador {#inicio}

<br>

### O que é R?

-   R é um programa de computador com linguagem computacional direcionada para análise estatística.[@ihaka1996]

-   R está disponível em [Comprehensive R Archive Network (CRAN)]((https://cran.r-project.org)).

-   `r R.version$version.string`.

<br>

### O que é RStudio?

-   RStudio é um ambiente de desenvolvimento integrado (*integrated development environment*, IDE) desenvolvido visando a reprodutibilidade e a simplicidade para a criação e disseminação de conhecimento.[@racine2011]

-   As principais características do RStudio incluem um ambiente de edição com abas para acesso rápido a arquivos, comandos e resultados; histórico de comandos previamente utilizados; ferramentas para visualização de bancos de dados e elaboração de scripts e gráficos e tabelas.[@racine2011]

-   RStudio está disponível em [Posit](https://posit.co/download/rstudio-desktop/).

<br>

### Por que usar R?

-   R é o software de maior abrangência de métodos estatísticos, possui sintaxe que permite análises estatísticas reproduzíveis e está disponível gratuitamente no website CRAN (<http://cran.r-project.org/>).[@mair2016]

<br>

### Que programas de computador podem ser usados para análise estatística com R?

-   [JASP](https://jasp-stats.org).[@love2019]

-   [jamovi](https://www.jamovi.org).[@sahin2020]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
Os pacotes *jmv*[@jmv] e *jmvconnect*[@jmvconnect] fornecem funções para análise descritiva e inferencial com interface com jamovi.
:::

<br>

## Scripts computacionais

<br>

### O que são scripts?

-   "Scripts são dados".[@hinsen2011]

-   Scripts permitem ao usuário se concentrar nas tarefas mais importantes da computação e utilizar pacotes ou bibliotecas para executar as funções mais básicas com maior eficiência.[@hinsen2011]

-   Um script é um arquivo de texto contendo (quase) os mesmos comandos que você digitaria na linha de comando do R. (Quase) refere-se ao fato de que se você estiver usando *sink()* para enviar a saída para um arquivo, você terá que incluir alguns comandos em *print()* para obter a mesma saída da linha de comando ([CRAN](https://cran.r-project.org/doc/contrib/Lemon-kickstart/kr_scrpt.html)).

<br>

### Quais práticas são recomendadas na redação de scripts?

-   Use nomes consistentes para as variáveis.[@SchwabSimon2021]

-   Defina os tipos de variáveis adequadamente no banco de dados.[@SchwabSimon2021]

-   Defina constantes - isto é, variáveis de valor fixo - ao invés de digitar valores.[@SchwabSimon2021]

-   Use e cite os pacotes disponíveis para suas análises.[@SchwabSimon2021]

-   Controle as versões do script.[@Eglen2017; @SchwabSimon2021]

-   Teste o script antes de sua utilização.[@SchwabSimon2021]

-   Conduza revisão por pares do código durante a redação (digitação em dupla).[@SchwabSimon2021]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *formatR*[@formatR] fornece a função [*tidy_source*](https://www.rdocumentation.org/packages/formatR/versions/1.14/topics/tidy_source) para formatar um R script.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *styler*[@styler] fornece a função [*style_file*](https://www.rdocumentation.org/packages/styler/versions/1.10.1/topics/style_file) para formatar um R script.
:::

<br>

## Compartilhamento

<br>

### O que pode ser compartilhado?

-   Idealmente, todos os scripts, pacotes/bibliotecas e dados necessários para outros reproduzirem seus dados.[@Eglen2017]

-   Minimamente, partes importantes incluindo implementações de novos algoritmos e dados que permitam reproduzir um resultado importante.[@Eglen2017]

<br>

### Como preparar dados para compartilhamento?

-   .[REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *synthpop*[@synthpop] fornece a função [*syn*](https://www.rdocumentation.org/packages/synthpop/versions/1.8-0/topics/syn) para criar bancos de dados sintéticos a partir de um banco de dados real.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *grateful*[@grateful] fornece a função [*cite_packages*](https://www.rdocumentation.org/packages/grateful/versions/0.2.0/topics/cite_packages) para citar os pacotes utilizados em um projeto R.
:::

<br>

### Como preparar scripts para compartilhamento?

-   Documente em um arquivo README os arquivos disponíveis e os pré-requisitos necessários para executar o código (ex.: pacotes e respectivas versões). Uma lista de configurações (hardware e software) que foram usadas para rodar o código pode ajudar na reprodução dos resultados.[@hofner2015]

-   Crie links persistentes para versões do seu script.[@Eglen2017]

-   Defina uma semente para o gerador de números aleatórios em scripts com métodos computacionais que dependem da geração de números pseudoaleatórios.[@hofner2015]

-   Escolha uma licença apropriada para garantir como outros usarão seus scripts.[@Eglen2017]

-   Compartilhe todos os pacotes relacionados à sua análise.[@Zhao2023]

-   Providencie a documentação sobre seu script (ex.: arquivo README).[@Eglen2017]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base-5] fornece a função [*set.seed*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Random) para especificar uma semente para reprodutibilidade de computações que envolvem números aleatórios.
:::

<br>

### O que incluir no arquivo README?

-   Título do manuscrito.[@hofner2015]

-   Autores do manuscrito.[@hofner2015]

-   Principais responsáveis pela escrita do script e quaisquer outras pessoas que fizeram contribuições substanciais para o desenvolvimento do script.[@hofner2015]

-   Endereço de e-mail do autor ou contribuidor a quem devem ser direcionadas dúvidas, comentários, sugestões e bugs sobre o script.[@hofner2015]

-   Lista de configurações nas quais o script foi testado, tais com nome e versão do programa, pacotes e plataforma.[@hofner2015]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *utils*[@utils] fornece a função [*sessionInfo*](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/sessionInfo) para descrever as características do programa, pacotes e plataforma da sessão atual.
:::

<br>

## Manuscritos reprodutíveis {#relatórios-dinamicos}

<br>

### O que são manuscritos reprodutíveis?

-   Manuscritos reprodutíveis - manuscritos executáveis ou relatórios dinâmicos - permitem a produção de um manuscrito completo a partir da integração do banco de dados da(s) amostra(s), do(s) script(s) de análise estatística (incluindo comentários para sua interpretação), dos pacotes ou bibliotecas utilizados, das fontes e referências bibliográficas citadas, além dos demais elementos textuais (tabelas, gráficos) - todos gerados dinamicamente.[@hinsen2011]

-   O trabalho com RMarkdown[@R-rmarkdown] permite um fluxo de dados totalmente transparente, desde o conjunto de dados coletados até o manuscrito finalizado. Todos os aspectos do fluxo de dados podem ser incorporados em blocos de R script (*chunk*), exibindo tanto o R script quando o respectivo texto, tabelas e figuras formatadas no estilo científico de interesse.[@holmes2021]

-   O RMarkdown[@R-rmarkdown] foi projetado especificamente para relatórios dinâmicos onde a análise é realizada em R e oferece uma flexibilidade incrível por meio de uma linguagem de marcação.[@mair2016]

<br>

### Por que usar manuscritos reprodutíveis?

-   No processo tradicional de redação científica há muitas etapas de copiar e colar não reproduzíveis envolvidas. Documentos dinâmicos combinam uma ferramenta de processamento de texto com o R script que produz o texto/tabela/figura a ser incorporado no manuscrito.[@mair2016]

-   Ao trabalhar com relatórios dinâmicos, é possível extrair o mesmo script usado para análise estatística. Os documentos podem ser compilados em vários formatos de saída e salvos como DOCX, PPTX e PDF.[@mair2016]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *officedown*[@officedown] fornece as funções [*rdocx_document*](https://www.rdocumentation.org/packages/officedown/versions/0.3.0/topics/rdocx_document) e [*rpptx_document*](https://www.rdocumentation.org/packages/officedown/versions/0.3.0/topics/rpptx_document) para criar arquivos DOCX e PPTX, respectivamente, com o conteúdo criado no manuscrito reprodutível.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *bookdown*[@bookdown] fornece as funções [*pdf_book*](https://www.rdocumentation.org/packages/bookdown/versions/0.35/topics/pdf_book), [*bs4_book*](https://www.rdocumentation.org/packages/bookdown/versions/0.35/topics/bs4_book) e [*epub_book*](https://www.rdocumentation.org/packages/bookdown/versions/0.35/topics/epub_book) para criar arquivos PDF, HTML e EPUB, respectivamente, com o conteúdo criado no manuscrito reprodutível.
:::

<br>

### Como manuscritos reprodutíveis contribuem para a ciência?

-   O compartilhamento de bancos de dados e seus scripts de análise estatística permitem a adoção de práticas reprodutíveis, tais como a reanálise dos dados.[@ioannidis2014]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *projects*[@projects] fornece a função [*setup_projects*](https://www.rdocumentation.org/packages/projects/versions/2.1.3/topics/setup_projects) para criar um projeto com arquivos organizados em diretórios.
:::

<br>

### Como exportar tabelas em formato DOCX?

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *table1*[@flextable] fornece as funções [*as_flextable*](https://www.rdocumentation.org/packages/flextable/versions/0.9.2/topics/as_flextable) e [*save_as_docx*](https://www.rdocumentation.org/packages/flextable/versions/0.9.2/topics/save_as_docx) para salvar tabelas em formato DOCX.
:::

<br>

### Como exportar figuras em formato TIFF?

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *tiff*[@tiff] fornece a função [*writeTIFF*](https://www.rdocumentation.org/packages/tiff/versions/0.1-11/topics/writeTIFF) para exportar gráficos em formato TIFF.
:::

<br>
