# **Correlação** {#analise-inferencial-correlacao-cap}

<br>

## Análise de correlação {#analise-correlacao}

<br>

### O que é análise de correlação?

-   .[REF]

<br>

### Qual é a interpretação das medidas de correlação?

-   Os valores de correlação estão no intervalo $[-1; 1]$.[@khamis2008; @barkan2015; @allison2022]

-   Valores de correlação positivos representam uma relação direta entre as variáveis, tal que valores maiores de uma variável estão associados a valores maiores de outra variável.[@khamis2008; @allison2022]

-   Valores de correlação negativos representam uma relação indireta (ou inversa) entre as variáveis, tal que valores maiores (menores) de uma variável estão associados a valores maiores (menores) de outra variável.[@khamis2008; @allison2022]

-   Valores de correlação próximos de $0$ representam a inexistência de relação entre as variáveis.[@khamis2008; @allison2022]

<br>

### Quais precauções devem ser tomadas na interpretação de medidas de correlação?

-   Tamanhos de efeito grande (ou qualquer outro) não representam necessariamente uma relação causa-efeito entre as variáveis.[@khamis2008]

-   Tamanhos de efeito grande (ou qualquer outro) não representam necessariamente uma relação de concordância ou confiabilidade entre as variáveis.[@khamis2008]

-   Uma escala de medição grosseira (isto é, com representação agregada do constructo na coleta de dados) pode subestimar o tamanho do efeito da correlação $r$ em de cerca de 13% e do coeficiente de determinação $R^2$ de cerca de 30%.[@aguinis2008] Neste caso, a correlação desatenuada $r_{x'y'}$ pode ser calculada pela equação \@ref(eq:r-corrected), utilizando a correlação observada $r_{xy}$ e os fatores de correção $r_{xx'}$ e $r_{yy'}$ para o número de intervalos nas variáveis X e Y, respectivamennte:[@aguinis2008]

\begin{equation}
(\#eq:r-corrected)
r_{x'y'} = \dfrac{r_{xy}}{r_{xx'}r_{yy'}}
\end{equation}
<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *psychmeta*[@psychmeta] fornece a função [*correct_r_coarseness*](https://www.rdocumentation.org/packages/psychmeta/versions/2.6.5/topics/correct_r_coarseness) para calcular o coeficiente de correlação desatenuado ($r_{x'y'}$).
:::

<br>

### Quais testes podem ser usados para análises de correlação?

-   Coeficiente de correlação de Pearson ($r$).[@khamis2008; @allison2022]

    -   O coeficiente de correlação de Pearson ($r$) avalia a força e direção da relação linear entre duas variáveis quantitativas.[@khamis2008; @allison2022]

    -   Tipo: paramétrico.[@khamis2008; @allison2022]

    -   Hipóteses:[@allison2022]

        -   Nula ($H_{0}$): $r=0$

        -   Alternativa ($H_{1}$): $r≠0$

    -   Tamanho do efeito:[@khamis2008; @allison2022]

        -   Coeficiente de correlação de Pearson ($r$)

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *stats*[@stats-2] fornece a função [*cor.test*](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/cor.test) para calcular o coeficiente de correlação de Pearson ($r$).
:::

<br>

-   Coeficiente de correlação ponto-bisserial ($r_{s}$).[@khamis2008]

    -   O coeficiente de correlação ponto-bisserial ($r_{s}$) avalia a força e direção da relação linear entre uma variável quantitativa e outra dicotômica.[@khamis2008]

    -   Tipo: paramétrico.[@khamis2008]

    -   Hipóteses:[@khamis2008]

        -   Nula ($H_{0}$): $r_{s}=0$

        -   Alternativa ($H_{1}$): $r_{s}≠0$

    -   Tamanho do efeito:[@khamis2008]

        -   Coeficiente de correlação ponto-bisserial ($r_{s}$)

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *stats*[@stats-2] fornece a função [*cor.test*](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/cor.test) para calcular o coeficiente de correlação ponto-bisserial ($r_{s}$).
:::

<br>

-   Coeficiente de correlação de Spearman ($\rho$).[@khamis2008; @allison2022]

    -   O coeficiente de correlação de Spearman ($\rho$) avalia a força e direção da relação monotônica entre duas variáveis quantitativas.[@khamis2008; @allison2022]

    -   O coeficiente de correlação de Spearman ($\rho$) pode ser também definida como a correlação de Pearson ($r$) entre as classificações (*ranks*) das duas variáveis quantitativas.[@khamis2008; @allison2022]

    -   Tipo: não-paramétrico.[@khamis2008; @allison2022]

    -   Hipóteses:[@khamis2008; @allison2022]

        -   Nula ($H_{0}$): $\rho=0$

        -   Alternativa ($H_{1}$): $\rho≠0$

    -   Tamanho do efeito:[@khamis2008; @allison2022]

        -   Coeficiente de correlação de Spearman ($\rho$)

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *stats*[@stats-2] fornece a função [*cor.test*](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/cor.test) para calcular o coeficiente de correlação de Spearman ($\rho$).
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *corrplot*[@corrplot-2] fornece a função [*cor.mtest*](https://www.rdocumentation.org/packages/corrplot/versions/0.92/topics/cor.mtest) para calcular os P-valores e intervalos de confiança da matriz de correlação.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *corrplot*[@corrplot-2] fornece a função [*corrplot*](https://www.rdocumentation.org/packages/corrplot/versions/0.92/topics/corrplot) para visualização da matriz de correlação.
:::

<br>
