# **Dados, *big data* e metadados**

<br>

## Dados

<br>

### O que são dados?

-   "Tudo são dados".[@Olson2021]

-   Dados coletados em um estudo geralmente contêm erros de mensuração e/ou classificação, dados perdidos e são agrupados por alguma unidade de análise.[@van2022a]

<br>

### O que são dados primários e secundários?

-   Dados primários são dados originais coletados intencionalmente para uma determinada análise exploratória ou inferencial planejada a priori.[@vetter2017]

-   Dados secundários compreendem dados coletados inicialmente para análises de um estudo, e são subsequentemente utilizados para outras análises.[@vetter2017]

<br>

### O que são dados quantitativos e qualitativos?

-   .[@REF]

<br>

## *Big data*

<br>

### O que são *big data*?

- *Big data * refere-se a bancos de dados muito grandes com um mecanismo "R" --- aleatório (*Random*), auto-reportado (*self-Reported*), reportado administrativamente (*administratively reported*), seletivamente respondido (*selectively repondend*) ---  descontrolado ou desconhecido.[@meng2018]

<br>

## Metadados

<br>

### O que são metadados?

-   Metadados são informações técnicas relacionadas às variáveis do estudo, tais como rótulos, limites de valores plausíveis, códigos para dados perdidos e unidades de medida.[@Baillie2022]

-   Metadados também são informações relacionadas ao delineamento e/ou protocolo do estudo, recrutamento dos participantes, e métodos para realização das medidas.[@Baillie2022]

<br>

### Quais são as recomendações para os metadados de um banco de dados?

-   Utilize rótulos padronizados para variáveis e fatores para facilitar o reuso (reprodutibilidade) do conjuntos de dados e scripts de análise.[@buttliere2021]

-   Crie rótulos de variáveis concisos, claros e mutuamente exclusivos.[@buttliere2021]

-   Evite muitas letras maiúsculas ou outros caracteres especiais que usam a *shift*.[@buttliere2021]

-   Na existência de versões de instrumentos publicadas em diferentes anos, use o ano de publicação das escalas no rótulo.[@buttliere2021]

-   Divida o rótulo da variável ou fator em partes e ordene-as do mais geral para o mais particular geral (ex.: experimento -\> repetição -\> escala -\> item).[@buttliere2021]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*names*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/names) para declarar o nome de uma variável.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*labels*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/labels) para declarar o rótulo de uma variável.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *units*[@units] fornece a função [*units*](https://www.rdocumentation.org/packages/units/versions/0.8-3/topics/units) para declarar as unidades de medida de uma variável.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *units*[@units] fornece a função [*valid_udunits*](https://www.rdocumentation.org/packages/units/versions/0.8-3/topics/valid_udunits) para listar as opções de unidades de medida de uma variável.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *janitor*[@janitor] fornece a função [*clean_names*](https://www.rdocumentation.org/packages/janitor/versions/2.2.0/topics/clean_names) para formatar de modo padronizado o nome das variáveis utilizando apenas caracteres, números e o símbolo '\_'.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *Hmisc*[@Hmisc] fornece a função [*contents*](https://www.rdocumentation.org/packages/Hmisc/versions/5.1-0/topics/contents) para criar um objeto com os metadados (nomes, rótulos, unidades, quantidade e níveis das variáveis categóricas, e quantidade de dados perdidos) de um dataframe.
:::

<br>
