# **Delineamento de estudos** {#delineamento-estudos}

<br>

## Relação Estatística-Epidemiologia

<br>

### Qual a relação entre estatística e epidemiologia?

-   .[@munafò2017]

<br>

```{r, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', results = "asis", fig.fullwidth = TRUE, fig.cap = "Mapa mental da relação entre o pensamento estatístico e o pensamento metodológico."}

DiagrammeR::mermaid("

graph TB

A(Projeto <br/>de pesquisa) --- B(Geração e especificação <br/> de hipóteses)
B(Geração e especificação <br/> de hipóteses)-->C(Delineamento <br/> do estudo)
C(Delineamento do estudo)-->D(Realização do estudo <br/> e coleta de dados)
D(Realização do estudo e coleta de dados)-->E(Análise de dados e teste de hipóteses)
E(Análise de dados <br/> e teste de hipóteses)-->F(Interpretação de resultados)
F(Interpretação <br/> de resultados)-->G(Publicação e/ou realização <br/> do próximo experimento)

H(Elaboração das hipóteses <br/> nula e alternativa)-.->B(Geração e especificação <br/> de hipóteses)
I(Seleção das análises <br/> descritiva/inferencial e testes)-.->C(Delineamento <br/> do estudo)
J(Análise inicial <br/> de dados)-.->D(Realização do estudo <br/> e coleta de dados)
K(Análise <br/> inferencial)-.->E(Análise de dados <br/> e teste de hipóteses)
L(Tamanho do efeito <br/> e P-valor)-.->F(Interpretação <br/> de resultados)
M(Redação <br/> dos resultados)-.->G(Publicação e/ou realização <br/> do próximo experimento)

H-->I
I-->J
J-->K
K-->L
L-->M

style H fill:#FFFFFF00;
style I fill:#FFFFFF00;
style J fill:#FFFFFF00;
style K fill:#FFFFFF00;
style L fill:#FFFFFF00;
style M fill:#FFFFFF00;

")
```

<br>

## Delineamento de estudos {#delineamento-estudos}

<br>

### Como podem ser classificados os estudos científicos?

-   Estudos científicos podem ser classificados em *básicos*, *observacionais*, *experimentais*, *acurácia diagnóstica*, *propriedades psicométricas*, *avaliação econômica* e *revisões de literatura*:[@Grant2009; @Süt2014; @Souza2017; @reeves2017; @echevarría-guanilo2019; @Chassé2019; @Chidambaram2019; @Erdemir2020; @Yang2021; @chipman2022]

-   *Estudos básicos*[@Süt2014; @Chidambaram2019]

    -   Genética

    -   Celular

    -   Experimentos com animais

    -   Desenvolvimento de métodos

-   *Estudos de simulação computacional*[@Erdemir2020; @chipman2022]

-   *Estudos observacionais*[@Süt2014; @Chidambaram2019]

    -   Descritivo

        -   Estudo de caso

        -   Série de casos

        -   Transversal

    -   Analítico

        -   Transversal

        -   Caso-Controle

            -   Caso-Controle aninhado

            -   Caso-Coorte

    -   Coorte prospectiva ou retrospectiva

-   *Estudos de desempenho diagnóstico*[@Chassé2019; @Yang2021]

    -   Transversal

    -   Caso-Controle

    -   Comparativo

    -   Totalmente pareado

    -   Parcialmente pareado com subgrupo aleatório

    -   Parcialmente pareado com subgrupo não aleatório

    -   Não pareado aleatório

    -   Não pareado não aleatório

-   *Estudos de propriedades psicométricas*[@Souza2017; @echevarría-guanilo2019]

    -   Validade

    -   Confiabilidade

    -   Concordância

-   *Estudos quase-experimentais*[@reeves2017]

    -   Quase-aleatorizado controlado

    -   Estimação de variável instrumental

    -   Descontinuidade de regressão

    -   Série temporal interrompida controlada

    -   Série temporal interrompida

    -   Diferença

-   *Estudos experimentais*[@Süt2014; @Chidambaram2019]

    -   Fases I a IV

        -   Aleatorizado controlado

        -   Não-aleatorizado controlado

        -   Autocontrolado

        -   Cruzado

        -   Fatorial

    -   Campo

    -   Comunitário

-   *Estudos de avaliação econômica*[@Süt2014]

    -   Análise de custo

    -   Análise de minimização de custo

    -   Análise de custo-utilidade

    -   Análise de custo-efetividade

    -   Análise de custo-benefício

-   *Estudos de revisão*[@Grant2009]

    -   Estado-da-arte

    -   Narrativa

    -   Crítica

    -   Mapeamento

    -   Escopo

    -   Busca e revisão sistemática

    -   Sistematizada

    -   Sistemática

        -   Meta-análise

        -   Bibliométrica.[@donthu2021; @lim2023]

    -   Sistemática qualitativa

    -   Mista

    -   Visão geral

    -   Rápida

    -   Guarda-chuva

<br>

## Pareamento {#pareamento}

<br>

### O que é pareamento?

-   Pareamento significa que para cada participante de um grupo (por exemplo, com alguma condição clínica), existe um (ou mais) participantes (por exemplo, grupo controle) que possui características iguais ou similares relativas a algumas variáveis de interesse.[@Bland1994]

-   As variáveis escolhidas para pareamento devem ter relação com as variáveis de desfecho, mas não são de interesse elas mesmas.[@Bland1994]

-   O ajuste por pareamento deve ser incluído nas análises estatísticas mesmo que as variáveis de pareamento não sejam consideradas prognósticas ou confundidores na amostra estudada.[@Bland1994]

-   A ausência de evidência estatística de diferença entre grupos não é considerada pareamento.[@Bland1994]

<br>

## Aleatorização {#aleatorização}

-   .[REF]

<br>

### O que é aleatorização?

<br>

## Alocação {#alocacao}

<br>

### O que é alocação?

-   .[REF]

<br>

## Cegamento {#cegamento}

-   .[REF]

<br>

### O que é cegamento?

<br>
