# **Desempenho diagnóstico** {#analise-desempenho-diagnostico}

<br>

## Tabelas 2x2 {#tabelas-2x2}

<br>

### Como analisar o desempenho diagnóstico em tabelas 2x2?

-   Acurácia.[REF]

-   Sensibilidade.[REF]

-   Especificidade.[REF]

-   Valor preditivo positivo.[REF]

-   Valor preditivo negativo.[REF]

<br>

## Curvas ROC {#curvas-roc}

<br>

### O que é área sob a curva (ROC)?

-   A área sob a curva ROC (AUC ou AUROC) quantifica o poder de discriminação ou desempenho diagnóstico na classificação de uma variável dicotômica.[@de2022]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *proc*[@pROC] fornece a função [*plot.roc*](https://www.rdocumentation.org/packages/pROC/versions/1.18.4/topics/plot.roc) para criar uma curva ROC.
:::

<br>

### Como interpretar a área sob a curva (ROC)?

-   A área sob a curva AUC varia no intervalo $[0.5; 1]$, com valores mais elevados indicando melhor discriminação ou desempenho do modelo de classificação.[@de2022]

-   As interpretações qualitativas (isto é, pobre/fraca/baixa, moderada/razoável/aceitável, boa ou muito boa/alta/excelebt) dos valores de área sob a curva são arbitrários e não devem ser considerados isoladamente.[@de2022]

-   Modelos de classificação com valores altos de área sob a curva podem ser enganosos se os valores preditos por esses modelos não estiverem adequadamente calibrados.[@de2022]

<br>

### Como analisar o desempenho diagnóstico em desfechos com distribuição trimodal na população?

-   Limiares duplos podem ser utilizados para análise de desempenho diagnóstico de testes com distribuição trimodal.[@ferreira2021]

<br>
