# **Distribuições e parâmetros**

<br>

## Distribuições de probabilidade

<br>

### O que são distribuições de probabilidade?

-   Uma distribuição de probabilidade é uma função que descreve os valores possíveis ou o intervalo de valores de uma variável (eixo horizontal) e a frequência com que cada valor é observado (eixo vertical).[@vetter2017]

<br>

### Como representar distribuições de probabilidade?

-   Tabelas de frequência, polígonos de frequência, gráficos de barras, histogramas e *boxplots* são formas de representar distribuições de probabilidade.[@s2011]

-   Tabelas de frequência mostram as categorias de medição e o número de observações em cada uma. É necessário conhecer o intervalo de valores (mínimo e máximo), que é dividido em intervalos arbitrários chamados "intervalos de classe".[@s2011]

-   Se houver muitos intervalos, não haverá redução significativa na quantidade de dados, e pequenas variações serão perceptíveis. Se houver poucos intervalos, a forma da distribuição não poderá ser adequadamente determinada.[@s2011]

-   A largura das classes pode ser determinada dividindo o intervalo total de observações pelo número de classes. Recomenda-se que as larguras sejam iguais, e larguras desiguais devem ser usadas apenas quando existirem grandes lacunas nos dados. Os intervalos devem ser mutuamente exclusivos e não sobrepostos, evitando intervalos abertos (ex.: \<5, \>10).[@s2011]

-   Polígonos de frequência são gráficos de linhas que conectam os pontos médios de cada barra do histograma. Eles são úteis para comparar duas ou mais distribuições de frequência.[@s2011]

-   Gráficos de barra verticais ou horizontais representam a distribuição de frequências de uma variável categórica. A altura de cada barra é proporcional à frequência da classe. A largura da barra é igual à largura da classe. A área de cada barra é proporcional à frequência da classe. A área total do gráfico de barras é igual ao número total de observações.[@s2011]

-   Histogramas representam a distribuição de frequências de uma variável contínua. A altura de cada barra é proporcional à frequência da classe. A largura da barra é igual à largura da classe. A área de cada barra é proporcional à frequência da classe. A área total do histograma é igual ao número total de observações.[@s2011]

-   *Boxplots* representam a distribuição de frequências de uma variável contínua. A linha central divide os dados em duas partes iguais (mediana ou Q2). A caixa inferior representa o primeiro quartil (Q1) e a caixa superior representa o terceiro quartil (Q3). A linha inferior é o mínimo e a linha superior é o máximo. Os valores atípicos são representados por pontos individuais.[@s2011]

<br>

### Quais características definem uma distribuição?

-   Uma distribuição pode ser definida por modelos matemáticos e caracterizada por parâmetros de tendência central, dispersão, simetria e curtose.

<br>

### Quais são as distribuições mais comuns?

-   Distribuções discretas:

    -   Uniforme: resultados (finitos) que são igualmente prováveis. [REF]

    -   Binomial: número de sucessos em *k* tentativas. [REF]

    -   Poisson: número de eventos em um intervalo de tempo fixo.[REF]

    -   Bernoulli: .[REF]

    -   Geométrica: número de testes até o 1o sucesso.[REF]

    -   Binomial negativa: número de testes até o *k*-ésimo sucesso.[REF]

    -   Hipergeométrica: número de indivíduos na amostra tomados sem reposição. [REF]

-   Distribuições contínuas:

    -   Uniforme: resultados que possuem a mesma densidade.[REF]

    -   Exponencial: tempo entre eventos.[REF]

    -   Normal: .[REF]

    -   Normal padrão: .[REF]

    -   Aproximação binomial: número de sucessos em uma grande quantidade de tentativas.[REF]

    -   Aproximação Poisson: número de ocorrências em um intervalo de tempo fixo.[REF]

    -   Qui-quadrado: .[REF]

    -   t-Student: .[REF]

    -   Weibull: .[REF]

    -   Log-normal: .[REF]

    -   Beta: .[REF]

    -   Gama: .[REF]

    -   Logística: .[REF]

    -   Pareto. [REF]

<br>

### Quais são as funções de uma distribuição?

-   Função de massa de probabilidade (*probability mass function*, pmf).[REF]

-   Função de distribuição cumulativa (*cumulative distribution function*, cdf).[REF]

-   Função quantílicas (*quantile function*, qf).[REF]

-   Função geradora de números aleatórios (*random function*, rf).[REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *stats*[@stats-3] fornece funções de distribuição de probabilidade (p), funções de densidade (d), funções quantílicas (q) e funções geradores de números aleatórios (r) para as distribuições [normal](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Normal), [Student t](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/TDist), [binomial](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Binomial), [qui-quadrado](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Chisquare), [uniforme](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Uniform), dentre outras.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *ggdist*[@ggdist] fornece a função [geom_slabinterval](https://www.rdocumentation.org/packages/ggdist/versions/3.3.0/topics/geom_slabinterval) para criar gráficos de distribuição de probabilidade (p) e funções de densidade (d) as distribuições.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *ggfortify*[@ggfortify] fornece a função [ggdistribution](https://www.rdocumentation.org/packages/ggfortify/versions/0.4.16/topics/ggdistribution) para criar gráficos de distribuição de probabilidade (p), funções de densidade (d), funções quantílicas (q) e funções geradores de números aleatórios (r) para as distribuições.
:::

<br>

### O que é a distribuição normal?

-   A distribuição normal (ou gaussiana) é uma distribuição com desvios simétricos positivos e negativos em torno de um valor central.[@Ali2016]

-   Em uma distribuição normal, o intervalo de 1 desvio-padrão (±1DP) inclui cerca de 68% dos dados; de 2 desvios-padrão (±2DP) cerca de 95% dos dados; e no intervalo de 3 desvios-padrão (±3DP) cerca de 99% dos dados.[@Ali2016]

<br>

```{r distribuicao-normal, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', results = "asis", fig.fullwidth = TRUE, fig.cap = "Distribuições e funções de probabilidade"}

scaleFUN <- function(x) sprintf("%.2f", x)

# normal
d1 <- ggfortify::ggdistribution(dnorm,
                                seq(-3, 3, 0.1),
                                mean = 0,
                                sd = 1,
                                main = "Distribuição de probabilidade") + ggplot2::scale_y_continuous(labels = scaleFUN) + ggplot2::theme_minimal() + ggplot2::theme(aspect.ratio = 1)

p1 <- ggfortify::ggdistribution(pnorm,
                                seq(-3, 3, 0.1),
                                mean = 0,
                                sd = 1,
                                main = "Função de distribuição cumulativa") + ggplot2::scale_y_continuous(labels = scaleFUN) + ggplot2::theme_minimal() + ggplot2::theme(aspect.ratio = 1)

ggpubr::ggarrange(d1, p1, heights = c(1, 1), widths = c(1, 1), nrow = 1, ncol = 2, align = "h")

```

<br>

### Que métodos podem ser utilizados para identificar a normalidade da distribuição?

-   Histogramas.[@vetter2017]

-   Gráficos Q-Q.[@vetter2017]

-   Testes de hipótese nula:[@vetter2017]

    -   Kolmogorov-Smirnov

    -   Shapiro-Wilk

    -   Anderson-Darling

<br>

### O que são distribuições não-normais?

-   .[REF]

<br>

## Parâmetros

<br>

### O que são parâmetros?

-   Parâmetros são informações que definem um modelo teórico, como propriedades de uma coleção de indivíduos.[@Altman1999]

-   Parâmetros definem características de uma população inteira, tipicamente não observados por ser inviável ter acesso a todos os indivíduos que constituem tal população.[@vetter2017]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*summary*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary) para calcular diversos parâmetros descritivos.
:::

<br>

### O que é uma análise paramétrica?

-   Testes paramétricos possuem suposições sobre as características e/ou parâmetros da distribuição dos dados na população.[@vetter2017]

-   Testes paramétricos assumem que: a variável é quantitativa numérica (contínua); os dados foram amostrados de uma população com distribuição normal; a variância da(S) amostra(s) é igual à da população; as amostras foram selecionadas de modo aleatório na população; os valores de cada amostra são independentes entre si.[@Ali2016; @vetter2017]

-   Testes paramétricos são baseados na suposição de que os dados amostrais provêm de uma população com parâmetros fixos determinando sua distribuição de probabilidade.[@kwak2017]

<br>

### O que é uma análise não paramétrica?

-   Testes não-paramétricos fazem poucas suposições, ou menos rigorosas, sobre as características e/ou parâmetros da distribuição dos dados na população.[@Ali2016; @vetter2017]

-   Testes não-paramétricos são úteis quando as suposições de normalidade não podem ser sustentadas.[@Ali2016]

<br>

### Por que as análises paramétricas são preferidas?

-   Em geral, testes paramétricos são mais robustos (isto é, possuem menores erros tipo I e II) que seus testes não-paramétricos correspondentes.[@greenhalgh1997; @vetter2017]

-   Testes não-paramétricos apresentam menor poder estatístico (maior erro tipo II) comparados aos testes paramétricos correspondentes.[@Ali2016]

<br>

### Que parâmetros podem ser estimados?

-   Parâmetros de tendência central.[@kanji2006; @Ali2016]

-   Parâmetros de dispersão.[@kanji2006; @Ali2016; @Curran-Everett2008]

-   Parâmetros de proporção.[@Altman1994; @kanji2006; @Ali2016; @Altman1994]

-   Parâmetros de distribuição.[@kanji2006]

-   Parâmetros de extremos.[@Ali2016]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*summary*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary) para calcular diversos parâmetros descritivos.
:::

<br>

## Tendência central

<br>

### Que parâmetros de tendência central podem ser estimados?

-   *Média*: aritmética, ponderada, geométrica ou harmônica.[@kanji2006; @Ali2016; @s.2011a]

-   *Mediana*.[@kanji2006; @Ali2016; @s.2011]

-   *Moda*.[@kanji2006; @Ali2016; @s.2011]

-   A posição relativa das medidas de tendência central (média, mediana e moda) depende da forma da distribuição.[@s.2011]

-   Em uma distribuição normal, as três medidas são idênticas.[@s.2011]

-   A média é sempre puxada para os valores extremos, por isso é deslocada para a cauda em distribuições assimétricas.[@s.2011]

-   A mediana fica entre a média e a moda em distribuições assimétricas.[@s.2011]

-   A moda é o valor mais frequente e, portanto, se localiza no pico da distribuição assimétrica.[@s.2011]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*summary*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary) para calcular diversos parâmetros descritivos.
:::

<br>

### Como escolher o parâmetro de tendência central?

-   A mediana é preferida à média quando existem poucos valores extremos na distribuição, alguns valores são indeterminados, ou há uma distribuição aberta, ou os dados são medidos em uma escala ordinal.[@s.2011]

-   A moda é preferida quando os dados são medidos em uma escala nominal.[@s.2011]

-   A média geométrica é preferida quando os dados são medidos em uma escala logarítmica.[@s.2011]

<br>

## Dispersão

<br>

### Que parâmetros de dispersão podem ser estimados?

-   *Variância*.[@kanji2006; @Ali2016]

-   *Desvio-padrão*: Informam sobre a dispersão da população e são, portanto, úteis como preditores da variação em novas amostras.[@Curran-Everett2008; @krzywinski2013; @manikandan2011]

-   *Erro-padrão*: Refletem a incerteza na média e sua dependência do tamanho da amostra.[@Curran-Everett2008; @krzywinski2013]

-   *Amplitude*.[@kanji2006; @Ali2016; @manikandan2011]

-   *Intervalo interquartil*.[@kanji2006; @Ali2016; @manikandan2011]

-   *Intervalo de confiança*: Captura a média populacional % do tempo correspondente ao nível de significância $\alpha$ pré-estabelecido .[@kanji2006; @Cumming2007; @krzywinski2013; @Ali2016]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*summary*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary) para calcular diversos parâmetros descritivos.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *stats*[@stats-4] fornece a função [*confint*](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/confint) para calcular o intervalo de confiança em um nível de significância $\alpha$.
:::

<br>

### Como escolher o parâmetro de dispersão?

<br>

- Desvio-padrão é apropriado quando a média é utilizada como parâmetro de tendência central em distribuições simétricas.[@manikandan2011]

- Amplitue ou intervalo interquartil são apropriadas para variáveis ordinais ou distribuições assimétricas.[@manikandan2011]

<br>

## Proporção

<br>

### Que parâmetros de proporção podem ser estimados?

-   *Frequência absoluta*.[@Altman1994; @kanji2006; @Ali2016]

-   *Frequência relativa*.[@Altman1994; @kanji2006; @Ali2016]

-   *Percentil*.[@Altman1994; @kanji2006; @Ali2016]

-   *Quantil*: é o ponto de corte que define a divisão da amostra em grupos de tamanhos iguais. Portanto, não se referem aos grupos em si, mas aos valores que os dividem:[@Altman1994]

    -   Tercil: 2 valores que dividem a amostra em 3 grupos de tamanhos iguais.[@Altman1994]

    -   Quartil: 3 valores que dividem a amostra em 4 grupos de tamanhos iguais.[@Altman1994]

    -   Quintil: 4 valores que dividem a amostra em 5 grupos de tamanhos iguais.[@Altman1994]

    -   Decil: 9 valores que dividem a amostra em 10 grupos de tamanhos iguais.[@Altman1994]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*summary*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary) para calcular diversos parâmetros descritivos.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*table*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table) para calcular proporções.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *stats*[@base] fornece a função [*quantile*](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile) para executar análise de percentis.
:::

<br>

## Distribuição

<br>

### Que parâmetros de distribuição podem ser estimados?

-   *Assimetria*.[@kanji2006]

-   *Curtose*.[@kanji2006]

<br>

## Extremos

<br>

### Que parâmetros extremos podem ser estimados?

-   *Mínimo*.[@Ali2016]

-   *Máximo*.[@Ali2016]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*summary*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary) para calcular diversos parâmetros descritivos.
:::

<br>

## Valores discrepantes

<br>

### O que são valores discrepantes (*outliers*)?

-   Em termos gerais, um valor discrepante - "fora da curva" ou *outlier* - é uma observação que possui um valor relativamente grande ou pequeno em comparação com a maioria das observações.[@zuur2009]

-   Mais especificamente, um valor discrepante é uma observação incomum que exerce influência indevida em uma análise.[@zuur2009]

<br>

### Como conduzir análises com valores discrepantes?

-   Erros de observação e de medição são uma justificativa válida para descartar observações discrepantes.[@zuur2009]

-   Valores discrepantes na variável de desfecho podem exigir uma abordagem mais refinada, especialmente quando representam uma variação real na variável que está sendo medida.[@zuur2009]

-   Valores discrepantes em uma (co)variável podem surgir devido a um projeto experimental inadequado; nesse caso, abandonar a observação ou transformar a covariável são opções adequadas.[@zuur2009]

-   É importante reportar se existem valores discrepantes e como foram tratados.[@zuur2009]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *outliers*[@outliers] fornece a função [*outlier*](https://www.rdocumentation.org/packages/outliers/versions/0.15/topics/outlier) para identificar os valores mais distantes da média.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *outliers*[@outliers] fornece a função [*rm.outlier*](https://www.rdocumentation.org/packages/outliers/versions/0.15/topics/rm.outlier) para remover os valores mais distantes da média detectados por testes de hipótese e/ou substitui-los pela média ou mediana.
:::

<br>
