# **Ensaio clínico aleatorizado** {#ensaio-clínico-aleatorizado}

<br>

## Características {#caracteristicas}

<br>

### Quais são as características dos ensaios clínicos aleatorizados?

-   A característica essencial de um ensaio clínico aleatorizado é a comparação entre grupos.[@bland2011]

-   Quanto à unidade de alocação:[@Bruce2022]

    -   Individual

    -   Agrupado

-   Quanto ao número de braços:[@Bruce2022]

    -   Único\*

    -   Múltiplos

-   Quanto ao número de centros:[@Bruce2022]

    -   Único

    -   Múltiplos

-   Quanto ao cegamento:[@Bruce2022]

    -   Aberto\*

    -   Simples-cego

    -   Duplo-cego

    -   Tripo-cego

    -   Quádruplo-cego

-   Quanto à alocação:[@Bruce2022]

    -   Sem sorteio

    -   Estratificada (centro apenas)

    -   Estratificada

    -   Minimizada

    -   Estratificada e minimizada

<br>

## Modelos de análise de comparação {#metodos-comparacao}

<br>

### Que modelos podem ser utilizados para comparações?

-   As abordagens compreendem a comparação da variável de desfecho medida entre os momentos antes e depois ou da sua mudança (pré - pós) entre os momentos.[@Vickers2001]

-   Se a média da variável é igual entre grupos no início do acompanhamento, ambas abordagens estimam o mesmo efeito. Caso contrário, o efeito será influenciado pela correlação entre as medidas antes e depois. A análise da mudança não controla para desbalanços no início do estudo. [@Vickers2001]

-   Uma abordagem recomendada é a análise de covariância (ANCOVA), pois ajusta os valores pós-intervenção aos valores pré-intervenção para cada participante, e não é afetada pelas diferenças entre grupos no início do estudo.[@Vickers2001]

-   A análise de covariância (ANCOVA) modelando seja a mudança (pré - pós) quando o desfecho no pós-tratamento parece ser o método mais efetivo considerando-se o viés de estimação dos parâmetros, a precisão das estimativas, a cobertura nominal (isto é, intervalo de confiança) e o poder do teste.[@OConnell2017]

-   Análise de variância (ANOVA) e modelos lineares mistos (MLM) são outras opções de métodos, embora apresentem maior variância, menor poder, e cobertura nominal comparados à ANCOVA.[@OConnell2017]

-   .[@Cnaan1997]

-   .[@mallinckrodt2008]

<br>

## Comparação na linha de base {#comparacao-linha-de-base}

<br>

### O que são dados na linha de base?

- Dados sociodemográficos, clínicos e funcionais são coletados na linha de base sobre cada participante no momento da aleatorização.[@Assmann2000]

- Os dados de linha de base são usados para caracterizar os pacientes incluídos no estudo e para mostrar que os grupos de tratamento estão bem equilibrados.[@Assmann2000]

- Dados da linha de base podem ser utilizados para a aleatorização de modo a equilíbrar ou estratificar os grupos considerando alguns fatores-chave.[@Assmann2000]

- Dados da linha de base podem ser utilizados como ajuste de covariável para análise do resultado por grupo de tratamento.[@Assmann2000]

<br>

### O que é comparação entre grupos na linha de base em ensaios clínicos aleatorizados?

-   A comparação se refere ao teste de hipótese nula de não haver diferença ('balanço' ou 'equilíbrio') entre grupos de tratamento nas (co)variáveis na linha de base, geralmente apresentadas apenas de modo descritivo na 'Tabela 1'.[@Stang2018]

-   A interpretação isolada do P-valor da comparação entre grupos na linha de base não permite identificar as razões para eventuais diferenças.[@Stang2018]

<br>

### Para quê comparar grupos na linha de base em ensaios clínicos aleatorizados?

-   Os P-valores estão relacionados à aleatorização dos participantes em grupos.[@Bolzern2019]

-   Em ensaios clínicos aleatorizados, a comparação de (co)variáveis na linha de base é usada para avaliar se aleatorização foi 'bem sucedida'.[@Bolzern2019]

<br>

### Quais são as razões para diferenças entre grupos de tratamento nas (co)variáveis na linha de base?

-   Acaso.[@Stang2018; @chen2020]

-   Viés.[@Stang2018; @chen2020]

-   Tamanho da amostra.[@Stang2018; @chen2020]

-   Má conduta científica.[@chen2020]

<br>

### Quais cenários permitem a comparação entre grupos na linha de base em ensaios clínicos aleatorizados?

-   Em ensaios clínicos aleatorizados agregados, os P-valores possuem interpretação diferente de estudos aleatorizados individualmente.[@Bolzern2019]

-   Em ensaios clínicos com agrupamento, nos quais o recrutamento ocorreu após a aleatorização, os P-valores já não estão inteiramente relacionados ao processo de aleatorização, mas sim ao método de recrutamento, o que pode resultar na comparação de amostras não aleatórias.[@Bolzern2019]

<br>

### Por que não se deve comparar grupos na linha de base em ensaios clínicos aleatorizados?

-   A interpretação errônea dos P-valores na comparação entre grupos, na linha de base, de um ensaio clínico aleatorizado constitui a 'falácia da Tabela 1'.[@pijls2022]

-   Quando a aleatorização é bem-sucedida, a hipótese nula de diferença entre grupos na linha de base é verdadeira.[@roberts1999]

-   Testes de significância estatística na linha de base avaliam a probabilidade de que as diferenças observadas possam ter ocorrido por acaso; no entanto, já sabemos - pelo delineamento do experimento - que quaisquer diferenças são causadas pelo acaso.[@gruijters2020]

<br>

### Quais estratégias podem ser adotadas para substituir a comparação entre grupos na linha de base em ensaios clínicos aleatorizados?

-   Na fase de projeto: identifique as variáveis prognósticas do desfecho de acordo com a literatura.[@roberts1999]

-   Na fase de análise: inclua as variáveis prognósticas nos modelos para ajuste.[@roberts1999]

<br>

## Comparação intragrupos {#comparacao-intragrupos}

<br>

### Por que não se deve comparar intragrupos (pré - pós) em ensaios clínicos aleatorizados?

-   Testar por mudanças a partir da linha de base separadamente em cada grupos aleatorizados não permite concluir sobre diferenças entre grupos; não se pode fazer inferências a partir da comparação de P-valores.[@bland2011]

<br>

## Comparação entre grupos {#comparacao-entre-grupos}

<br>

### O que é comparação entre grupos em ensaios clínicos aleatorizados?

-   A comparação se refere ao teste de hipótese nula de não haver diferença ('alteração' ou 'mudança') pós-tratamento entre grupos de tratamento.[@bland2011]

<br>

## Comparação de subgrupos {#comparacao-subgrupos}

<br>

### O que é comparação de subgrupos em ensaios clínicos aleatorizados?

- Análises de subgrupos podem ser realizadas para avaliar se as diferenças no resultado do tratamento (ou a falta delas) dependem de algumas características na linha de base dos pacientes.[@Assmann2000]

<br>

### Como realizar a comparação de subgrupos em ensaios clínicos aleatorizados?

- Testes estatísticos de interação (que avaliam se um efeito de tratamento difere entre subgrupos) devem ser usados, e não apenas a inspeção dos P-valores do subgrupo. Somente se o teste de interação estatística apoiar um efeito de subgrupo as conclusões poderão ser influenciadas.[@Assmann2000; @Brookes2004]

<br>

### Como interpretar a comparação de subgrupos em ensaios clínicos aleatorizados?

-   Análises de subgrupos devem ser consideradas de natureza exploratória e raramente elas afetam as conclusões obtidas a partir do estudo.[@Assmann2000; @Brookes2004]

<br>

- A credibilidade das análises de subgrupos é melhor se restrita ao desfecho primário e a alguns subgrupos predefinidos e baseadas em hipóteses biologicamente plausíveis.[@Assmann2000]

- Deve-se verificar se o estudo possui poder estatístico suficiente para detectar tamanhos de efeitos realistas em subgrupos e interpretar com cautela uma diferença de tratamento em um subgrupo quando a comparação global do tratamento não é significativa.[@Assmann2000]

<br>

## Efeito de interação {#interacao}

<br>

### Por que analisar o efeito de interação?

-   Em ensaios clínicos aleatorizados, o principal problema de pesquisa é se há uma diferença pré - pós maior em um grupo do que em outro(s).[@bland2011]

-   A comparação de subgrupos por meio de testes de significância de hipótese nula separados é enganosa por não testar (comparar) diretamente os tamanhos dos efeitos dos tratamentos.[@Matthews1996]

-   .[@Bours2023]

<br>

### Quando usar o termo de interação?

-   Análise de efeito de interação pode ser usada para testar se o efeito de um tratamento varia entre dois ou mais subgrupos de indivíduos, ou seja, se um efeito é modificado pelo(s) outros(s) efeito(s).[@Altman1996]

-   A interação entre duas (ou mais) variáveis pode ser utilizada para comparar efeitos do tratamento em subgrupos de ensaios clínicos.[@Altman2003]

-   O poder estatístico para detectar efeitos de interação é limitado.[@Altman2003]

<br>

## Ajuste de covariáveis {#ajuste-de-covariaveis}

<br>

### Quais variáveis devem ser utilizadas no ajuste de covariáveis?

-   A escolha das características de linha de base pelas quais uma análise é ajustada deve ser determinada pelo conhecimento prévio de uma possível influência no resultado, em vez da evidência de desequilíbrio entre os grupos de tratamento no estudo.[@roberts1999]

<br>

### Quais os benefícios do ajuste de covariáveis?

-   Ajustar por covariáveis ajuda a estimar os efeitos do tratamento para o indivíduo, assim como aumenta a eficiência dos testes para hipótese nula e a validade externa do estudo.[@Hauck1998]

-   Incluir a variável de desfecho medida na linha de base como covariável - independentemente de a análise ser realizada com a medida pós-tratamento da mesma variável ou a diferença para a linha de base - pode aumentar o poder estatístico do estudo.[@Kahan2014]

-   Incluir outras variáveis medidas na linha de base, com potencial para serem desbalanceadas entre grupos após a aleatorização, diminui a chance de afetar as estimativas de efeito dos tratamentos.[@Kahan2014]

<br>

### Quais os riscos do ajuste de covariáveis?

-   Incluir covariáveis que não são prognósticas do desfecho pode reduzir o poder estatístico do estudo.[@Kahan2014]

-   Incluir covariáveis com dados perdidos pode reduzir o tamanho amostral e consequentemente o poder estatístico do estudo (análise de casos completos) ou levar a desvios do plano de análise por exclusão de covariáveis prognósticas.[@Kahan2014]

<br>

## Imputação de dados perdidos {#imputacao-dados}

<br>

### Como lidar com os dados perdidos em desfechos?

-   Em dados longitudinais com um pequeno número de 'ondas' (medidas repetidas) e poucas variáveis, para análise com modelos de regressão univariados, a imputação paramétrica via especificação condicional completa - também conhecido como imputação multivariada por equações encadeadas (*multivariate imputation by chained equations*, MICE) - é eficiente do ponto de vista computacional e possui acurácia e precisão para estimação de parâmetros.[@Cao2022; @Heymans2022]

-   Para dados perdidos em desfechos dicotômicos, o desempenho dos métodos de imputação multivariada por equações encadeadas (*multivariate imputation by chained equations*, MICE)[@mice] e por correspondência média preditiva (*predictive mean matching*, PMM)[@rubin1986; @little1988a] é similar.[@austin2023]

<br>

### Como lidar com os dados perdidos em covariáveis?

-   Imputação de dados perdidos de uma covariável pela média dos dados do respectivo grupo permite estimativas não enviesadas dos efeitos do tratamento, preserva o erro tipo I e aumenta o poder estatístico comparado à análise de dados completos.[@Kahan2014]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
Os pacotes *mice*[@mice] e *miceadds*[@miceadds] fornecem funções [*mice*](https://www.rdocumentation.org/packages/mice/versions/3.16.0/topics/mice) e [*mi.anova*](https://www.rdocumentation.org/packages/miceadds/versions/3.16-18/topics/mi.anova) para imputação multivariada por equações encadeadas, respectivamente, para imputação de dados.
:::

<br>
