# **Fontes externas** {-}

<br>

## Diretrizes {-}

-   *Review of guidance papers on regression modeling in statistical series of medical journals*.[@Wallisch2022]

-   *Principles and recommendations for incorporating estimands into clinical study protocol templates*.[@Lynggaard2022]

-   *How to write statistical analysis section in medical research*.[@Dwivedi2022]

-   *Recommendations for Statistical Reporting in Cardiovascular Medicine: A Special Report From the American Heart Association*.[@Althouse2021]

-   *Framework for the treatment and reporting of missing data in observational studies: The Treatment And Reporting of Missing data in Observational Studies framework*.[@Lee2021]

-   *Guidelines for reporting of figures and tables for clinical research in urology*.[@Vickers2020]

-   *Who is in this study, anyway? Guidelines for a useful Table 1*.[@Hayes-Larson2019]

-   *Guidelines for Reporting of Statistics for Clinical Research in Urology*.[@assel2019]

-   *Reveal, Don't Conceal: Transforming Data Visualization to Improve Transparency*.[@Weissgerber2019]

-   *Guidelines for the Content of Statistical Analysis Plans in Clinical Trials*.[@Gamble2017]

-   *Basic statistical reporting for articles published in Biomedical Journals: The ''Statistical Analyses and Methods in the Published Literature'' or the SAMPL Guidelines*.[@Lang2015]

-   *Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm*.[@Weissgerber2015]

-   *STRengthening analytical thinking for observational studies: the STRATOS initiative*.[@Sauerbrei2014]

-   *Research methods and reporting*.[@groves2008]

-   *How to ensure your paper is rejected by the statistical reviewer*.[@stratton2005]

<br>

## Listas de verificação {-}

-   *A CHecklist for statistical Assessment of Medical Papers (the CHAMP statement): explanation and elaboration*.[@Mansournia2021]

-   *Checklist for clinical applicability of subgroup analysis*.[@Gil-Sierra2020]

-   *Evidence‐based statistical analysis and methods in biomedical research (SAMBR) checklists according to design features*.[@dwivedi2019]

<br>

## American Heart Association {-}

-   [*Statistical Reporting Recommendations - AHA/ASA journals*](https://www.ahajournals.org/statistical-recommendations)

<br>

## American Physiological Society {-}

-   [*Statistics*](https://journals.physiology.org/topic/advances-collections/statistics?seriesKey=&tagCode=&)

-   [*Exploration in Statistics*](https://journals.physiology.org/topic/advances-collections/explorations-in-statistics?seriesKey=&tagCode=&)

-   [*General Statistics*](https://journals.physiology.org/topic/advances-collections/general-statistics?seriesKey=&tagCode=&)

-   [*Reporting Statistics*](https://journals.physiology.org/topic/advances-collections/reporting-statistics?seriesKey=&tagCode=&)

<br>

## American Statistical Association {-}
 
-   [*Statistical Inference in the 21st Century: A World Beyond p \< 0.05 - The American Statistical Association*](https://www.tandfonline.com/toc/utas20/73/sup1?nav=tocList)

<br>

## British Medicine Journal {-}

-   [*Statistics - Latest from The BMJ*](https://www.bmj.com/specialties/statistics)

-   [*Statistics notes - Latest from The BMJ*](https://www.bmj.com/specialties/statistics-notes)

-   [*Statistics and research methods - Latest from The BMJ*](https://www.bmj.com/specialties/statistics-and-research-methods)

-   [*Statistics at Square One*](https://www.bmj.com/about-bmj/resources-readers/publications/statistics-square-one)

-   [*Research methods & reporting*](https://www.bmj.com/research/research-methods-and-reporting)

<br>

## Enhancing the QUality And Transparency Of health Research Network {-}

-   *Enhancing the Quality and Transparency of health research* [EQUATOR Network](https://www.equator-network.org).[@Altman2008]

<br>

## Journal of the Amercan Medical Association {-}

-   [*JAMA Guide to Statistics and Methods - JAMA*](https://jamanetwork.com/collections/44042/jama-guide-to-statistics-and-methods)

<br>

## Nature Publishing Group {-}

-   [*Statistics for Biologists - Nature Publising Group*](https://www.nature.com/collections/qghhqm)

<br>

## Royal Statistical Society {-}

-   [*Best Practices for Data Visualisation - Royal Statistical Society*](https://royal-statistical-society.github.io/datavisguide/)

<br>

## Wiley Online Library {-}

-   [*Tutorials in Biostatistics Papers - Wiley Online Library*](https://onlinelibrary.wiley.com/page/journal/10970258/homepage/tutorials.htm)

<br>
