# **Inteligência artificial** {#inteligencia-artificial}

<br>

## Inteligência artificial

<br>

### O que é inteligência artificial (IA)?

-   .[@REF]

<br>

### Como ela se relaciona com estatística, ciência de dados e aprendizado de máquina?

-   .[@REF]

<br>

## Áreas da IA

<br>

### Quais são as principais áreas de aplicação da IA?

-   Percepção: visão computacional, reconhecimento de fala.[@REF]

-   Raciocínio: sistemas especialistas, inferência lógica.[@REF]

-   Aprendizado: machine learning e deep learning.[@REF]

-   Interação: processamento de linguagem natural, agentes conversacionais.[@REF]

<br>

### Quais são exemplos de aplicação prática?

-   Classificação de imagens.[@REF]

-   Análise de sentimentos.[@REF]

-   Geração de texto.[@REF]

<br>

## Técnicas modernas

<br>

### Quais são as técnicas modernas de IA?

-   Redes neurais profundas (CNN, RNN, Transformers).[@REF]

-   Modelos generativos (GANs, VAEs, LLMs).[@REF]

-   Aprendizado por reforço profundo (Deep Reinforcement Learning).[@REF]

<br>

## IA generativa e grandes modelos de linguagem

<br>

### O que são grandes modelos de linguagem (*large langauge models*, LLM)?

-   .[@REF]

<br>

### Como funcionam modelos como GPT, BERT e similares?

-   .[@REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *keras*[@keras](https://cran.r-project.org/web/packages/keras/index.html) funções para criar, treinar e avaliar modelos de redes neurais.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *torch*[@torch](https://cran.r-project.org/web/packages/torch/index.html) permite criar e treinar redes neurais com alto desempenho.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *reticulate*[@reticulate](https://cran.r-project.org/web/packages/reticulate/index.html) integra R e Python em um mesmo ambiente de trabalho, permitindo chamar funções Python a partir de R e facilitar o uso de bibliotecas de IA disponíveis nesse ecossistema.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *text2vec*[@text2vec](https://cran.r-project.org/web/packages/text2vec/index.html) fornece ferramentas para modelagem de texto em R, incluindo pré-processamento, vetorização, embeddings e outros modelos úteis para processamento de linguagem natural.
:::

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
