# **Meta-análise** {#meta-analise}

<br>

## Meta-análise {#meta-analise}

<br>

### O que é meta-análise?

- .[]

<br>

## Interpretação de efeitos em meta-análise {#interpretacao}

<br>

### Como avaliar a variação do tamanho do efeito?

-   O intervalo de predição contém informação sobre a variação do tamanho do efeito.[@Borenstein2022]

-   Se o intervalo de predição não contém a hipótese nula ($H_{0}$), podemos concluir que (a) o tratamento funciona igualmente bem em todas as populações, ou que ele funciona melhor em algumas populações do que em outras.[@Borenstein2022]

-   Se o intervalo de predição contém a hipótese nula ($H_{0}$), podemos concluir que o tratamento pode ser benéfico em algumas populações, mas prejudicial em outras, de modo que a estimativa pontual (geralmente a média) torna-se amplamente irrelevante. Nesse caso, é recomendado investigar em que populações o tratamento seria benéfico e em quais causaria danos.[@Borenstein2022]

<br>

### Como avaliar a heterogeneidade entre os estudos?

-   A heterogeneidade - variação não-aleatória - no efeito do tratamento entre os estudos incluídos em uma meta-análise pode ser avaliada pelo $I^{2}$.[@Rücker2008; @Borenstein2022]

-   $I^{2}$ representa qual proporção da variância observada reflete a variância nos efeitos verdadeiros em vez do erro de amostragem.[@Borenstein2022]

-   $I^{2}$ não depende da quantidade de estudos incluídos na meta-análise. Entretanto, $I^{2}$ aumenta com a quantidade de participantes incluídos nos estudos meta-analisados.[@Rücker2008]

-   A heterogeneidade entre estudos é explicada de modo mais confiável utilizando dados de pacientes individuais, uma vez que a direção verdadeira da modificação de efeito não pode ser observada a partir de dados agregados no estudo.[@degrooth2023]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}

O pacote *metagear*[@metagear] fornece funções para condução e análise de revisões sistemáticas.

:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}

O pacote *metagear*[@metagear] fornece a função [*plot_PRISMA*](https://www.rdocumentation.org/packages/metagear/versions/0.7/topics/plot_PRISMA) para gerar o fluxograma de uma revisão sistemática de acordo com o *Preferred Reporting Items for Systematic Reviews and Meta-Analyses*[@Moher2015].

:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}

O pacote *PRISMA2020*[@PRISMA2020-2; @PRISMA2020] fornece a função [*PRISMA_flowdiagram*](https://www.rdocumentation.org/packages/PRISMA2020/versions/1.1.1/topics/PRISMA_flowdiagram) para elaboração do fluxograma de revisões sistemáticas no formato padrão.

:::

<br>
