# **Modelagem de sobrevida** {#modelagem-sobrevida}

<br>

## Sobrevida

<br>

### O que é sobrevida?

- A sobrevida é um termo utilizado em estatística e análise de dados para descrever o tempo que decorre até a ocorrência de um evento específico, como a morte, a falha de um equipamento ou a recidiva de uma doença. Em estudos clínicos, por exemplo, a sobrevida pode referir-se ao tempo que um paciente vive após o diagnóstico de uma doença ou após o início de um tratamento.[@REF]

<br>

## Análise de sobrevida

<br>

### O que é análise de sobrevida?

- A análise de sobrevida é uma área da estatística que se concentra no estudo desses tempos até o evento, levando em consideração que nem todos os indivíduos podem ter experimentado o evento durante o período de estudo (censura).[@REF]

- Métodos comuns de análise de sobrevida incluem a estimativa da função de sobrevivência, a análise de Kaplan-Meier e modelos de regressão como o modelo de riscos proporcionais de Cox.[@REF]

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
