# **Modelos** {#modelos}

<br>

## Modelos estatísticos

<br>

### O que é modelagem estatística?

-   Modelagem é o processo de usar dados para selecionar um modelo matemático explícito que represente o processo gerador dos dados.[@Greenland1989]

<br>

### Por que a escolha do modelo é complexa?

- Há inúmeras combinações possíveis de variáveis, formas funcionais (lineares, quadráticas, transformações), interações e formas do desfecho, o que torna o espaço de possibilidades muito amplo.[@Greenland1989]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *equatiomatic*[@equatiomatic] fornece a função [*extract_eq*](https://www.rdocumentation.org/packages/equatiomatic/versions/0.3.1/topics/extract_eq) para extrair a equação dos modelos em formato LaTeX para visualização.
:::

<br>

## Suposições dos modelos

<br>

### Quais suposições são feitas para modelagem?

-   .[@REF]

<br>

### Como avaliar as suposições de um modelo?

-   .[@REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *performance*[@performance] fornece a função [*check_model*](https://www.rdocumentation.org/packages/performance/versions/0.10.4/topics/check_model) para analisar a colinearidade entre variáveis, a normalidade da distribuição das variáveis e a heteroscedasticidade.
:::

<br>

## Avaliação de modelos

<br>

### O que é qualidade de ajuste de um modelo?

-   .[@REF]

<br>

### Como avaliar a qualidade de ajuste de um modelo?

- Usando diagnóstico de regressão (ex.: análise de resíduos, gráficos de valores observados vs. preditos) e comparação com análises estratificadas.[@Greenland1989]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *performance*[@performance] fornece a função [*model_performance*](https://www.rdocumentation.org/packages/performance/versions/0.10.4/topics/model_performance) para calcular as métricas de ajuste da regressão adequadas ao modelo pré-especificado.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *performance*[@performance] fornece a função [*compare_performance*](https://www.rdocumentation.org/packages/performance/versions/0.10.4/topics/compare_performance) para comparar o desempenho e a qualidade do ajuste de diversos modelos de regressão pré-especificados.
:::

<br>

## Modelos estocásticos

<br>

### O que são modelos estocásticos?

-   .[@REF]

<br>

### O que são cadeias de Markov?

-   .[@REF]

<br>

### Como construir uma cadeia de Markov?

-   [@REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *markovchain*[@markovchain] fornece a função [*markovchainFit*](https://www.rdocumentation.org/packages/markovchain/versions/0.9.5/topics/createSequenceMatrix) ajusta uma cadeia com base em dados observados.
:::

<br>

## Comparação de modelos

<br>

### Como comparar modelos de aprendizagem de máquina?

-   .[@REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *correctR*[@correctR] fornece funções para comparar o desempenho e a qualidade do ajuste de diversos modelos de aprendizagem de máquina em amostras correlacionadas.
:::

<br>

```{r, echo=FALSE, warning=FALSE, results='asis'}
cat(readLines("citation.html"), sep = "\n")
```

<br>
