# **Pensamento estatístico** {#pensamento-estatistico}

<br>

## Metodologia da pesquisa

<br>

### Qual a relação entre estatística e metodologia da pesquisa científica?

-   .[@munafò2017]

<br>

```{r, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', results = "asis", fig.fullwidth = TRUE, fig.cap = "Mapa mental da relação entre o pensamento estatístico e o pensamento metodológico."}

DiagrammeR::mermaid("

graph TB

A(Projeto <br/>de pesquisa) --- B(Geração e especificação <br/> de hipóteses)
B(Geração e especificação <br/> de hipóteses)-->C(Delineamento <br/> do estudo)
C(Delineamento do estudo)-->D(Realização do estudo <br/> e coleta de dados)
D(Realização do estudo e coleta de dados)-->E(Análise de dados e teste de hipóteses)
E(Análise de dados <br/> e teste de hipóteses)-->F(Interpretação de resultados)
F(Interpretação <br/> de resultados)-->G(Publicação e/ou realização <br/> do próximo experimento)

H(Elaboração das hipóteses <br/> nula e alternativa)-.->B(Geração e especificação <br/> de hipóteses)
I(Seleção das análises <br/> descritiva/inferencial e testes)-.->C(Delineamento <br/> do estudo)
J(Análise inicial <br/> de dados)-.->D(Realização do estudo <br/> e coleta de dados)
K(Análise <br/> inferencial)-.->E(Análise de dados <br/> e teste de hipóteses)
L(Tamanho do efeito <br/> e P-valor)-.->F(Interpretação <br/> de resultados)
M(Redação <br/> dos resultados)-.->G(Publicação e/ou realização <br/> do próximo experimento)

H-->I
I-->J
J-->K
K-->L
L-->M

style H fill:#FFFFFF00;
style I fill:#FFFFFF00;
style J fill:#FFFFFF00;
style K fill:#FFFFFF00;
style L fill:#FFFFFF00;
style M fill:#FFFFFF00;

")
```

<br>

## População e amostra {#populacao-amostra}

<br>

### O que é população?

-   População - ou população-alvo - refere-se ao conjunto completo sobre o qual se pretende obter informações.[@Banerjee2010]

-   População é metodologicamente delimitada pelos critérios de inclusão e exclusão do estudo.[@Banerjee2010]

- Em estudos observacionais, inicialmente as características geográficas e/ou demográficas, por exemplo, definem a população a ser estudada.[@Banerjee2010]

- Em estudos analíticos, a população é inicialmente definida pelos objetivos da pesquisa e posteriormente as observações são realizadas na amostra.[@Banerjee2010]

<br>

### O que é amostra?

- Amostra é uma parte da população do estudo.[@Banerjee2010]

-   Em pesquisa científica, utilizam-se dados de uma amostra de participantes (ou outras unidades de análise) para realizar inferências sobre a população.[@Bland2015]

<br>

## Unidade de análise {#unidade-analise}

<br>

### O que é unidade de análise?

-   A unidade de análise (ou unidade experimental) de pesquisas na área de saúde geralmente é o indivíduo.[@Altman1997]

-   A unidade de análise também pode ser a instituição em estudos multicêntricos (ex.: hospitais, clínicas) ou um estudo publicado em meta-análise (ex.: ensaios clínicos).[@Altman1997]

### Por que identificar a unidade de análise de um estudo?

-   É fundamental identificar corretamente a unidade de análise para evitar inflação do tamanho da amostra (ex.: medidas bilaterais resultando em o dobro de participantes), violações de suposições dos testes de hipótese (ex.: independência entre medidas e/ou unidade de análise) e resultados espúrios em testes de hipótese (ex.: p-valores menores que aqueles observados se a amostra não estivesse inflada).[@Altman1997; @Matthews1990]

### Que medidas podem ser obtidas da unidade de análise de um estudo?

-   Da unidade de análise podem ser coletadas informações em medidas únicas, repetidas, seriadas ou múltiplas.

<br>

## Tamanho da amostra

<br>

### O que é tamanho da amostra?

-   .[@Banerjee2010]

<br>

### Por que determinar o tamanho da amostra é importante?

-   Uma amostra muito pequena para o estudo pode resultar em ajuste exagerado, imprecisão e baixo poder do teste.[@van2022a]

<br>

### Como é determinado o tamanho da amostra de um estudo?

-   Geralmente é recomendado ser cético em relação às regras práticas para o tamanho da amostra, tais como a proporção entre o número de variáveis (ou eventos) e de participantes.[@van2022a]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *pwr*[@pwr] fornece a função [*cohen.ES*](https://www.rdocumentation.org/packages/pwr/versions/1.3-0/topics/cohen.ES) para cálculo do tamanho da amostra baseado em diferentes testes de hipóteses.
:::

<br>

### Quais aspectos éticos estão envolvidos no tamanho da amostra?

-   O tratamento ético dos participantes do estudo, portanto, não exige que se considere se o poder do estudo é inferior à meta convencional de 80% ou 90%.[@Bacchetti2005]

-   Estudos com poder \<80% não são necessariamente antiéticos.[@Bacchetti2005]

-   Grandes estudos podem ser desejáveis por outras razões que não as éticas.[@Bacchetti2005]

<br>

## Amostragem {#amostragem}

<br>

### O que é amostragem?

-   .[REF]

<br>

### Quais métodos de amostragem são usados para obter uma amostra da população?

-   O método de amostragem é geralmente definido pelas condições de viabilidade do estudo, no que diz respeito a acesso aos participantes, ao tempo de execução e aos custos envolvidos, entre outras.[@Banerjee2010]

-   Não-probabilísticas ou intencionais:[@Banerjee2010]

    - Bola de neve.
    
    - Conveniência.
    
    - Participantes encaminhados
    
-   Probabilísticas:[@Banerjee2010]

    - Simples.
    
    - Sistemática.
    
    - Multiestágio.
    
    - Estratificada.
    
    - Agregada.

<br>

### O que é erro de amostragem?

-   .[REF]

<br>

## Reamostragem {#reamostragem}

<br>

### O que é reamostragem?

-   Reamostragem é um procedimento que cria vários conjuntos de dados sorteados a partir de um conjunto de dados real - a amostra da população - sem a necessidade de fazer suposições sobre os dados e suas distribuições.[@Bland2015]

-   O procedimento é repetido várias vezes para usar a variabilidade dos resultados para obter um intervalo de confiança do parâmetro.[@Bland2015]

<br>

### Por que utilizar reamostragem?

-   Quando se dispõe de dados de apenas 1 amostra, as diversas suposições que são feitas podem não ser atingidas.[@Bland2015]

-   Procedimentos de reamostragem produzem um conjunto de observações escolhidas aleatoriamente da amostra, igualmente representativo da população original.[@Bland2015]

-   Procedimentos de reamostragem permitem estimar o erro-padrão e intervalos de confiança sem a necessidade de tais suposições, sendo, portanto, um conjunto de procedimentos não-paramétricos.[@Bland2015]

<br>

### Quais procedimentos de reamostragem podem ser realizados?

-   *Bootstrap*: Cada iteração gera uma amostra *bootstrap* do mesmo tamanho do conjunto de dados original escolhendo aleatoriamente observações reais, uma de cada vez. Cada observação tem chances iguais de ser escolhida a cada vez, portanto, algumas observações serão escolhidas mais de uma vez e outras nem serão escolhidas.[@Bland2015]

<br>
