# **Pensamento metodológico** {#pensamento-metodologico}

<br>

## Estatística e Epidemiologia

<br>

### Qual a relação entre estatística e metodologia da pesquisa científica?

-   .[@munafò2017]

<br>

```{r, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', results = "asis", fig.fullwidth = TRUE, fig.cap = "Mapa mental da relação entre o pensamento estatístico e o pensamento metodológico."}

DiagrammeR::mermaid("

graph TB

A(Projeto <br/>de pesquisa) --- B(Geração e especificação <br/> de hipóteses)
B(Geração e especificação <br/> de hipóteses)-->C(Delineamento <br/> do estudo)
C(Delineamento do estudo)-->D(Realização do estudo <br/> e coleta de dados)
D(Realização do estudo e coleta de dados)-->E(Análise de dados e teste de hipóteses)
E(Análise de dados <br/> e teste de hipóteses)-->F(Interpretação de resultados)
F(Interpretação <br/> de resultados)-->G(Publicação e/ou realização <br/> do próximo experimento)

H(Elaboração das hipóteses <br/> nula e alternativa)-.->B(Geração e especificação <br/> de hipóteses)
I(Seleção das análises <br/> descritiva/inferencial e testes)-.->C(Delineamento <br/> do estudo)
J(Análise inicial <br/> de dados)-.->D(Realização do estudo <br/> e coleta de dados)
K(Análise <br/> inferencial)-.->E(Análise de dados <br/> e teste de hipóteses)
L(Tamanho do efeito <br/> e P-valor)-.->F(Interpretação <br/> de resultados)
M(Redação <br/> dos resultados)-.->G(Publicação e/ou realização <br/> do próximo experimento)

H-->I
I-->J
J-->K
K-->L
L-->M

style H fill:#FFFFFF00;
style I fill:#FFFFFF00;
style J fill:#FFFFFF00;
style K fill:#FFFFFF00;
style L fill:#FFFFFF00;
style M fill:#FFFFFF00;

")
```

<br>

## Delineamento de estudos {#delineamento-estudos}

<br>

### Como podem ser classificados os estudos científicos?

-   Estudos científicos podem ser classificados em *básicos*, *observacionais*, *experimentais*, *acurácia diagnóstica*, *propriedades psicométricas*, *avaliação econômica* e *revisões de literatura*:[@Grant2009; @Süt2014; @Souza2017; @reeves2017; @echevarría-guanilo2019; @Chassé2019; @Chidambaram2019; @Erdemir2020; @Yang2021; @chipman2022]

-   *Estudos básicos*[@Süt2014; @Chidambaram2019]

    -   Genética

    -   Celular

    -   Experimentos com animais

    -   Desenvolvimento de métodos

-   *Estudos de simulação computacional*[@Erdemir2020; @chipman2022]

-   *Estudos observacionais*[@Süt2014; @Chidambaram2019]

    -   Descritivo

        -   Estudo de caso

        -   Série de casos

        -   Transversal

    -   Analítico

        -   Transversal

        -   Caso-Controle

            -   Caso-Controle aninhado

            -   Caso-Coorte

    -   Coorte prospectiva ou retrospectiva

-   *Estudos de desempenho diagnóstico*[@Chassé2019; @Yang2021]

    -   Transversal

    -   Caso-Controle

    -   Comparativo

    -   Totalmente pareado

    -   Parcialmente pareado com subgrupo aleatório

    -   Parcialmente pareado com subgrupo não aleatório

    -   Não pareado aleatório

    -   Não pareado não aleatório

-   *Estudos de propriedades psicométricas*[@Souza2017; @echevarría-guanilo2019]

    -   Validade

    -   Confiabilidade

    -   Concordância

-   *Estudos quase-experimentais*[@reeves2017]

    -   Quase-aleatorizado controlado

    -   Estimação de variável instrumental

    -   Descontinuidade de regressão

    -   Série temporal interrompida controlada

    -   Série temporal interrompida

    -   Diferença

-   *Estudos experimentais*[@Süt2014; @Chidambaram2019]

    -   Fases I a IV

        -   Aleatorizado controlado

        -   Não-aleatorizado controlado

        -   Autocontrolado

        -   Cruzado

        -   Fatorial

    -   Campo

    -   Comunitário

-   *Estudos de avaliação econômica*[@Süt2014]

    -   Análise de custo

    -   Análise de minimização de custo

    -   Análise de custo-utilidade

    -   Análise de custo-efetividade

    -   Análise de custo-benefício

-   *Estudos de revisão*[@Grant2009]

    -   Estado-da-arte

    -   Narrativa

    -   Crítica

    -   Mapeamento

    -   Escopo

    -   Busca e revisão sistemática

    -   Sistematizada

    -   Sistemática

        -   Meta-análise

        -   Bibliométrica.[@donthu2021; @lim2023]

    -   Sistemática qualitativa

    -   Mista

    -   Visão geral

    -   Rápida

    -   Guarda-chuva

<br>

## Validade do estudo {#validade-estudo}

<br>

### O que é validade interna?

-   .[@findley2021]

<br>


### Que fatores afetam a validade interna?

- .[REF]

<br>

### O que é validade externa?

-   .[@findley2021]

<br>

### Que fatores afetam a validade externa?

- A amostragem não probabilística pode dificultar a generalização dos achados da amostra para a população, diminuindo assim a validade externa do estudo.[@Banerjee2010]

- Quando as características da amostra obtida por seleção não probabilística forem similares às da população, a validade externa pode ser maior.[@Banerjee2010]

<br>

### Como avaliar a validade de um estudo?

- As características da amostra apresentadas na Tabela 1 são úteis para interpretação da validade interna e externa dos achados do estudo.[@Westreich2013]

<br>

## Reprodutibilidade

<br>

### O que é reprodutibilidade?

-   Reprodutibilidade é a habilidade de se obter resultados iguais ou similares quando uma análise ou teste estatístico é repetido.[@resnik2016; @hofner2015; @mair2016]

<br>

### O que é replicabilidade?

-   Replicabilidade é a habilidade de se obter conclusões iguais ou similares quando um experimento é repetido.[@hofner2015; @mair2016]

<br>

### Por que reprodutibilidade é importante?

-   Analisar a reprodutibilidade pode fornecer evidências a respeito da objetividade e confiabilidade dos achados, em detrimento de terem sido obtidos devido a vieses ou ao acaso.[@resnik2016]

-   A reprodutibilidade não é apenas uma questão metodológica, mas também ética, uma vez que pode envolver mal práticas científicas como fabricação e/ou falsificação de dados.[@resnik2016]

-   Reprodutibilidade pode ser considerada um padrão mínimo em pesquisa científica.[@hofner2015]]

<br>

### Como contribuir para a reprodutibilidade?

-   Disponibilize publicamente os bancos de dados, respeitando as considerações éticas vigentes (ex.: autorização dos participantes e do Comitê de Ética em Pesquisa) e internacionalmente.[@mair2016]

<br>
