```{=openxml}
<w:p>
  <w:r>
    <w:br w:type="page"/>
  </w:r>
</w:p>
```
# **Pesquisa por levantamento** {#pesquisa-levantamento}

<br>

## Pesquisa por levantamento

<br>

### O que é pesquisa por levantamento?

- .[@REF]

<br>

### Quando utilizar um levantamento?

- .[@REF]

<br>

## Levantamentos transversais

- .[@REF]

<br>

## Levantamentos longitudinais

- .[@REF]

<br>

## Painéis

- .[@REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *surveysd*[@surveysd] fornece a função `cpp_mean` para calcular médias aritméticas ou geométricas de dados.
:::

<br>

## Como melhorar a taxa de resposta?

- .[@REF]

<br>

## Diretrizes para redação

<br>

### Quais são as diretrizes para redação de estudos de levantamento?

- Visite a rede *Enhancing the QUAlity and Transparency Of health Research* ([EQUATOR Network](https://www.equator-network.org/)) para encontrar diretrizes específicas.

- *A Consensus-BasedChecklist for Reporting of Survey Studies (CROSS)*.[@sharma2021]

- *AAPOR Reporting Guidelines for Survey Studies*.[@pitt2021]

- *SURGE (The SUrvey Reporting GuidelinE)*.[@grimshaw2014]

- *Improving the quality of Web surveys: the Checklist for Reporting Results of Internet E-Surveys (CHERRIES)*.[@eysenbach2004]

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
