# **Pesquisa qualitativa** {#pesquisa-qualitativa}

<br>

## Pesquisa qualitativa

<br>

### O que é pesquisa qualitativa?

-   No contexto de ensaios clínicos randomizados, pesquisa qualitativa é usada para compreender a complexidade das intervenções e dos contextos sociais em que são testadas, contribuindo para gerar evidências de efetividade.[@ocathain2013]

-   O valor potencial da pesquisa qualitativa inclui: otimizar a intervenção e procedimentos dos ensaios clínicos randomizados; facilitar a interpretação dos achados; fortalecer a condução ética; ampliar a validade externa ; e economizar recursos ao direcionar futuros ensaios clínicos randomizados para intervenções mais promissoras.[@ocathain2013]

<br>

## Diretrizes para redação

<br>

### Quais são as diretrizes para redação de estudos de propriedades psicométricas?

-   Visite a rede *Enhancing the QUAlity and Transparency Of health Research* ([EQUATOR Network](https://www.equator-network.org/)) para encontrar diretrizes específicas.

-   *Standards for reporting qualitative research: a synthesis of recommendations*:[@obrien2014] <https://www.equator-network.org/reporting-guidelines/srqr/>

-   *Enhancing transparency in reporting the synthesis of qualitative research: ENTREQ*:[@tong2012] <https://www.equator-network.org/reporting-guidelines/entreq/>

-   *Consolidated criteria for reporting qualitative research (COREQ) : a 32-item checklist for interviews and focus groups*:[@tong2007] <https://www.equator-network.org/reporting-guidelines/coreq/>

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
