# **Propriedades psicométricas** {#propriedades-psicometricas}

<br>

## Propriedades psicométricas

### O que são propriedades psicométricas?

-   .[REF]

<br>

```{r crosstable-psicometria, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', results = "asis"}
library(dplyr)
cross.table.psico <-
  matrix(
    c(
      'Adequado', 'Inadequado',
      'Inadequado', 'Inadequado'
    ),
    nrow = 2,
    ncol = 2,
    byrow = FALSE
  )
rownames(cross.table.psico) <-
  c("Validade alta", "Validade baixa")
colnames(cross.table.psico) <-
  c("Concordância alta", "Concordância baixa")

# exibe a tabela de dados
kableExtra::kable(
  cross.table.psico,
  align = "c",
  format = ifelse(knitr::is_html_output(), "html", "latex"),
  booktabs = TRUE,
  linesep = "",
  escape = FALSE,
  caption = "Tabela de confusão sobre propriedades psicométricas de instrumentos."
) %>%
  kableExtra::kable_styling(
    latex_options = c("basic"),
    bootstrap_options = c("basic", "hover", "condensed", "responsive"),
    full_width = ifelse(knitr::is_html_output(), T, T),
    position = "center"
  ) %>%
  kableExtra::row_spec(0,
                       bold = TRUE,
                       extra_css = "border-top: 1px solid; border-bottom: 1px solid") %>%
  kableExtra::row_spec(dim(cross.table.psico)[1],
                       extra_css = "border-bottom: 1px solid")
```

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *lavaan*[@lavaan] fornece a função [*cfa*](https://www.rdocumentation.org/packages/lavaan/versions/0.6-16/topics/cfa) para implementar modelos de análise fatorial confirmatória.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *lavaan*[@lavaan] fornece a função [*modificationIndices*](https://www.rdocumentation.org/packages/lavaan/versions/0.6-16/topics/modificationIndices) para calcular os índices de modificação.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *semTools*[@semTools] fornece a função [*reliability*](https://www.rdocumentation.org/packages/semTools/versions/0.5-6/topics/reliability-deprecated) para analisar a confiabilidade de um instrumento.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *psych*[@psych-2] fornece a função [*icc*](https://www.rdocumentation.org/packages/psych/versions/2.3.6/topics/ICC) para calcular a confiabilidade utilizando coeficientes de correlação intraclasse.
:::

<br>

## Análise fatorial exploratória {#analise-fatorial-exploratoria}

<br>

### O que é análise fatorial exploratória?

-   .[REF]

<br>

## Análise fatorial confirmatória {#analise-fatorial-ocnfirmatoria}

<br>

### O que é análise fatorial confirmatória?

-   .[REF]

<br>

## Validade de conteúdo {#validade-conteúdo}

<br>

### O que é validade interna?

-   .[@findley2021]

<br>

### O que é validade externa?

-   .[@findley2021]

<br>

### Que fatores afetam a validade?

-   A amostragem não probabilística pode dificultar a generalização dos achados da amostra para a população, diminuindo assim a validade externa do estudo.[@Banerjee2010]

-   Quando as características da amostra obtida por seleção não probabilística forem similares às da população, a validade externa pode ser maior.[@Banerjee2010]

<br>

### Como avaliar a validade de um estudo?

-   As características da amostra apresentadas na Tabela 1 são úteis para interpretação da validade interna e externa dos achados do estudo.[@Westreich2013]

<br>

## Validade de face {#validade-face}

<br>

### O que é validade de face?

-   .[RF]

<br>

## Validade do construto {#validade-constructo}

<br>

### O que é construto?

-   .[RF]

<br>

## Validade fatorial {#validade-fatorial}

<br>

### O que é validade fatorial?

-   .[RF]

<br>

## Validade convergente {#validade-convergente}

<br>

### O que é validade convergente?

-   .[RF]

<br>

## Validade discriminante {#validade-discriminante}

<br>

### O que é validade discriminante?

-   .[RF]

<br>

## Validade de critério {#validade-criterio}

<br>

### O que é validade de critério?

-   .[RF]

<br>

## Validade concorrente {#validade-concorrente}

<br>

### O que é concorrente?

-   .[RF]

<br>

### O que é validade concorrente?

-   .[RF]

<br>

### O que é validade preditiva?

-   .[RF]

<br>

## Responsividade {#responsividade}

<br>

### O que é responsividade?

- .[REF]

<br>
