```{=openxml}
<w:p>
  <w:r>
    <w:br w:type="page"/>
  </w:r>
</w:p>
```

# **Regressão** {#regressao}

<br>

## Regressão linear

<br>

```{r regressao-linear-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
library(dplyr)

# Reprodutibilidade
set.seed(1234)

n <- 150

dados_linear <-
  tibble::tibble(
    idade = rnorm(n, mean = 55, sd = 12),
    sexo = factor(sample(c("Feminino", "Masculino"), n, replace = TRUE)),
    tratamento = factor(sample(c("Controle", "Intervenção"), n, replace = TRUE))
  ) %>%
  dplyr::mutate(
    desfecho = 40 +
      0.35 * idade +
      ifelse(sexo == "Masculino", 3, 0) +
      ifelse(tratamento == "Intervenção", 5, 0) +
      rnorm(n, mean = 0, sd = 8)
  )
```

```{r regressao-linear-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
modelo_linear <- lm(
  desfecho ~ idade + sexo + tratamento,
  data = dados_linear
)

tbl_linear <-
  gtsummary::tbl_regression(
    modelo_linear,
    intercept = TRUE,
    estimate_fun = ~ gtsummary::style_sigfig(.x, digits = 3),
    pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = 3)
  ) %>%
  gtsummary::bold_labels() %>%
  gtsummary::bold_p(t = 0.05) %>%
  gtsummary::modify_caption("Regressão linear múltipla") %>%
  gtsummary::modify_header(
    label = "**Variável**",
    estimate = "**Coeficiente**"
  ) %>%
  gtsummary::as_gt() %>%
  gt::tab_source_note(
    paste0(
      "R² ajustado: ",
      round(summary(modelo_linear)$adj.r.squared, 3),
      "; RMSE: ",
      round(performance::rmse(modelo_linear), 3)
    )
  )

tbl_linear
```

<br>

## Regressão logística

<br>

```{r regressao-logistica-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
# Reprodutibilidade
set.seed(1234)

n <- 200

dados_logistica <-
  tibble::tibble(
    idade = rnorm(n, mean = 60, sd = 10),
    sexo = factor(sample(c("Feminino", "Masculino"), n, replace = TRUE)),
    tratamento = factor(sample(c("Controle", "Intervenção"), n, replace = TRUE))
  ) %>%
  dplyr::mutate(
    logito = -4 +
      0.04 * idade +
      ifelse(sexo == "Masculino", 0.5, 0) -
      ifelse(tratamento == "Intervenção", 0.8, 0),
    probabilidade = 1 / (1 + exp(-logito)),
    desfecho = rbinom(n, size = 1, prob = probabilidade),
    desfecho = factor(desfecho, levels = c(0, 1), labels = c("Não", "Sim"))
  )

modelo_logistico <- glm(
  desfecho ~ idade + sexo + tratamento,
  data = dados_logistica,
  family = binomial
)

tbl_logistico <-
  gtsummary::tbl_regression(
    modelo_logistico,
    exponentiate = TRUE,
    estimate_fun = ~ gtsummary::style_sigfig(.x, digits = 3),
    pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = 3)
  ) %>%
  gtsummary::bold_labels() %>%
  gtsummary::bold_p(t = 0.05) %>%
  gtsummary::modify_caption("Regressão logística binária") %>%
  gtsummary::modify_header(
    label = "**Variável**",
    estimate = "**OR**"
  ) %>%
  gtsummary::as_gt() %>%
  gt::tab_source_note(
    "OR = razão de chances. Valores acima de 1 indicam aumento da chance do desfecho; valores abaixo de 1 indicam redução."
  )

tbl_logistico
```

<br>

## Regressão de Poisson

<br>

```{r regressao-poisson-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
# Reprodutibilidade
set.seed(1234)

n <- 180

dados_poisson <-
  tibble::tibble(
    idade = rnorm(n, mean = 50, sd = 11),
    exposicao = runif(n, min = 0.5, max = 3),
    grupo = factor(sample(c("A", "B"), n, replace = TRUE))
  ) %>%
  dplyr::mutate(
    log_mu = -1 +
      0.02 * idade +
      ifelse(grupo == "B", 0.45, 0) +
      log(exposicao),
    mu = exp(log_mu),
    eventos = rpois(n, lambda = mu)
  )

modelo_poisson <- glm(
  eventos ~ idade + grupo + offset(log(exposicao)),
  data = dados_poisson,
  family = poisson(link = "log")
)

tbl_poisson <-
  gtsummary::tbl_regression(
    modelo_poisson,
    exponentiate = TRUE,
    estimate_fun = ~ gtsummary::style_sigfig(.x, digits = 3),
    pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = 3)
  ) %>%
  gtsummary::bold_labels() %>%
  gtsummary::bold_p(t = 0.05) %>%
  gtsummary::modify_caption("Regressão de Poisson") %>%
  gtsummary::modify_header(
    label = "**Variável**",
    estimate = "**Razão de taxas**"
  ) %>%
  gtsummary::as_gt() %>%
  gt::tab_source_note(
    "Modelo com offset para tempo de exposição. Estimativas exponenciadas representam razões de taxas."
  )

tbl_poisson
```

<br>

## Regressão ordinal

<br>

```{r regressao-ordinal-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
# Reprodutibilidade
set.seed(1234)

n <- 220

dados_ordinal <-
  tibble::tibble(
    idade = rnorm(n, mean = 58, sd = 10),
    tratamento = factor(sample(c("Controle", "Intervenção"), n, replace = TRUE))
  ) %>%
  dplyr::mutate(
    escore_latente = 0.03 * idade +
      ifelse(tratamento == "Intervenção", 0.7, 0) +
      rnorm(n),
    resposta = dplyr::case_when(
      escore_latente < 1.2 ~ "Baixa",
      escore_latente < 2.2 ~ "Moderada",
      TRUE ~ "Alta"
    ),
    resposta = ordered(resposta, levels = c("Baixa", "Moderada", "Alta"))
  )

modelo_ordinal <- ordinal::clm(
  resposta ~ idade + tratamento,
  data = dados_ordinal
)

tbl_ordinal <-
  gtsummary::tbl_regression(
    modelo_ordinal,
    exponentiate = TRUE,
    estimate_fun = ~ gtsummary::style_sigfig(.x, digits = 3),
    pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = 3)
  ) %>%
  gtsummary::bold_labels() %>%
  gtsummary::bold_p(t = 0.05) %>%
  gtsummary::modify_caption("Regressão logística ordinal") %>%
  gtsummary::modify_header(
    label = "**Variável**",
    estimate = "**OR acumulada**"
  ) %>%
  gtsummary::as_gt()

tbl_ordinal
```

<br>

## Regressão com interação

<br>

```{r regressao-interacao-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
# Reprodutibilidade
set.seed(1234)

n <- 160

dados_interacao <-
  tibble::tibble(
    tempo = factor(sample(c("Antes", "Depois"), n, replace = TRUE), levels = c("Antes", "Depois")),
    grupo = factor(sample(c("Controle", "Intervenção"), n, replace = TRUE)),
    idade = rnorm(n, mean = 55, sd = 10)
  ) %>%
  dplyr::mutate(
    desfecho = 50 +
      0.2 * idade +
      ifelse(tempo == "Depois", 2, 0) +
      ifelse(grupo == "Intervenção", 1, 0) +
      ifelse(tempo == "Depois" & grupo == "Intervenção", 6, 0) +
      rnorm(n, mean = 0, sd = 7)
  )

modelo_interacao <- lm(
  desfecho ~ idade + tempo * grupo,
  data = dados_interacao
)

tbl_interacao <-
  gtsummary::tbl_regression(
    modelo_interacao,
    estimate_fun = ~ gtsummary::style_sigfig(.x, digits = 3),
    pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = 3)
  ) %>%
  gtsummary::bold_labels() %>%
  gtsummary::bold_p(t = 0.05) %>%
  gtsummary::modify_caption("Regressão linear com termo de interação") %>%
    gtsummary::modify_header(
    label = "**Variável**",
    estimate = "**Coeficiente**"
  ) %>%
  gtsummary::as_gt() %>%
  gt::tab_source_note(
    "O termo de interação estima se a diferença entre grupos varia conforme o tempo."
  )

tbl_interacao
```

<br>

## Regressão com efeitos mistos

<br>

```{r regressao-mista-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
# Reprodutibilidade
set.seed(1234)

n_id <- 60
n_tempo <- 3

dados_mistos <-
  tidyr::expand_grid(
    ID = factor(1:n_id),
    tempo = 0:(n_tempo - 1)
  ) %>%
  dplyr::mutate(
    tratamento = factor(sample(c("Controle", "Intervenção"), n_id, replace = TRUE)[as.numeric(ID)]),
    intercepto_individual = rnorm(n_id, mean = 0, sd = 6)[as.numeric(ID)],
    desfecho = 50 +
      2.5 * tempo +
      ifelse(tratamento == "Intervenção", 4, 0) +
      intercepto_individual +
      rnorm(dplyr::n(), mean = 0, sd = 5)
  )

modelo_misto <- lme4::lmer(
  desfecho ~ tempo + tratamento + (1 | ID),
  data = dados_mistos
)

tbl_misto <-
  gtsummary::tbl_regression(
    modelo_misto,
    estimate_fun = ~ gtsummary::style_sigfig(.x, digits = 3),
    pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = 3)
  ) %>%
  gtsummary::bold_labels() %>%
  gtsummary::modify_caption("Modelo de regressão linear com efeitos mistos") %>%
  gtsummary::modify_header(
    label = "**Variável**",
    estimate = "**Coeficiente**"
  ) %>%
  gtsummary::as_gt() %>%
  gt::tab_source_note(
    "Modelo com intercepto aleatório por indivíduo, adequado para medidas repetidas ou dados agrupados."
  )

tbl_misto
```

<br>

## Comparação de modelos de regressão

<br>

```{r comparacao-modelos-regressao-gtsummary, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE}
modelo_1 <- lm(
  desfecho ~ idade,
  data = dados_linear
)

modelo_2 <- lm(
  desfecho ~ idade + sexo,
  data = dados_linear
)

tbl_comparacao <-
  gtsummary::tbl_merge(
    tbls = list(
      gtsummary::tbl_regression(modelo_1),
      gtsummary::tbl_regression(modelo_2)
    ),
    tab_spanner = c("**Modelo 1**", "**Modelo 2**")
  ) %>%
  gtsummary::modify_caption("Comparação de modelos de regressão linear") %>%
  gtsummary::modify_header(
    label = "**Variável**",
  ) %>%
  gtsummary::as_gt() %>%
  gt::tab_source_note(
    paste0(
      "AIC: Modelo 1 = ", round(AIC(modelo_1), 1),
      "; Modelo 2 = ", round(AIC(modelo_2), 1), "."
    )
  )

tbl_comparacao
```

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
