# **Seleção de testes** {#selecao-testes}

<br>

## Multiverso de análises estatísticas {#multiverso-estatistica}

<br>

### Por que escolher o teste é um problema?

-   Analisar a mesma hipótese com o mesmo banco de dados pode resultar em diferenças substanciais nas estimativas estatísticas e nas conclusões.[@Breznau2022]

- As decisões para especificação das análises estatísticas podem ser tão minuciosas que muitas vezes nem sequer são registadas como decisões e, assim, podem impactar na reprodutibilidade do estudo.[@Breznau2022]

<br>

## Escolha de testes para análise inferencial {#escolha-analise-inferencial}

<br>

### Qual a relação entre estatística e metodologia para pesquisa científica?

-   .[@munafò2017]

<br>

```{r, include = TRUE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', results = "asis", fig.fullwidth = TRUE, fig.cap = "Mapa mental da relação entre o pensamento estatístico e o pensamento metodológico."}

DiagrammeR::mermaid("

graph TB

A(Projeto <br/>de pesquisa) --- B(Geração e especificação <br/> de hipóteses)
B(Geração e especificação <br/> de hipóteses)-->C(Delineamento <br/> do estudo)
C(Delineamento do estudo)-->D(Realização do estudo <br/> e coleta de dados)
D(Realização do estudo e coleta de dados)-->E(Análise de dados e teste de hipóteses)
E(Análise de dados <br/> e teste de hipóteses)-->F(Interpretação de resultados)
F(Interpretação <br/> de resultados)-->G(Publicação e/ou realização <br/> do próximo experimento)

H(Elaboração das hipóteses <br/> nula e alternativa)-.->B(Geração e especificação <br/> de hipóteses)
I(Seleção das análises <br/> descritiva/inferencial e testes)-.->C(Delineamento <br/> do estudo)
J(Análise inicial <br/> de dados)-.->D(Realização do estudo <br/> e coleta de dados)
K(Análise <br/> inferencial)-.->E(Análise de dados <br/> e teste de hipóteses)
L(Tamanho do efeito <br/> e P-valor)-.->F(Interpretação <br/> de resultados)
M(Redação <br/> dos resultados)-.->G(Publicação e/ou realização <br/> do próximo experimento)

H-->I
I-->J
J-->K
K-->L
L-->M

style H fill:#FFFFFF00;
style I fill:#FFFFFF00;
style J fill:#FFFFFF00;
style K fill:#FFFFFF00;
style L fill:#FFFFFF00;
style M fill:#FFFFFF00;

")
```

<br>

### Como selecionar os testes para a análise estatística inferencial?

-   .[@dwivedi2019]

-   .[@Dwivedi2022]

-   .[@Kim2017]

-   .[@marusteri2010]

-   .[@mishra2019]

-   .[@ray2021]

-   .[@nayak2011]

-   .[@shankar2014]

<br>
