# **Shiny Apps** {#shiny-apps}

<br>

## Aplicativos por delineamento de estudo

<br>

### Qual Shiny App usar para ensaios experimentais?

- [*RCTapp*](https://sciencer.shinyapps.io/RCTapp/)[@ferreira2025]

<br>

```{r RCTapp, echo = FALSE, warning = FALSE, message = FALSE, appendix = TRUE, fig.align = 'center', layout='Blank', ph=officer::ph_location_fullsize(), results = "asis", fig.fullwidth = TRUE, fig.cap = "RCTapp: Shiny app para análise de ensaios clínicos aleatorizados."}
URL.site <- "https://sciencer.shinyapps.io/RCTapp/"
file.png <- "images/RCTapp.png"

screen_width <- 1920
screen_height <- 1080

# function to vget screenshot
library("chromote")
screenshot <- function(b, img_path,
                       selector = "html",
                       cliprect = c(top = 0, left = 0, width = screen_width, height = screen_height),
                       expand = NULL) {
  
  b$screenshot(
    img_path,
    selector = selector,
    delay = 15,
    cliprect = cliprect,
    expand = expand
  )
  
  magick::image_read(img_path) |>
    magick::image_shadow() |>
    magick::image_write(img_path, quality = 100)
}

# get URL screenshot
a <- ChromoteSession$new(height = screen_height, width = screen_width)
invisible(a$Page$navigate(URL.site))
Sys.sleep(1)
screenshot(a, file.png)

if(!exists(file.png)) {
  # show image
  img <- magick::image_read(file.png)
  # zero margins
  par(mar = c(0, 0, 0, 0), oma = c(0, 0, 0, 0))
  plot(img)
}
```

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
