# **Simulação computacional** {#simulacao-computacional}

<br>

## Características

<br>

### Quais são as características de estudos de simulação computacional?

-   .[@REF]

<br>

## Método de Monte Carlo

<br>

### O que é o método de Monte Carlo?

-   .[@REF]

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *base*[@base] fornece a função [*set.seed*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Random) para especificar uma semente para reprodutibilidade de computações que envolvem números aleatórios.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *simstudy*[@simstudy] fornece as funções [*defData*](https://www.rdocumentation.org/packages/simstudy/versions/0.7.0/topics/defData) e [*genData*](https://www.rdocumentation.org/packages/simstudy/versions/0.7.0/topics/genData) para criar variáveis e simular um banco de dados de acordo com o delineamento pré-especificado, respectivamente.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *faux*[@faux] fornece a função [*sim_design*](https://www.rdocumentation.org/packages/faux/versions/1.2.1/topics/sim_design) para simular um banco de dados de acordo com o delineamento pré-especificado.
:::

<br>

::: {.infobox .Rlogo data-latex="{images/Rlogo}"}
O pacote *InteractionPoweR*[@InteractionPoweR] fornece a função [*generate_interaction*](https://www.rdocumentation.org/packages/InteractionPoweR/versions/0.2.1/topics/generate_interaction) para simular bancos de dads com efeitos de interação.
:::

<br>

## Diretrizes para redação

<br>

### Quais são as diretrizes para redação de estudos de simulação computacional?

-   Visite a rede *Enhancing the QUAlity and Transparency Of health Research* [EQUATOR Network](https://www.equator-network.org/) para encontrar diretrizes específicas para cada tipo de estudo de simulação computacional.

    -   *Reporting Guidelines for Health Care Simulation Research: Extensions to the CONSORT and STROBE Statements*:[@cheng2016] <https://www.equator-network.org/reporting-guidelines/reporting-guidelines-for-health-care-simulation-research-extensions-to-the-consort-and-strobe-statements/>

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
