# **Vieses e paradoxos estatísticos**

<br>

## Vieses estatísticos

<br>

### O que são vieses estatísticos?

-   .[REF]

<br>

## Paradoxos estatísticos

<br>

### O que são paradoxos estatísticos?

-   .[REF]

<br>

### O que é o paradoxo de Abelson?

-   .[@abelson1985]

<br>

### O que é o paradoxo de Berkson?

-   .[@berkson1946]

<br>

### O que é o paradoxo de Ellsberg?

-   .[@ellsberg1961]

<br>

### O que é o paradoxo de Freedman?

-   .[@freedman1983; @freedman1989]

<br>

### O que é o paradoxo de Hand?

-   .[@hand1992]

<br>

### O que é o paradoxo de Lindley?

-   .[@lindley1957]

<br>

### O que é o paradoxo de Lord?

-   .[@lord1967; @lord1969]

<br>

### O que é o paradoxo de Proebsting?

-   .[REF]

<br>

### O que é o paradoxo de Simpson?

-   .[@simpson1951; @blyth1972]

<br>

### O que é o paradoxo de Stein?

-   .[@stein1956]

<br>

### O que é o paradoxo de Okie?

-   .[REF]

<br>

### O que é o paradoxo da acurácia?

-   .[REF]

<br>

### O que é o paradoxo do falso positivo?

-   .[REF]

<br>

### O que é o paradoxo da caixa de Bertrand?

-   .[REF]

<br>

### O que é o paradoxo do elevador?

-   .[@de1996]

<br>

### O que é o paradoxo da amizade?

-   .[@feld1991]

<br>

### O que é o paradoxo do menino ou menina?

-   .[@de1996]

<br>

### O que é o paradoxo do teste surpresa?

-   .[REF]

<br>

### O que é o paradoxo do nó da gravata?

-   .[REF]

<br>

### O que é o paradoxo da Bela Adormecida?

-   .[REF]

<br>
