```{=openxml}
<w:p>
  <w:r>
    <w:br w:type="page"/>
  </w:r>
</w:p>
```

# **Vinculação e pareamento de dados** {#vinculacao-pareamento}

<br>

## Vinculação e pareamento de dados

<br>

### O que é vinculação e pareamento de dados?

-   A vinculação de dados combina informações de múltiplas fontes referentes ao mesmo indivíduo, criando uma base enriquecida para pesquisa.[@harron2022]

<br>

## Abordagens de vinculação

<br>

### Quais são as abordagens de vinculação?

- Vinculação determinística – baseada em regras exatas de concordância entre identificadores (ex.: número do NHS, data de nascimento).[@harron2022]

- Vinculação probabilística – utiliza pesos de concordância e estima a probabilidade de dois registros pertencerem à mesma pessoa.[@harron2022]

<br>

## Erros de vinculação

<br>

### Quais são os erros comuns na vinculação de dados?

- Falso pareamento.[@harron2022]

- Pareamento perdido.[@harron2022]

- Esses erros podem ser interpretados sob a lógica de sensibilidade, especificidade e valor preditivo positivo.[@harron2022]

<br>

## Controle de qualidade

<br>

### Como controlar a qualidade da vinculação de dados?

- Avaliar qualidade dos identificadores.[@harron2022]

- Realizar análises de sensibilidade.[@harron2022]

- Reportar métodos com transparência.[@harron2022]

- Considerar erro de vinculação como problema semelhante a dados ausentes.[@harron2022]

<br>

```{r, echo=FALSE, warning=FALSE, results='asis', eval=knitr::is_html_output()}
cat(readLines("citation.html"), sep = "\n")
```

<br>
