# **Variáveis e fatores** {#variaveis-fatores}

<br>

## Variáveis {#variaveis}

<br>

### O que são variáveis?

-   Variáveis são informações que podem variar entre medidas em diferentes indivíduos ou repetições.[@Altman1999]

- Variáveis definem características de uma amostra extraída da população, tipicamente observados por aplicação de métodos de amostragem (isto é, seleção) da população de interesse.[@vetter2017]

<br>

### Como são classificadas as variáveis?

-   Quanto à informação: Quantitativa ou qualitativa.[@Ali2016; @vetter2017; @Dettori2018; @kaliyadan2019]

-   Quanto ao conteúdo: contínua (intervalo ou razão; discreta ou contínua), categórica ordinal (numérica discreta ou nominal) ou categórica nominal (multinominal ou dicotômica).[@Ali2016; @vetter2017; @Dettori2018; @kaliyadan2019]

-   Quanto à interpretação: dependente (desfecho), independente (preditora, covariável, confundidora, controle), mediadora, moderadora, modificadora ou auxiliar.[@Ali2016; @vetter2017; @Dettori2018; @kaliyadan2019]

<br>

### Por que é importante classificar as variáveis corretamente?

-   Identificar corretamente os tipos de variáveis da pesquisa é uma das etapas da escolha dos métodos estatísticos adequados para as análises e representações no texto, tabelas e gráficos.[@Dettori2018]

<br>

## Transformação de variáveis {#transformacao}

<br>

### O que é transformação de variáveis contínuas?

-   Transformação significa aplicar uma função matemática à variável medida em sua unidade original.[@Bland1996]

-   A transformação visa atender aos pressupostos dos modelos estatísticos quanto à distribuição da variável, em geral a distribuição Gaussiana.[@Bland1996; @vetter2017]

<br>

### Por que transformar variáveis?

-   Muitos procedimentos estatísticos supõem que as variáveis - ou seus termos de erro, mais especificamente - são normalmente distribuídas. A violação dessa suposição pode aumentar suas chances de cometer um erro do tipo I ou II.[@osborne2010]

-   Mesmo quando se está usando análises consideradas "robustas" para violações dessas suposições ou testes não paramétricos (que não assumem explicitamente termos de erro normalmente distribuídos), atender a essas questões pode melhorar os resultados das análises (por exemplo, Zimmerman, 1995).[@osborne2010]

<br>

### Quais transformações podem ser aplicadas?

-   Distribuições com assimetria à direita: raiz quadrada, logaritmo natural, logaritmo base 10, transformação inversa.[@osborne2010]

-   Distribuições com assimetria à esquerda: reflexão e raiz quadrada, reflexão e logaritmo natural, reflexão e logaritmo base 10, reflexão e transformação inversa.[@osborne2010]

-   Transformação arco-seno.[@osborne2010]

-   Transformação de Box-Cox.[@box1964]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *MASS*[@MASS] fornece a função *box.cox* para executar a transformação de Box-Cox.[@box1964] [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/MASS/index.html)
:::

<br>

## Dicotomização de variáveis {#dicotomizacao}

<br>

### É recomendado categorizar ou dicotomizar variáveis contínuas?

-   Categorizar variáveis não é necessário para conduzir análises estatísticas. Ao invés de categorizar (ou dicotomizar), priorize as variáveis contínuas.[@Altman2006; @Royston2006; @Collins2016]

-   Em geral, não existe uma justificativa racional (plausibilidade biológica) para assumir que as categorias artificiais subjacentes existam.[@Altman2006; @Royston2006; @Collins2016]

-   Dicotomização causa perda de informação e consequentemente perda de poder estatístico para detectar efeitos.[@Altman2006]

-   Dicotomização também classifica indivíduos com valores próximos na variável contínua como indivíduos em pontos opostos e extremos, artificialmente sugerindo que são muito diferentes.[@Altman2006]

-   Dicotomização pode diminuir a variabilidade das variáveis.[@Altman2006]

-   Dicotomização pode ocultar não-linearidades presentes na variável contínua.[@Altman2006]

-   A mediana, embora amplamente utilizada, não é um bom parâmetro para dicotomizar variáveis.[@Altman2006]

-   Caso exista um ponto de corte ou limiar verdadeiro que discrimina dois ou mais grupos, identificá-lo ainda pode ser um desafio.[@Prince2017]

<br>

### Quais métodos podem ser usados para dicotomizar variáveis contínuas?

-   Em termos de tabelas de contingência 2x2, os seguintes métodos permitem[@Prince2017] a identificação do limiar verdadeiro: Youden,[@YOUDEN1950] Gini Index,[@strobl2007] estatística qui-quadrado,[@pearson1900] risco relativo[@Greiner2000] e kappa[@fleiss1971].

<br>

## Fatores {#fatores}

<br>

### O que são fatores?

-   [REF].

<br>
