# **Distribuições e parâmetros** {#distribuicoes-parametros}

<br>

## Distribuições {#distribuicoes}

<br>

### O que são distribuições?

- Uma distribuição estatística é uma função que descreve os valores possíveis ou o intervalo de valores de uma variável (eixo horizontal) e a frequência com que cada valor é observado (eixo vertical).[@vetter2017]

<br>

### Quais características definem uma distribuição?

- Uma distribuição pode ser definida por modelos matemáticos e caracterizada por sua tendência central, dispersão, simetria, curtose.

- Em uma distribuição normal, o intervalo de 1 desvio-padrão (±1DP) inclui cerca de 68% dos dados; de 2 desvios-padrão (±2DP) cerca de 95% dos dados; e no intervalo de 3 desvios-padrão (±3DP) cerca de 99% dos dados.[@Ali2016]

<br>

### O que é a distribuição normal?

- A distribuição normal (ou Gaussiana) é uma distribuição com desvios simétricos positivos e negativos em torno de um valor central.[@Ali2016]

- Em uma distribuição normal, o intervalo de 1 desvio-padrão (±1DP) inclui cerca de 68% dos dados; de 2 desvios-padrão (±2DP) cerca de 95% dos dados; e no intervalo de 3 desvios-padrão (±3DP) cerca de 99% dos dados.[@Ali2016]

<br>

### O que são distribuições não-normais?

- .[REF]

<br>

### Que métodos podem ser utilizados para identificar a normalidade da distribuição?

- Histogramas.[@vetter2017]

- Gráficos Q-Q.[@vetter2017]

- testes de hipótese de Kolmogorov-Smirnov, Shapiro-Wilk, Anderson-Darling.[@vetter2017]

<br>

## Parâmetros {#parametros}

<br>

### O que são parâmetros?

-   Parâmetros são informações que definem um modelo teórico, como propriedades de uma coleção de indivíduos.[@Altman1999]

- Parâmetros definem características de uma população inteira, tipicamente não observados por ser inviável ter acesso a todos os indivíduos que constituem tal população.[@vetter2017]

<br>

### Quais são os parâmetros mais comuns?

-   Parâmetros de tendência central: média, mediana, moda.[@kanji2006; @Ali2016]

-   Parâmetros de dispersão: variância, desvio-padrão, amplitude, intervalo interquartil, intervalo de confiança.[@kanji2006; @Ali2016]

-   Parâmetros de proporção: frequência absoluta, frequência relativa, percentil, quantil.[@Altman1994; @kanji2006; @Ali2016]

-   Parâmetros de distribuição: assimetria, curtose.[@kanji2006]

-   Extremos: mínimo, máximo.[@Ali2016]

<br>
