# **Distribuições e parâmetros** {#distribuicoes-parametros}

<br>

## Distribuições {#distribuicoes}

<br>

### O que são distribuições?

- Uma distribuição estatística é uma função que descreve os valores possíveis ou o intervalo de valores de uma variável (eixo horizontal) e a frequência com que cada valor é observado (eixo vertical).[@vetter2017]

<br>

### Quais características definem uma distribuição?

- Uma distribuição pode ser definida por modelos matemáticos e caracterizada por sua tendência central, dispersão, simetria, curtose.

- Em uma distribuição normal, o intervalo de 1 desvio-padrão (±1DP) inclui cerca de 68% dos dados; de 2 desvios-padrão (±2DP) cerca de 95% dos dados; e no intervalo de 3 desvios-padrão (±3DP) cerca de 99% dos dados.[@Ali2016]

<br>

### O que é a distribuição normal?

- A distribuição normal (ou gaussiana) é uma distribuição com desvios simétricos positivos e negativos em torno de um valor central.[@Ali2016]

- Em uma distribuição normal, o intervalo de 1 desvio-padrão (±1DP) inclui cerca de 68% dos dados; de 2 desvios-padrão (±2DP) cerca de 95% dos dados; e no intervalo de 3 desvios-padrão (±3DP) cerca de 99% dos dados.[@Ali2016]

<br>

### O que são distribuições não-normais?

- .[REF]

<br>

### Que métodos podem ser utilizados para identificar a normalidade da distribuição?

- Histogramas.[@vetter2017]

- Gráficos Q-Q.[@vetter2017]

- Testes de hipótese nula:[@vetter2017]

    - Kolmogorov-Smirnov
    
    - Shapiro-Wilk
    
    - Anderson-Darling

<br>

## Parâmetros {#parametros}

<br>

### O que são parâmetros?

-   Parâmetros são informações que definem um modelo teórico, como propriedades de uma coleção de indivíduos.[@Altman1999]

- Parâmetros definem características de uma população inteira, tipicamente não observados por ser inviável ter acesso a todos os indivíduos que constituem tal população.[@vetter2017]

<br>

### Que parâmetros podem ser estimados?

-   Parâmetros de tendência central:[@kanji2006; @Ali2016]

    -   *Média*
    
    -   *Mediana*
    
    -   *Moda*

-   Parâmetros de dispersão:[@kanji2006; @Ali2016]

    -   *Variância*
    
    -   *Desvio-padrão*: Estima a variabilidade entre as observações e a média amostra, e estima a variabilidade na população.[@Curran-Everett2008]
    
    -   *Erro-padrão*: Estima a variabilidade teórica entre médias amostrais.[@Curran-Everett2008]
    
    -   *Amplitude*
    
    -   *Intervalo interquartil*
    
    -   *Intervalo de confiança*
    

-   Parâmetros de proporção:[@Altman1994; @kanji2006; @Ali2016]

    -   *Frequência absoluta*
    
    -   *Frequência relativa*
    
    -   *Percentil*
    
    -   *Quantil*: é o ponto de corte que define a divisão da amostra em grupos de tamanhos iguais. Portanto, não se referem aos grupos em si, mas aos valores que os dividem.[@Altman1994]

-   Parâmetros de distribuição:[@kanji2006]

    -   *Assimetria*
    
    -   *Curtose*
    

-   Parâmetros de extremos:[@Ali2016]

    -   *Mínimo*
    
    -   *Máximo*
    

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *stats*[@base] fornece a função *quantile* para executar análise de percentis. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html)
:::

<br>
