# **Análise de regressão** {#analise-regresaao}

<br>

## Multivariável vs. Multivariada {#multivariavel-multivariada}

<br>

### O que são as análises de regressão multivariável e multivariada?

-   a análise multivariável consiste em 1 variável dependente e múltiplas variáveis dependentes.[@Hidalgo2013]

-   A análise multivariada consiste em múltiplas variáveis dependentes.[@Hidalgo2013]

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *modelsummary*[@modelsummary] fornece as funç˜es *modelsummary* e *modelplot* para gerar tabelas e gráficos de coeficientes de regressão. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cloud.r-project.org/web/packages/modelsummary/index.html)
:::

<br>

## Seleção de variáveis {#selecao}

<br>

### Correlação bivariada pode ser usada para seleção de variáveis?

-   Seleção bivariada de variáveis - isto é, aplicação de testes de correlação em pares de variáveis candidatas e variável de desfecho afim de selecionar quais serão incluídas no modelo multivariável - é um dos erros mais comuns na literatura.[@Dales1978; @Sun1996]

-   A seleção bivariada de variáveis torna o modelo mais suscetível a otimismo no ajuste se as variáveis de confundimento não são adequadamente controladas.[@Dales1978; @Sun1996]

<br>

### O que pode ser feito para reduzir o número de variáveis candidatas a um modelo multivariável?

-   Verifique a existência de multicolinearidade entre as variáveis candidatas.[@Sun1996]

-   Em caso de uma proporção baixa entre o número de participantes e de variáveis, use o conhecimento prévio da literatura para selecionar um pequeno conjunto de variáveis candidatas.[@Sun1996]

-   Colapse categorias com contagem nula (células com valor igual a 0) de variáveis candidatas.[@Sun1996]

-   Use simulações de dados para identificar qual(is) variável(is) está(ão) causando problemas de convergência do ajuste do modelo.[@Sun1996]

<br>
