# **Análise descritiva** {#analise-descritiva}

<br>

## Análise descritiva {#descritiva}

<br>

### O que é análise descritiva?

-   A análise descritiva utiliza métodos para calcular, descrever e resumir os dados coletados da(s) amostra(s) de modo que sejam interpretadas adequadamente.[@vetter2017]

-   As análises descritivas geralmente compreendem a apresentação quantitativa (numérica) em tabelas e/ou gráficos.[@vetter2017]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *dataExplorer*[@DataExplorer] fornece a função *create_report* para executar análise explotarória. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/DataExplorer/index.html)
:::

<br>

### Que parâmetros podem ser estimados para análise descritiva?

-   Parâmetros de tendência central:[@kanji2006; @Ali2016]

    -   *Média*
    
    -   *Mediana*
    
    -   *Moda*

-   Parâmetros de dispersão:[@kanji2006; @Ali2016]

    -   *Variância*
    
    -   *Desvio-padrão*: Estima a variabilidade entre as observações e a média amostra, e estima a variabilidade na população.[@Curran-Everett2008]
    
    -   *Erro-padrão*: Estima a variabilidade teórica entre médias amostrais.[@Curran-Everett2008]
    
    -   *Amplitude*
    
    -   *Intervalo interquartil*
    
    -   *Intervalo de confiança*
    

-   Parâmetros de proporção:[@Altman1994; @kanji2006; @Ali2016]

    -   *Frequência absoluta*
    
    -   *Frequência relativa*
    
    -   *Percentil*
    
    -   *Quantil*: é o ponto de corte que define a divisão da amostra em grupos de tamanhos iguais. Portanto, não se referem aos grupos em si, mas aos valores que os dividem.[@Altman1994]

-   Parâmetros de distribuição:[@kanji2006]

    -   *Assimetria*
    
    -   *Curtose*
    

-   Parâmetros de extremos:[@Ali2016]

    -   *Mínimo*
    
    -   *Máximo*
    

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *stats*[@base] fornece a função *quantile* para executar análise de percentis. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html)
:::

<br>
