# **Análise exploratória** {#analise-exploratoria}

<br>

## Análise descritiva {#descritiva}

<br>

### O que é análise descritiva?

- A análise descritiva utiliza métodos para calcular, descrever e resumir os dados coletados da(s) amostra(s) de modo que sejam interpretadas adequatamente.[@vetter2017]

- As análises descritivas geralmente compreendem a apresentação quantitativa (numérica) em tabelas e/ou gráficos.[@vetter2017]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *dataExplorer*[@DataExplorer] fornece a função *create_report* para executar análise explotarória. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/DataExplorer/index.html)
:::

<br>

### Que parâmetros populacionais podem ser estimados?

- Proporções.[REF]

- Tendência central.[REF]

- Dispersão.[REF]

- Extremos.[REF]

- Proporções.[REF]

- Intervalos de confiança.[REF]

<br>

### O que são quantis?

-   Quantis são pontos de corte que definem a divisão da amostra em grupos de tamanhos iguais. Portanto, nào se referem aos grupos em si, mas aos valores que os dividem.[@Altman1994]

-   Tercis dividem a amostra em 3 grupos tal que 33,3% das observações ficam em cada grupo.[@Altman1994]

-   Quartis dividem a amostra em 4 grupos tal que 25% das observações ficam em cada grupo.[@Altman1994]

-   Quintis dividem a amostra em 5 grupos tal que 20% das observações ficam em cada grupo.[@Altman1994]

-   Decis dividem a amostra em 10 grupos tal que 10% das observações ficam em cada grupo.[@Altman1994]

-   Centis dividem a amostra em 100 grupos tal que 1% das observações ficam em cada grupo.[@Altman1994]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *stats*[@base] fornece a função *quantile* para executar análise de percentis. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html)
:::

<br>
