# **Delineamento de estudos** {#delineamento-estudos}

<br>

## Classificação {#classificacao}

<br>

### Como podem ser classificados os estudos científicos?

-   Estudos científicos podem ser classificados em *básicos*, *observacionais*, *experimentais*, *acurácia diagnóstica*, *propriedades psicométricas*, *avaliação econômica* e *revisões de literatura*:[@Grant2009; @Süt2014; @Souza2017; @reeves2017; @echevarría-guanilo2019; @Chassé2019; @Chidambaram2019; @Erdemir2020; @Yang2021; @chipman2022]

│─ Estudos básicos[@Süt2014; @Chidambaram2019] <br> │ └─ Experimentos com animais <br> │ └─ Desenvolvimento de métodos <br> │ └─ Genéticos <br> │ └─ Celulares <br>

│─ Estudos de simulação computacional[@Erdemir2020; @chipman2022] <br>

│─ Estudos observacionais[@Süt2014; @Chidambaram2019] <br> │ └─ Descritivos <br> │ └─── Estudo de caso <br> │ └─── Série de casos <br> │ └─── Transversal <br> │ └─ Analíticos <br> │ └─── Transversal <br> │ └─── Caso-Controle <br> │ └───── Caso-Controle aninhado <br> │ └───── Caso-Coorte <br> │ └─── Coorte (prospectiva ou retrospectiva) <br>

│─ Estudos de acurácia diagnóstica[@Chassé2019; @Yang2021] <br> │ └─ Transversal <br> │ └─ Caso-Controle <br> │ └─ Comparativos <br> │ └─ Totalmente pareado <br> │ └─ Parcialmente pareado com subgrupo aleatório <br> │ └─ Parcialmente pareado com subgrupo não aleatório <br> │ └─ Não pareado aleatório <br> │ └─ Não pareado não aleatório <br>

│─ Estudos de propriedades psicométricas[@Souza2017; @echevarría-guanilo2019] <br> │ └─ Validade <br> │ └─ Confiabilidade <br> │ └─ Concordância <br>

│─ Estudos quase-experimentais[@reeves2017] <br> │ └── Quase-aleatorizados controlados <br> │ └── Estimação de variávbel instrumental <br> │ └── Discontinnuidade de regressão <br> │ └── Série temporal interrompida controlada <br> │ └── Série temporal interrompida <br> │ └── Diferença <br>

│─ Estudos experimentais[@Süt2014; @Chidambaram2019] <br> │ └─ Fases I a IV <br> │ └── Aleatorizados controlados <br> │ └── Não-aleatorizados controlados <br> │ └── Autocontrolados <br> │ └── Cruzados <br> │ └── Fatorial <br> │ └─ Campo <br> │ └─ Comunitário <br>

│─ Avaliação econômica[@Süt2014] <br> │ └─ Análise de custo <br> │ └─ Análise de minimização de custo <br> │ └─ Análise de custo-utilidade <br> │ └─ Análise de custo-efetividade <br> │ └─ Análise de custo-benefício <br>

│─ Revisão de literatura[@Grant2009] <br> │ └─ Crítica <br> │ └─ Narrativa <br> │ └─ Mapeamento <br> │ └─ Sistemática <br> │ └─ Meta-análise <br> │ └─ Mista <br> │ └─ Visão geral <br> │ └─ Sistemática qualitativa <br> │ └─ Rápida <br> │ └─ Escopo <br> │ └─ Estado-da-arte <br> │ └─ Busca e revisão sistemática <br> │ └─ Sistematizada <br> │ └─ Guarda-chuva <br>

<br>
