# **Tabelas, Gráficos e Fluxogramas** {#tabelas-graficos-fluxogramas}

<br>

## Tabelas {#tabelas}

<br>

### Por que usar tabelas?

-   Tabelas complementam o texto (e vice-versa), e podem apresentar os dados de modo mais acessível e informativo.[@Inskip2017]

<br>

### Como construir a Tabela 1?

-   A Tabela 1 geralmente é utilizada para descrever as características da amostra estudada, possibilitando a análise de ameaças à validade interna e/ou externa ao estudo.[@Hayes-Larson2019]

-   Inclua na tabela: título ou legenda, uma síntese descritiva (geralmente por meio de parâmetros descritivos), intervalos de confiança e/ou p-valores conforme necessário para adequada interpretação.[@Inskip2017; @Kwak2021]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *table1*[@table1] fornece funções para construção da 'Tabela 1' [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/table1/index.html)
:::

<br>

### Como construir a Tabela 2?

-   A Tabela 2 pode ser utilizada para apresentar estimativas de múltiplos efeitos ajustados de um mesmo modelo estatístico.[@Westreich2013]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *table1*[@table1] fornece funções para construção da 'Tabela 2' [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/table1/index.html)
:::

<br>

### Como exportar a tabela para o manuscrito?

- .[REF]

<br>

## Gráficos {#graficos}

<br>

### O que são gráficos?

-   Gráficos são utilizados para apresentar dados (geralmente em grande quantidade) de modo mais intuitivo e fácil de compreender.[@Park2022]

<br>

### Que elementos incluir em gráficos?

-   Título, eixos horizontal e vertical com respectivas unidades, escalas em intervalos representativos das variáveis, legenda com símbolos, síntese descritiva dos valores e respectiva margem de erro, conforme necessário para adequada interpretação.[@Park2022]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` Os pacotes *ggplot2*[@ggplot2], *plotly*[@plotly] e *corrplot*[@corrplot] fornecem funções para construção de gráficos [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/ggplot2/index.html) [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/plotly/index.html) [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/corrplot/index.html)
:::

<br>

### Para que servem as barras de erro em gráficos?

- Barras de erro ajudam ao autor a apresentar as informações que descrevem os dados (por exemplo, em uma análise descritiva) ou sobre as inferências ou conclusões tomadas a partir de dados.[@Cumming2007]

- Barras de erro mais longas representam mais imprecisão (maiores erros), enquanto barras mais curtas representam mais precisão na estimativa.[@Cumming2007]

- Barras de erro descritivas geralmente apresentam a amplitude (mínimo-máximo) ou desvio-padrão.[@Cumming2007]

- Barras de erro inferenciais geralmente apresentam o erro-padrão ou intervalo de confiança (por exemplo, de 95%).[@Cumming2007]

- O cumprimento das barras de erro sugerem graficamente a imprecisão dos dados do estudo, uma vez que o valor verdadeiro da população pode estar em qualquer nível do intervalo da barra.[@Cumming2007]

<br>

### Quais são as boas práticas na elaboração de gráficos?

- O tamanho da amostra total e subgrupos, se houver, deve estar descrito na figura ou na sua legenda.[@Cumming2007]

- Para análise inferencial de figuras, as barras de erro representadas por erro-padrão ou intervalo de confiança são preferíveis à amplitude ou desvio-padrão.[@Cumming2007]

-   Evite gráficos de barra e mostre a distribuição dos dados sempre que possível.[@Weissgerber2019]

-   Exiba os pontos de dados em boxplots.[@Weissgerber2019]

-   Use *jitter* simétrico em gráficos de pontos para permitir a visualização de todos os dados.[@Weissgerber2019]

-   Prefira palhetas de cor adaptadas para daltônicos.[@Weissgerber2019]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *ggsci*[@ggsci] fornece palhetas de cores inspiradas em publicações científicas para uso em gráficos [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/ggsci/index.html)
:::

<br>


### Como exportar o gráfico para o manuscrito?

- .[REF]

<br>

## Fluxogramas {#fluxogramas}

<br>

### O que são fluxogramas?

-   Fluxogramas são figuras que apresentam as etapas de um estudos.

<br>

### Que fluxogramas podem ser incluídos?

-   Inclua fluxogramas com o delineamento aplicado no estudo.[@Weissgerber2019]

-   A [EQUATOR Network](https://www.equator-network.org) disponibiliza modelos de fluxogramas para os mais diversos delineamentos de estudo.[@Altman2008]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *PRISMA2020*[@PRISMA2020-2; @PRISMA2020] fornece funções para elaboração do fluxograma de revisões sistemáticas no formato padrão [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/PRISMA2020/index.html)
:::

<br>
