# **Análise inferencial** {#analise-inferencial}

<br>

## Análise inferencial {#inferencial}

<br>

### O que é análise inferencial?

- Na análise inferencial são utilizados dados da(s) amostra(s) para fazer uma inferência válida (isto é, estimativa) sobre os parâmetros populacionais desconhecidos.[@vetter2017]

<br>

## Testes paramétricos e não-paramétricos {#testes-parametricos-não-parametricos}

<br>

### O que é um teste paramétrico?

- Testes paramétricos possuem suposições sobre as características e/ou parâmetros da distribuição dos dados na população.[@vetter2017]

- Testes paramétricos assumem que os dados foram amostrados de uma distribuição normal.[@vetter2017]

<br>

### O que é um teste não paramétrico?

- Testes não-paramétricos fazem poucas suposições, ou menos rigorosas, sobre as características e/ou parâmetros da distribuição dos dados na população.[@vetter2017]

<br>

### Por que os testes paramétricos são preferidos?

- Em geral, testes paramétricos são mais robustos (isto é, possuem menores erros tipo I e II) que seus testes não-paramétricos correspondentes.[@vetter2017]

<br>
