---
bibliography: references.bib
---

# **Análise inferencial** {#analise-inferencial}

<br>

## Ideias e hipóteses científicas {#ideias-hipoteses}

<br>

### O que é hipótese científica?

-   Hipótese científica é uma ideia que pode ser testada.[@Curran-Everett2009]

<br>

### Quais são as principais fontes de ideias para gerar hipóteses científicas?

-   Revisão das práticas atuais.[@Vandenbroucke2018]

-   Desafio a ideias aceitas.[@Vandenbroucke2018]

-   Conflito entre ideias divergentes.[@Vandenbroucke2018]

-   Variações regionais, temporais e populacionais.[@Vandenbroucke2018]

-   Experiências dos próprios pesquisadores.[@Vandenbroucke2018]

-   Imaginação sem fronteiras ou limites convencionais.[@Vandenbroucke2018]

<br>

## Testes de hipóteses {#erros-inferencia}

<br>

### Quais são os tipos de teste de hipóteses?

-   Teste (clássico) de significância da hipótese nula.[@lakens2018]

-   Teste de mínimos efeitos.[@lakens2018]

-   Teste de equivalência.[@lakens2018]

-   Teste de inferioridade.[@lakens2018]

-   Teste de não-inferioridade.[REF]

-   Teste de superioridade.[REF]

<br>

## Análise inferencial {#inferencial}

<br>

### O que é análise inferencial?

-   Na análise inferencial são utilizados dados da(s) amostra(s) para fazer uma inferência válida (isto é, estimativa) sobre os parâmetros populacionais desconhecidos.[@vetter2017]

-   No paradigma de Jerzy Neyman e Egon Pearson, um teste de hipótese científica envolve a tomada de decisão sobre hipóteses nulas ($H_{0}$) e alternativa ($H_{1}$) concorrentes e mutuamente exclusivas.[@Curran-Everett2009]

<br>

### O que é hipótese nula?

-   A hipótese nula ($H_{0}$) é uma expressão que representa o estado atual do conhecimento (*status quo*), em geral a não existência de um determinado efeito.[@kanji2006]

<br>

### O que é hipótese alternativa?

-   A hipótese alternativa ($H_{1}$) é uma expressão que contém as situações que serão testadas, de modo que um resultado positivo indique alguma ação a ser conduzida.[@kanji2006]

<br>

### Qual hipótese está sendo testada?

-   A hipótese nula ($H_{0}$) é a hipótese sob teste em análises inferenciais.[@Ali2016]

-   Pode-se concluir sobre rejeitar ou não rejeitar a hipótese nula ($H_{0}$).[@Ali2016]

-   Não se conclui sobre a hipótese alternativa ($H_{1}$).[@kanji2006]

-   Para testar a hipótese nula, deve-se selecionar o nível de significância crítica (p-valor de corte); a probabilidade de rejeitarmos uma hipótese nula verdadeira ($\alpha$); e a probabilidade de não rejeitarmos uma hipótese nula falsa ($\beta$).[@Curran-Everett2009]

<br>

### O que reportar após um teste de hipótese?

- P-valores, como estimativa da significância estatística.[@Sullivan2012]

- Tamanho do efeito, como estimativa de significância substantiva (clínica).[@Sullivan2012]

<br>

## Erros de inferência

<br>

### O que são erros de inferência estatística?

-   Um erro de inferência é a tomada de decisão incorreta, seja a favor ou contra a hipótese nula.[@Curran-Everett2009]

<br>

### O que é erro tipo I?

-   Erro tipo I significa a rejeição de uma hipótese nula ($H_{0}$) quando esta é verdadeira.[@Curran-Everett2009]

<br>

### O que é erro tipo II?

-   Erro tipo II significa a não rejeição de uma hipótese nula ($H_{0}$) quando esta é falsa.[@Curran-Everett2009]

<br>

### O que é poder do teste?

-   Poder do teste é a probabilidade de rejeitar a hipótese nula ($H_{0}$) quando esta é falsa.[@Curran-Everett2009]

-   Poder do teste pode ser calculado como ($1 - \beta$).[@Curran-Everett2009]

<br>

### Qual a relação entre os erros tipo I e II?

-   .[REF]

<br>

## Tamanho do efeito {#tamanho-efeito}

<br>

### O que é o tamanho do efeito?

-   Tamanho do efeito quantifica a magnitude de um efeito real da análise, expressando uma importância descritiva dos resultados.[@Kim2015]

<br>

### Como interpretar um tamanho do efeito?

-   Tamanhos de efeito podem ser comparadores entre diferentes estudos.[@Sullivan2012]

<br>

### Quais são os tipos de tamanho do efeito?

-   Diferenças padronizadas entre grupos:[@Sullivan2012; @Kim2015]

    -   Cohen's d

    -   Glass's $\Delta$

    -   Razão de chances ($RC$ ou $OR$)

    -   Risco relativo ou razão de risco ($RR$)

-   Medidas de associação:[@Sullivan2012; @Kim2015]

    -   Coeficiente de correlação de Pearson ($r$)

    -   Coeficiente de determinação ($R^2$)

<br>

### Como converter um tamanho de efeito em outro?

-   .[@Kim2015]

<br>

## P-valor {#p-valor}

<br>

### O que é o P-valor?

-   .[REF]

<br>

## Tipos de análises inferenciais {#tipos-analises-inferenciais}

<br>

### O que é uma análise ad hoc?

-   .[REF]

<br>

### O que é uma análise post hoc?

-   .[REF]

<br>

### O que é um teste paramétrico?

-   Testes paramétricos possuem suposições sobre as características e/ou parâmetros da distribuição dos dados na população.[@vetter2017]

-   Testes paramétricos assumem que: a variável é quantitativa numérica (contínua); os dados foram amostrados de uma população com distribuição normal; a variância da(S) amostra(s) é igual à da população; as amostras foram selecionadas de modo aleatório na população; os valores de cada amostra são independentes entre si.[@Ali2016; @vetter2017]

<br>

### O que é um teste não paramétrico?

-   Testes não-paramétricos fazem poucas suposições, ou menos rigorosas, sobre as características e/ou parâmetros da distribuição dos dados na população.[@Ali2016; @vetter2017]

-   Testes não-paramétricos são úteis quando as suposições de normalidade não podem ser sustentadas.[@Ali2016]

<br>

### Por que os testes paramétricos são preferidos?

-   Em geral, testes paramétricos são mais robustos (isto é, possuem menores erros tipo I e II) que seus testes não-paramétricos correspondentes.[@vetter2017]

-   Testes não-paramétricos apresentam menor poder estatístisco (maior erro tipo II) comparados aos testes paramétricos correspondentes.[@Ali2016]

<br>
