# **Delineamento de estudos** {#delineamento-estudos}

<br>

## Classificação {#classificacao}

<br>

### Como podem ser classificados os estudos científicos?

- Estudos científicos podem ser classificados em *básicos*, *observacionais*, *experimentais*, *acurácia diagnóstica*, *propriedades psicométricas*, *avaliação econômica* e *revisões de literatura*:[@Grant2009; @Süt2014; @Souza2017; @reeves2017; @echevarría-guanilo2019; @Chassé2019; @Chidambaram2019; @Erdemir2020; @Yang2021; @chipman2022]

<br>

- *Estudos básicos*[@Süt2014; @Chidambaram2019]
  - Genética
  - Celular
  - Experimentos com animais
  - Desenvolvimento de métodos

<br>

- *Estudos de simulação computacional*[@Erdemir2020; @chipman2022]

<br>

- *Estudos observacionais*[@Süt2014; @Chidambaram2019]
  - Descritivo
    - Estudo de caso
    - Série de casos
    - Transversal
  - Analítico
    - Transversal
    - Caso-Controle
      - Caso-Controle aninhado
      - Caso-Coorte
    - Coorte prospectiva ou retrospectiva

<br>

- *Estudos de acurácia diagnóstica*[@Chassé2019; @Yang2021]
  - Transversal
  - Caso-Controle
  - Comparativo
  - Totalmente pareado
  - Parcialmente pareado com subgrupo aleatório
  - Parcialmente pareado com subgrupo não aleatório
  - Não pareado aleatório
  - Não pareado não aleatório

<br>

- *Estudos de propriedades psicométricas*[@Souza2017; @echevarría-guanilo2019]
  - Validade
  - Confiabilidade
  - Concordância

<br>

- *Estudos quase-experimentais*[@reeves2017]
  - Quase-aleatorizado controlado
  - Estimação de variável instrumental
  - Descontinuidadede regressão
  - Série temporal interrompida controlada
  - Série temporal interrompida
  - Diferença

<br>

- *Estudos experimentais*[@Süt2014; @Chidambaram2019]
  - Fases I a IV
    - Aleatorizado controlado
    - Não-aleatorizado controlado
    - Autocontrolado
    - Cruzado
    - Fatorial
  - Campo
  - Comunitário

<br>

- *Estudos de avaliação econômica*[@Süt2014]
  - Análise de custo
  - Análise de minimização de custo
  - Análise de custo-utilidade
  - Análise de custo-efetividade
  - Análise de custo-benefício

<br>

- *Estudos de revisão*[@Grant2009]
  - Crítica
  - Narrativa
  - Mapeamento
  - Sistemática
  - Meta-análise
  - Mista
  - Visão geral
  - Sistemática qualitativa
  - Rápida
  - Escopo
  - Estado-da-arte
  - Busca e revisão sistemática
  - Sistematizada
  - Guarda-chuva

<br>
