# **Associação** {#analise-inferencial-associacao}

<br>

## Análise de associação {#analise-associacao}

<br>

### O que é análise de associação?

-   .[REF]

<br>

## Bivariável {#bivariavel}

<br>

### O que são as análises de associação bivariável?

-   .[REF]

<br>

### Quais testes podem ser usados para análises de associação bivariável?

-   Teste Qui-quadrado ($\chi^2$).[@McHugh2013; @Kim2017a]

    -   O teste qui-quadrado ($\chi^2$) avalia uma hipótese global se a relação entre duas variáveis e/ou fatores é independente ou associada.[@Kim2017a]

    -   O teste qui-quadrado é utilizado para comparar a distribuição de uma variável categórica em uma amostra ou grupo com a distribuição em outro. Se a distribuição da variável categórica não for muito diferente nos diferentes grupos, pode-se concluir que a distribuição da variável categórica não está relacionada com a variável dos grupos. Pode-se também concluir que a variável categórica e os grupos são independentes.[@Kim2017a]

    -   Tipo: não paramétrico.[@McHugh2013; @Kim2017a]

    -   Suposições:[@McHugh2013; @Kim2017a]

        -   As variáveis são ordinais ou categóricas nominais, de modo que as células representem frequência.

        -   Os níveis dos fatores (variáveis categóricas) são mutuamente exclusivos.

        -   Tamanho de amostra grande e adequado porque é baseado em uma abordagem de aproximação.

        -   Menos de 20% das células com frequências esperadas \< 5

        -   Nenhuma célula com frequência esperada \< 1.

    -   Hipóteses:[@Kim2017a]

        -   Nula ($H_{0}$): independente (sem associação)

        -   Alternativa ($H_{1}$): não independente (associação)

    -   Tamanho do efeito:[@Kim2017a]

        -   Phi ($\phi$), para tabelas de contingência 2x2

        -   Razão de chances ($RC$ ou $OR$), para tabelas de contingência 2x2

        -   Cramer V ($V$), para tabelas de contingência NxM

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *gtsummary*[@gtsummary] fornece a função *tbl_cross* para criar uma tabela NxM. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/gtsummary/index.html)
:::

<br>

-   Teste Exato de Fisher ($\chi^2$).[@McHugh2013; @Kim2017a]

    -   O teste exato de Fisher avalia a hipótese nula de independência aplicando a distribuição hipergeométrica dos números nas células da tabela.[@Kim2017a]

    -   Hipóteses:[@McHugh2013; @Kim2017a]

        -   Nula ($H_{0}$): independente (sem associação)

        -   Alternativa ($H_{1}$): não independente (associação)

    -   Tamanho do efeito:[@McHugh2013; @Kim2017a]

        -   Phi ($\phi$), para tabelas de contingência 2x2

        -   Razão de chances ($RC$ ou $OR$), para tabelas de contingência 2x2

        -   Cramer V ($V$), para tabelas de contingência NxM

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *gtsummary*[@gtsummary] fornece a função *tbl_cross* para criar uma tabela NxM. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/gtsummary/index.html)
:::

<br>

## Multivariável vs. Multivariada {#multivariavel-multivariada}

<br>

### O que são as análises de regressão simples, multivariável e multivariada?

-   A análise de regressão simples consiste em modelos estatísticos com 1 variável dependente (desfecho) e 1 variável independente (preditor).[@Hidalgo2013]

-   A análise multivariável (ou múltiplo) consiste em modelos estatísticos com 1 variável dependente (desfecho) e duas ou mais variáveis independentes.[@Hidalgo2013]

-   A análise multivariada consiste em modelos estatísticos com 2 ou mais variáveis dependente (desfechos) e duas ou mais variáveis independentes.[@Hidalgo2013]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *modelsummary*[@modelsummary] fornece as funções *modelsummary* e *modelplot* para gerar tabelas e gráficos de coeficientes de regressão. [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cloud.r-project.org/web/packages/modelsummary/index.html)
:::

<br>

### Quais testes podem ser usados em análise de associação multivariável?

- .[REF]

<br>

## Seleção de variáveis {#selecao}

<br>

### Correlação bivariada pode ser usada para seleção de variáveis em modelos de regressão multivariável?

-   Seleção bivariada de variáveis - isto é, aplicação de testes de correlação em pares de variáveis candidatas e variável de desfecho afim de selecionar quais serão incluídas no modelo multivariável - é um dos erros mais comuns na literatura.[@Dales1978; @Sun1996]

-   A seleção bivariada de variáveis torna o modelo mais suscetível a otimismo no ajuste se as variáveis de confundimento não são adequadamente controladas.[@Dales1978; @Sun1996]

<br>

### O que pode ser feito para reduzir o número de variáveis candidatas em modelos de regressão multivariável?

-   Verifique a existência de multicolinearidade entre as variáveis candidatas.[@Sun1996]

-   Em caso de uma proporção baixa entre o número de participantes e de variáveis, use o conhecimento prévio da literatura para selecionar um pequeno conjunto de variáveis candidatas.[@Sun1996]

-   Colapse categorias com contagem nula (células com valor igual a 0) de variáveis candidatas.[@Sun1996]

-   Use simulações de dados para identificar qual(is) variável(is) está(ão) causando problemas de convergência do ajuste do modelo.[@Sun1996]

<br>
