# **Ensaios clínicos aleatorizados** {#ensaios-clínicos-aleatorizados}

<br>

## Características {#caracteristicas}

<br>

### Quais são as características dos ensaios clínicos randomizados?

-   Quanto à unidade de alocação: *individual* vs. *agrupado*.[@Bruce2022]

-   Quanto ao número de braços: *único* vs. *múltiplos*.[@Bruce2022]

-   Quanto ao número de centros: *único* vs. *múltiplos*.[@Bruce2022]

-   Quanto ao cegamento: *aberto* vs. *simples-cego* vs. *duplo-cego* vs. *tripo-cego* vs. *quádruplo-cego*.[@Bruce2022]

-   Quanto à alocação: *sem sorteio* vs. *estratificada (centro apenas)* vs. *estratificada* vs. *minimizada* vs. *estratificada e minimizada*.[@Bruce2022]

<br>

## Comparação na linha de base {#comparacao-linha-de-base}

<br>

### Quais estratégias podem ser adotadas sobre comparação entre grupos na linha de base em ensaios clínicos randomizados?

-   Na fase de projeto: identifique as variáveis prognósticas do desfecho de acordo com a literatura.[@roberts1999]

-   Na fase de análise: inclua as variáveis prognósticas nos modelos para ajuste.[@roberts1999]

<br>

### Por que não se deve comparar grupos na linha de base em ensaios clínicos randomizados?

-   Quando a randomização é bem-sucedida, a hipótese nula de diferença entre grupos na linha de base é verdadeira.[@roberts1999]

-   Testes de significância estatística na linha de base avaliam a probabilidade de que as diferenças observadas possam ter ocorrido por acaso; no entanto, já sabemos - pelo delineamento do experimento - que quaisquer diferenças são causadas pelo acaso.[@gruijters2020]

<br>

## Análises de comparação {#comparacao-pre-pos}

<br>

### Que modelos podem ser utilizados para comparações?

-   As abordagens compreendem a comparação da variável de desfecho medida entre os momentos antes e depois ou da sua mudança (pre - pós) entre os momentos.[@Vickers2001]

-   Se a média da variável é igual entre grupos no início do acompanhamento, ambas abordagens estimam o mesmo efeito. Caso contrário, o efeito será influenciado pela correlação entre as medidas antes e depois. A análise da mudança não controla para desbalanços no início do estudo. [@Vickers2001]

-   Uma abordagem recomendada é a análise de covariância (ANCOVA), pois ajusta os valores pós-intervenção aos valores pré-intervenção para cada participante, e não é afetada pelas diferenças entre grupos no início do estudo.[@Vickers2001]

-   A análise de covariância (ANCOVA) modelando seja a mudança (pré - pós) quando o desfecho no pós-tratamento parece ser o método mais efetivo considerando-se o viés de estimação dos parâmetros, a precisão das estimativas, a cobertura nominal (isto é, intervalo de confiança) e o poder do teste.[@OConnell2017]

-   Análise de variância (ANOVA) e modelos lineares mistos (MLM) são outras opções de métodos, embora apresentem maior variância, menor poder, e cobertura nominal comparados à ANCOVA.[@OConnell2017]

<br>

## Ajuste de covariáveis {#ajuste-de-covariaveis}

<br>

### Quais variáveis devem ser utilizadas no ajuste de covariáveis?

-   A escolha das características de linha de base pelas quais uma análise é ajustada deve ser determinada pelo conhecimento prévio de uma possível influência no resultado, em vez da evidência de desequilíbrio entre os grupos de tratamento no estudo.[@roberts1999]

<br>

### Quais os benefícios do ajuste de covariáveis?

-   Ajustar por covariáveis ajuda a estimar os efeitos do tratamento para o indivíduo, assim como aumenta a eficiência dos testes para hipótese nula e a validade externa do estudo.[@Hauck1998]

-   Incluir a variável de desfecho medida na linha de base como covariável - independentemente da análise ser realizada com a medida pós-tratamento da mesma variável ou a diferença para a linha de base - pode aumentar o poder estatístico do estudo.[@Kahan2014]

-   Incluir outras variáveis medidas na linha de base, com potencial para serem desbalanceadas entre grupos após a randomização, diminui a chance de afetar as estimativas de efeito dos tratamentos.[@Kahan2014]

<br>

### Quais os riscos do ajuste de covariáveis?

-   Incluir covariáveis que não são prognósticas do desfecho pode reduzir o poder estatístico do estudo.[@Kahan2014]

-   Incluir covariáveis com dados perdidos pode reduzir o tamanho amostral e consequentemente o poder estatístico do estudo (análise de casos completos) ou levar a desvios do plano de análise por exclusão de covariáveis prognósticas.[@Kahan2014]

<br>

### Como lidar com os dados perdidos em covariáveis?

-   Imputação de dados perdidos de uma variável pela média dos dados observada permite estimativas não enviesadas dos efeitos do tratamento, preserva o erro tipo I e aumenta o poder estatístico comparado à análise de dados completos.[@Kahan2014]

<br>

## Interação {#interacao}

<br>

### O que é efeito de interação?

-   A interação - representada pelo símbolo '\*' - é o termo estatístico empregado para representar a heterogeneidade de um determinado efeito.[@Altman1996]

<br>

### Quando usar o termo de interação?

-   Análise de efeito de interação pode ser usada para testar se o efeito de um tratamento varia entre dois ou mais subgrupos de indivíduos, ou seja, se um efeito é modificado pelo(s) outros(s) efeito(s).[@Altman1996]

-   A interação entre duas (ou mais) variáveis pode ser utilizada para comparar efeitos do tratamento em subgrupos de ensaios clínicos.[@Altman2003]

-   O poder estatístico para detectar efeitos de interação é limitado.[@Altman2003]

<br>

### Por que analisar o efeito de interação?

-   A comparação de subgrupos por meio de testes de significância de hipótese nula separados é enganoso por não testar (comparar) diretamente os tamanhos dos efeitos dos tratamentos.[@Matthews1996]

<br>
