# **Redação estatística** {#redacao}

<br>

## Manuscritos reprodutíveis {#manuscritos-reprodutiveis}

<br>

### O que são manuscritos reprodutíveis?

- .[REF]

<br>

## Diretrizes {#diretrizes}

<br>

### Quais diretrizes estão disponíveis?

-   *Review of guidance papers on regression modeling in statistical series of medical journals*.[@Wallisch2022]

-   *Principles and recommendations for incorporating estimands into clinical study protocol templates*.[@Lynggaard2022]

-   *How to write statistical analysis section in medical research*.[@Dwivedi2022]

-   *Recommendations for Statistical Reporting in Cardiovascular Medicine: A Special Report From the American Heart Association*.[@Althouse2021]

-   *Framework for the treatment and reporting of missing data in observational studies: The Treatment And Reporting of Missing data in Observational Studies framework*.[@Lee2021]

-   *Guidelines for reporting of figures and tables for clinical research in urology*.[@Vickers2020]

-   *Who is in this study, anyway? Guidelines for a useful Table 1*.[@Hayes-Larson2019]

-   *Guidelines for Reporting of Statistics for Clinical Research in Urology*.[@assel2019]

-   *Reveal, Don't Conceal: Transforming Data Visualization to Improve Transparency*.[@Weissgerber2019]

-   *Guidelines for the Content of Statistical Analysis Plans in Clinical Trials*.[@Gamble2017]

-   *Basic statistical reporting for articles published in Biomedical Journals: The ''Statistical Analyses and Methods in the Published Literature'' or the SAMPL Guidelines*.[@Lang2015]

-   *Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm*.[@Weissgerber2015]

-   *STRengthening analytical thinking for observational studies: the STRATOS initiative*.[@Sauerbrei2014]

-   *Research methods and reporting*.[@groves2008]

-   *How to ensure your paper is rejected by the statistical reviewer*.[@stratton2005]

<br>

## Checklists {#checklists}

<br>

### O que são checklists?

-   Checklists são listas que podem ser utilizadas por autores, revisores ou editores, durante as fases de planejamento ou apresentação, para redação ou revisão de textos que relatam anaálises estatísticas.

<br>

### Por que usar checklists?

-   Checklists têm sido recomendados para melhorar o relato das análses realizadas, aumentar a transparência do estudo e reprodutibilidade dos achados.[@Gardner1986]

-   Trabalhos acadêmicos que relatam análises de dados devem ser passar por revisão por pares que inclua apreciação da análise estatóstica, e sua adequaçào ao delineamento do estudo e instrumentos utilizados.[@Mascha2017]

-   Checklists não são suficientes para garantir a qualidade técnica da pesquisa, mas podem conitribuir para a revisão por pares.[@Mascha2017]

<br>

### Quais checklists estão disponíveis?

-   *A CHecklist for statistical Assessment of Medical Papers (the CHAMP statement): explanation and elaboration*.[@Mansournia2021]

-   *Checklist for clinical applicability of subgroup analysis*.[@Gil-Sierra2020]

-   *Evidence‐based statistical analysis and methods in biomedical research (SAMBR) checklists according to design features*.[@dwivedi2019]

<br>

## Fluxogramas {#fluxogramas}

<br>

### O que são fluxogramas?

-   Fluxogramas são figuras que apresentam as etapas de um estudos.

<br>

### Que fluxogramas podem ser incluídos?

-   Inclua fluxogramas com o delineamento aplicado no estudo.[@Weissgerber2019]

-   A [EQUATOR Network](https://www.equator-network.org) disponibiliza modelos de fluxogramas para os mais diversos delineamentos de estudo.[@Altman2008]

<br>

::: blue
`r library(fontawesome); fa("r-project", margin_right = "0.1em")` O pacote *PRISMA2020*[@PRISMA2020-2; @PRISMA2020] fornece funções para elaboração do fluxograma de revisões sistemáticas no formato padrão [`r library(fontawesome); fa("up-right-from-square", margin_right = "0.1em")`](https://cran.r-project.org/web/packages/PRISMA2020/index.html)
:::

<br>
