# **Pacotes** {-}

```{r pacotes-instalador, echo = FALSE, warning = FALSE, message = FALSE, fig.align='center', results = "hide"}
if (!require("remotes", character.only = TRUE, quietly = TRUE))
  install.packages("remotes", character.only = TRUE)
library("remotes", character.only = TRUE)

if (!require("grateful", character.only = TRUE, quietly = TRUE))
  remotes::install_github("Pakillo/grateful")
library("grateful", character.only = TRUE)

if (!require("emo", character.only = TRUE, quietly = TRUE))
  devtools::install_github("hadley/emo"
  )
```

```{r pacotes-citacao, echo = FALSE, warning = FALSE, message = FALSE, fig.align='center', results = "asis"}
pkgs <- grateful::cite_packages(output = "table", citation.style = "american-medical-association-10th-edition.csl", bib.file = "grateful-refs.bib", dependencies = FALSE, out.dir = getwd(), out.format = ifelse(knitr::is_html_output(), "html", "pdf"))

kableExtra::kable(
  pkgs[, 1:2],
  align = "c",
  format = ifelse(knitr::is_html_output(), "html", "latex"),
  booktabs = TRUE,
  linesep = ""
) %>%
  kableExtra::kable_styling(
    latex_options = c("striped"),
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = ifelse(knitr::is_html_output(), T, T),
    position = "center"
  ) %>%
  kableExtra::row_spec(0,
                       bold = TRUE,
                       extra_css = "border-top: 1px solid; border-bottom: 1px solid") %>%
  kableExtra::row_spec(dim(pkgs)[1],
                       extra_css = "border-bottom: 1px solid; border-bottom: 1px solid")
```

<br>
