# **Computação estatística** {#computacao-estatistica}

<br>

## Programa de computador {#inicio}

<br>

### O que é R?

-   R é um programa de computador com linguagem computacional direcionada para análise estatística.[@ihaka1996]

- R está disponível em [Comprehensive R Archive Network (CRAN)]((https://cran.r-project.org)).

- R `R.version$version.string`.

<br>

### O que é RStudio?

-   RStudio é um ambiente de desenvolvimento integrado (*integrated devlopmnt environment*, IDE) desenvolvido visando a reprodutibilidade e a simplicidade para a criação e disseminação de conhecimento.[@racine2011]

- As principais características do RStudio incluem um ambiente de edição com abas para acesso rápido a arquivos, comandos e resultados; histórico de comandos previamente utilizados; ferramentas para visualização de bancos de dados e elaboração de scripts e gráficos e tabelas.[@racine2011]

- RStudio está disponível em [Posit](https://posit.co/download/rstudio-desktop/).

-   [RStudio version (`RStudio.Version()$version)`].

<br>

## Scripts computacionais {#inicio}

<br>

### O que são scripts?

-   Um script é um arquivo de texto contendo (quase) os mesmos comandos que você digitaria na linha de comando do R. (Quase) refere-se ao fato de que se você estiver usando *sink()* para enviar a saída para um arquivo, você terá que incluir alguns comandos em *print()* para obter a mesma saída da linha de comando ([CRAN](https://cran.r-project.org/doc/contrib/Lemon-kickstart/kr_scrpt.html)).

<br>

### Quais práticas são recomendadas na redação de scripts?

-   Use nomes consistentes para as variáveis.[@SchwabSimon2021]

-   Defina os tipos de variáveis adequadamente no banco de dados.[@SchwabSimon2021]

-   Defina constantes - isto é, variáveis de valor fixo - ao invés de digitar valores.[@SchwabSimon2021]

-   Use e cite os pacotes disponíveis para suas análises.[@SchwabSimon2021]

-   Controle as versões do script.[@Eglen2017; @SchwabSimon2021]

-   Teste o script antes de sua utilização.[@SchwabSimon2021]

-   Conduza revisão por pares do código durante a redação (digitação em dupla).[@SchwabSimon2021]

<br>

### O que pode ser compartilhado?

-   Idealmente, todos os scripts, pacotes/bibliotecas e dados necessários para outros reproduzirem seus dados.[@Eglen2017]

-   Minimamente, partes importantes incluindo implementações de novos algoritmos e dados que permitam reproduzir um resultado importante.[@Eglen2017]

<br>

### Como preparar os scripts para compartilhamento?

-   Crie links persistentes para versões do seu script.[@Eglen2017]

-   Escolha uma licença apropriada para garantir como outros usarão seus scripts.[@Eglen2017]

-   Providencie a documentação sobre seu script (ex.: arquivos *README*).[@Eglen2017]

-   Compartilhar todos os pacotes relacionados à sua análise.[@Zhao2023]

<br>

::: {.infobox .Rlogo data-latex="{Rlogo}"}

O pacote *formatR*[@formatR] fornece a função [*tidy_source*](https://www.rdocumentation.org/packages/formatR/versions/1.14/topics/tidy_source) para formatar um R script.

:::

<br>

### Que programas de computador gratuitos podem ser usados para análise estatística com R?

-   [JASP](https://jasp-stats.org).[@love2019]

-   [jamovi](https://www.jamovi.org).[@sahin2020]

<br>
