# **Concordância e confiabilidade** {#analise-concordancia-confiabilidade}

<br>

## Problemas de pesquisa {#problemas}

<br>

### Quais problemas de pesquisa são investigados com estudos de concordância e confiabilidade?

- Quão reprodutíveis são as mensurações?[@altman1983]

- Os diferentes métodos medem a mesma coisa em média?[@altman1983]

- Existe viés entre as medidas de diferentes métodos (isto é, medem a mesma coisa em média)?[@altman1983]

- Um método pode substituir o outro?[@altman1983]

<br>

### Quais fontes de variabilidade são comumente investigadas?

- Intra/Entre sujeitos.[@altman1983]

- Intra/Entre repetições.[@altman1983]

- Intra/Entre observadores.[@altman1983]

<br>

## Concordância {#concordancia}

<br>

### O que é concordância?

- .[REF]

<br>

### Quais métodos são adequados para análise de concordância?

- Gráfico de dispersão com a reta de regressão.[@altman1983]

- Gráfico de limites de concordância (média dos testes vs. diferença entre testes) com a reta de regressão do viés e respectivo intervalo de confiança.[@altman1983]

<br>

### Quais métodos não são adequados para análise de concordância?

-   Comparação de médias: dois métodos apresentarem médias similares - isto é, 'sem diferença estatística' após um teste inferencial de hipótese nula $H_{0}:\mu_{1} = \mu_{2}$ - não informa sobre a concordância deles. Métodos com maior erro de medida tendem a ter menos chance de rejeição da hipótese nula.[@altman1983]

- Correlação bivariada: o coeficiente de correlação dependente tanto da variação entre indivíduos (isto é, entre os valores verdadeiros) quanto da variação intraindividual (isto é, erro de medida). Se a variância dos erros de medida de ambos os métodos não for pequena comparadas à variância dos valores verdadeiros, o tamanho do efeito da correlação será pequeno mesmo que os métodos possuam boa concordância.[@altman1983]

- Regressão linear: o teste da hipótese nula da inclinação da reta de regressão ($H_{0}:\beta = 0$) é equivalente a testar a correlação bivariada ($H_{0}:\rho = 0$).[@altman1983]

<br>

## Confiabilidade {#confiabilidade}

<br>

### O que é confiabilidade?

- .[REF]

<br>

### Quais métodos são adequados para análise de confiabilidade?

- .[REF]

<br>
