# **Delineamento de estudos** {#delineamento-estudos}

<br>

## Classificação {#classificacao}

<br>

### Como podem ser classificados os estudos científicos?

-   Estudos científicos podem ser classificados em *básicos*, *observacionais*, *experimentais*, *acurácia diagnóstica*, *propriedades psicométricas*, *avaliação econômica* e *revisões de literatura*:[@Grant2009; @Süt2014; @Souza2017; @reeves2017; @echevarría-guanilo2019; @Chassé2019; @Chidambaram2019; @Erdemir2020; @Yang2021; @chipman2022]

-   *Estudos básicos*[@Süt2014; @Chidambaram2019]

    -   Genética

    -   Celular

    -   Experimentos com animais

    -   Desenvolvimento de métodos

-   *Estudos de simulação computacional*[@Erdemir2020; @chipman2022]

-   *Estudos observacionais*[@Süt2014; @Chidambaram2019]

    -   Descritivo

        -   Estudo de caso

        -   Série de casos

        -   Transversal

    -   Analítico

        -   Transversal

        -   Caso-Controle

            -   Caso-Controle aninhado

            -   Caso-Coorte

    -   Coorte prospectiva ou retrospectiva

-   *Estudos de acurácia diagnóstica*[@Chassé2019; @Yang2021]

    -   Transversal

    -   Caso-Controle

    -   Comparativo

    -   Totalmente pareado

    -   Parcialmente pareado com subgrupo aleatório

    -   Parcialmente pareado com subgrupo não aleatório

    -   Não pareado aleatório

    -   Não pareado não aleatório

-   *Estudos de propriedades psicométricas*[@Souza2017; @echevarría-guanilo2019]

    -   Validade

    -   Confiabilidade

    -   Concordância

-   *Estudos quase-experimentais*[@reeves2017]

    -   Quase-aleatorizado controlado

    -   Estimação de variável instrumental

    -   Descontinuidade de regressão

    -   Série temporal interrompida controlada

    -   Série temporal interrompida

    -   Diferença

-   *Estudos experimentais*[@Süt2014; @Chidambaram2019]

    -   Fases I a IV

        -   Aleatorizado controlado

        -   Não-aleatorizado controlado

        -   Autocontrolado

        -   Cruzado

        -   Fatorial

    -   Campo

    -   Comunitário

-   *Estudos de avaliação econômica*[@Süt2014]

    -   Análise de custo

    -   Análise de minimização de custo

    -   Análise de custo-utilidade

    -   Análise de custo-efetividade

    -   Análise de custo-benefício

-   *Estudos de revisão*[@Grant2009]

    -   Estado-da-arte

    -   Narrativa

    -   Crítica

    -   Mapeamento

    -   Escopo

    -   Busca e revisão sistemática

    -   Sistematizada

    -   Sistemática

        -   Meta-análise

        -   Bibliométrica.[@donthu2021; @lim2023]

    -   Sistemática qualitativa

    -   Mista

    -   Visão geral

    -   Rápida

    -   Guarda-chuva

<br>

## População {#populacao}

<br>

### O que é população?

- .[REF]

<br>

### Qual é a relação entre população e amostra?

-   Em pesquisa científica, utilizam-se dados de uma amostra de participantes (ou outras unidades de análise) para realizar inferências sobre a população.[@Bland2015]

<br>

## Amostragem {#amostragem}

<br>

### O que é amostragem?

- .[REF]

<br>

## Reamostragem {#reamostragem}

<br>

### O que é reamostragem?

-   Reamostragem é um procedimento que cria vários conjuntos de dados sorteados a partir de um conjunto de dados real - a amostra da população - sem a necessidade de fazer suposições sobre os dados e suas distribuições .[@Bland2015]

- O procedimento é repetido várias vezes para usar a variabilidade dos resultados para obter um intervalo de confiança do parâmetro.[@Bland2015]

<br>

### Por que utilizar reamostragem?

-   Quando se dispõe de dados de apenas 1 amostra, as diversas suposições que são feitas podem não ser atingidas.[@Bland2015]

- Procedimentos de reamostragem produzem um conjunto de observações escolhidas aleatoriamente da amostra, igualmente representativo da população original.[@Bland2015]

-   Procedimentos de reamostragem permitem estimar o erro-padrão e intervalos de confiança sem a necessidade de tais suposições, sendo portanto um conjunto de procedimentos não-paramétricos.[@Bland2015]

<br>

### Quais procedimentos de reamostragem podem ser realizados?

-  *Bootstrap*:  Cada iteração gera uma amostra *bootstrap* do mesmo tamanho do conjunto de dados original escolhendo aleatoriamente observações reais, uma de cada vez. Cada observação tem chances iguais de ser escolhida a cada vez, portanto, algumas observações serão escolhidas mais de uma vez e outras nem serão escolhidas.[@Bland2015]

<br>

## Pareamento {#pareamento}

<br>

### O que é pareamento?

-   Pareamento significa que para cada participante de um grupo (por exemplo, com alguma condição clínica), existe um (ou mais) participantes (por exemplo, grupo controle) que possui características iguais ou similares relativas a algumas variáveis de interesse.[@Bland1994]

-   As variáveis escolhidas para pareamento devem ter relação com as variáveis de desfecho, mas não são de interesse elas mesmas.[@Bland1994]

-   O ajuste por pareamento deve ser incluído nas análises estatísticas mesmo que as variáveis de pareamento não sejam consideradas prognósticas ou confundidores na amostra estudada.[@Bland1994]

-   A ausência de evidência estatística de diferença entre grupos não é considerada pareamento.[@Bland1994]

<br>

## Alocação {#alocacao}

<br>

### O que é alocação?

-   .[REF]

<br>

## Aleatorização {#aleatorização}

-   .[REF]

<br>

### O que é aleatorização?

<br>

## Validade do estudo {#validade-estudo}

<br>

### O que é validade interna?

-   .[@findley2021]

<br>

### O que é validade externa?

-   .[@findley2021]

<br>
