# **Pensamento estatístico** {#pensamento-estatistico}

<br>

## Estatística e pesquisa científica {#estatisica-pesquisa}

<br>

### Qual a contribuição da estatística para pesquisa?

-   .[@munafò2017]

<br>

<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
</script>

<pre class="mermaid" style="background-color:white; primaryColor:white; mainBkg:white; fill:white; background:white;">

    graph TD
    G-->B

    subgraph ide1 [Modelo teórico hipotético-dedutivo]
    B[Geração e especificação <br/> de hipóteses]-->C[Delineamento <br/> do estudo]
    C[Delineamento do estudo]-->D[Realização do estudo <br/> e coleta de dados]
    D[Realização do estudo e coleta de dados]-->E[Análise de dados e teste de hipóteses]
    E[Análise de dados <br/> e teste de hipóteses]-->F[Interpretação de resultados]
    F[Interpretação <br/> de resultados]-->G[Publicação e/ou realização <br/> do próximo experimento]
    end

    subgraph ide2 [Contribuições da estatística]
    H[Elaboração das hipóteses <br/> nula e alternativa]-.->B[Geração e especificação <br/> de hipóteses]
    I[Seleção das análises <br/> descritiva/inferencial e testes]-.->C[Delineamento <br/> do estudo]
    J[Análise inicial <br/> de dados]-.->D[Realização do estudo <br/> e coleta de dados]
    K[Análise <br/> inferencial]-.->E[Análise de dados <br/> e teste de hipóteses]
    L[Tamanho do efeito <br/> e P-valor]-.->F[Interpretação <br/> de resultados]
    M[Redação <br/> dos resultados]-.->G[Publicação e/ou realização <br/> do próximo experimento]
    end

</pre>

<br>

## Espaços amostrais e eventos {#espacos-eventos}

<br>

### O que é espaço amostral?

-   .[REF]

<br>

### O que é evento?

-   .[REF]

<br>

### O que é espaço de eventos?

-   .[REF]

<br>

## Probabilidade condicional {#probabilidade-ciondicional}

<br>

### O que é probabilidade condicional?

-   .[REF]

<br>

## Leis dos grandes números {#lei-grandes-numeros}

<br>

### O que é a lei fraca dos grandes números?

-   .[REF]

<br>

### O que é a lei forte dos grandes números?

-   .[REF]

<br>

## Teorema central do limite {#teorema-central-limite}

<br>

### O que é teorema central do limite?

-   .[REF]

<br>

## Regressão para a média {#regressao-media}

<br>

### O que é regressão para a média?

-   .[REF]

<br>
