# **Pensamento metodológico** {#pensamento-metodologico}

<br>

## População {#populacao}

<br>

### O que é população?

- .[REF]

<br>

### Qual é a relação entre população e amostra?

-   Em pesquisa científica, utilizam-se dados de uma amostra de participantes (ou outras unidades de análise) para realizar inferências sobre a população.[@Bland2015]

<br>

## Amostragem {#amostragem}

<br>

### O que é amostragem?

- .[REF]

<br>

## Tamanho da amostra

<br>

### O que é tamanho da amostra?

-   .[REF]

<br>

### Como é determinado o tamanho da amostra de um estudo?

-   .[REF]

<br>

### Quais aspectos éticos estão envolvidos no tamanho da amostra?

-   O tratamento ético dos participantes do estudo, portanto, não exige que se considere se o poder do estudo é inferior à meta convencional de 80% ou 90%.[@Bacchetti2005]

- Estudos com poder <80% não são necessariamente antiéticos.[@Bacchetti2005]

- Grandes estudos podem ser desejáveis por outras razões que não as éticas.[@Bacchetti2005]

<br>

## Validade do estudo {#validade-estudo}

<br>

### O que é validade interna?

-   .[@findley2021]

<br>

### O que é validade externa?

-   .[@findley2021]

<br>

## Pareamento {#pareamento}

<br>

### O que é pareamento?

-   Pareamento significa que para cada participante de um grupo (por exemplo, com alguma condição clínica), existe um (ou mais) participantes (por exemplo, grupo controle) que possui características iguais ou similares relativas a algumas variáveis de interesse.[@Bland1994]

-   As variáveis escolhidas para pareamento devem ter relação com as variáveis de desfecho, mas não são de interesse elas mesmas.[@Bland1994]

-   O ajuste por pareamento deve ser incluído nas análises estatísticas mesmo que as variáveis de pareamento não sejam consideradas prognósticas ou confundidores na amostra estudada.[@Bland1994]

-   A ausência de evidência estatística de diferença entre grupos não é considerada pareamento.[@Bland1994]

<br>

## Alocação {#alocacao}

<br>

### O que é alocação?

-   .[REF]

<br>

## Aleatorização {#aleatorização}

-   .[REF]

<br>

### O que é aleatorização?

<br>

