# CREATE POSTS

```{r read, echo = FALSE, results = FALSE, warning = FALSE, message = FALSE}
# read TeX file
tex_data <- TeXCheckR::read_tex_document(
  file.path("./docs", "Ciencia-com-R.tex")
)
# source scripts
source(file.path("R", "tex_to_df.R"), local = knitr::knit_global())
df <- parse_tex_structure(tex_data)

# CLEAN df
df <- df |>
  dplyr::filter(
    !is.na(graphic) |
      (
        !is.na(references) &
          !grepl("REF", item) &
          references != "REF" &
          item != ".\\textsuperscript{\\citeproc{ref-REF}{\\textbf{REF?}}}"
      )
  )

# BUILD CHAPTER INDEX (order = first appearance in df)
chapter_index <- df |>
  dplyr::distinct(chapter) |>
  dplyr::mutate(chapter_id = dplyr::row_number())

# BUILD SECTION INDEX (restart at 1 per chapter)
section_index <- df |>
  dplyr::distinct(chapter, section) |>
  dplyr::group_by(chapter) |>
  dplyr::mutate(section_id = dplyr::row_number()) |>
  dplyr::ungroup()

# BUILD SUBSECTION INDEX (restart at 1 per chapter + section)
subsection_index <- df |>
  dplyr::distinct(chapter, section, subsection) |>
  dplyr::group_by(chapter, section) |>
  dplyr::mutate(subsection_id = dplyr::row_number()) |>
  dplyr::ungroup()

# JOIN INDICES BACK INTO df
df <- df |>
  dplyr::left_join(chapter_index, by = "chapter") |>
  dplyr::left_join(section_index, by = c("chapter", "section"))

# JOIN SUBSECTION INDEX BACK INTO df
df <- df |>
  dplyr::left_join(
    subsection_index,
    by = c("chapter", "section", "subsection")
  )
```


```{r save, echo = FALSE, results = FALSE, warning = FALSE, message = FALSE}
# delete .PNG files from posts folder
delete_files <- list.dirs("posts", full.names = TRUE)
unlink(delete_files, recursive = TRUE)
# create folder "posts"
dir.create("posts", showWarnings = FALSE)

# read bib file
bib <- RefManageR::ReadBib(file.path("./bib", "references.bib"))

# save all posts
source(file.path("R", "savePost.R"), local = knitr::knit_global())
for (i in 1:nrow(df)) {
  # progress bar
  cat(paste0(round(i / nrow(df) * 100), '% completed'))
  SavePost_df(entry = df[i, ], bib = bib)
  if (i == nrow(df)) cat(': Done')
  else cat('\014')
}
```
