# **Reprodutibilidade em ciência** {#manuscritos-reprodutiveis}

<br>

## Reprodutibilidade

<br>

### O que é reprodutibilidade?

-   Reprodutibilidade em ciência é a habilidade de se obter resultados iguais ou similares quando um experimento ou teste é repetido.[@resnik2016]

-   Analisar a reprodutibilidade pode fornecer evidências a respeito da objetividade e confibilidade dos achados, wem detrimento de terem sido obtidos devido a vieses ou ao acaso.[@resnik2016]

-   A reprodutibilidade não é apenas uma questão metodológica, mas também ética, uma vez que pode envolver mal práticas científicas como fabricação e/ou falsificação de dados.[@resnik2016]

<br>

## Manuscritos reprodutíveis

<br>

### O que são manuscritos reprodutíveis?

-   .[@R-rmarkdown]

<br>

### Como manuscritos reprodutíveis contribuem para a ciência ?

-   O compartilhamento de bancos de dados e seus scripts de análise estatística permitem a adoção de práticas reprodutíveis, tais como a reanálise dos dados.[@ioannidis2014]

<br>
