# **Variáveis e fatores** {#variaveis-fatores}

<br>

## Variáveis {#variaveis}

<br>

### O que são variáveis?

-   Variáveis são informações que podem variar entre medidas em diferentes indivíduos e/ou repetições.[@Altman1999]

-   Variáveis definem características de uma amostra extraída da população, tipicamente observados por aplicação de métodos de amostragem (isto é, seleção) da população de interesse.[@vetter2017]

<br>

### Como são classificadas as variáveis?

-   Quanto à informação:[@Ali2016; @vetter2017; @Dettori2018; @kaliyadan2019]

    -   Quantitativa

    -   Qualitativa

-   Quanto ao conteúdo:[@Ali2016; @vetter2017; @Dettori2018; @kaliyadan2019]

    -   Contínua (intervalo ou razão; discreta ou contínua)

    -   Categórica ordinal (numérica discreta ou nominal)

    -   Categórica nominal (multinominal ou dicotômica)

-   Quanto à interpretação:[@Ali2016; @vetter2017; @Dettori2018; @kaliyadan2019]

    -   Dependente (desfecho)

    -   Independente (preditora, covariável, confundidora, controle)

    -   Mediadora

    -   Moderadora

    -   Modificadora

    -   Auxiliar

    -   Indicadora

<br>

### Por que é importante classificar as variáveis?

-   Identificar corretamente os tipos de variáveis da pesquisa é uma das etapas da escolha dos métodos estatísticos adequados para as análises e representações no texto, tabelas e gráficos.[@Dettori2018]

<br>

## Transformação de variáveis contínuas {#transformacao}

<br>

### O que é transformação de variáveis contínuas?

-   Transformação significa aplicar uma função matemática à variável medida em sua unidade original.[@Bland1996]

-   A transformação visa atender aos pressupostos dos modelos estatísticos quanto à distribuição da variável, em geral a distribuição gaussiana.[@Bland1996; @vetter2017]

-   A dicotomização pode ser interpretada como um caso particular de agrupamento.[@Fedorov2009]

<br>

### Por que transformar variáveis?

-   Muitos procedimentos estatísticos supõem que as variáveis - ou seus termos de erro, mais especificamente - são normalmente distribuídas. A violação dessa suposição pode aumentar suas chances de cometer um erro do tipo I ou II.[@osborne2010]

-   Mesmo quando se está usando análises consideradas robustas para violações dessas suposições ou testes não paramétricos (que não assumem explicitamente termos de erro normalmente distribuídos), atender a essas questões pode melhorar os resultados das análises (por exemplo, Zimmerman, 1995).[@osborne2010]

<br>

### Quais transformações podem ser aplicadas?

-   Distribuições com assimetria à direita:[@osborne2010]

    -   Raiz quadrada

    -   Logaritmo natural

    -   Logaritmo base 10

    -   Transformação inversa

-   Distribuições com assimetria à esquerda:[@osborne2010]

    -   Reflexão e raiz quadrada

    -   Reflexão e logaritmo natural

    -   Reflexão e logaritmo base 10

    -   Reflexão e transformação inversa

-   Transformação arco-seno.[@osborne2010]

-   Transformação de Box-Cox.[@box1964]

-   Dicotomização.

<br>

::: {.infobox .Rlogo data-latex="{Rlogo}"}
**Atenção!**

O pacote *MASS*[@MASS] fornece a função [*boxcox*](https://www.rdocumentation.org/packages/MASS/versions/7.3-58.3/topics/boxcox) para executar a transformação de Box-Cox.[@box1964]

:::

<br>

## Categorização de variáveis contínuas {#categorizacao}

<br>

### O que é catogorização de uma variável?

-   .[REF]

<br>

### Por que não é recomendado categorizar variáveis contínuas?

-   Nenhum dos argumentos usados para defender a categorização de variáveis se sustenta sob uma análise técnica rigorosa.[@MacCallum2002]

-   Categorizar variáveis não é necessário para conduzir análises estatísticas. Ao invés de categorizar, priorize as variáveis contínuas.[@Altman2006; @Royston2006; @Collins2016]

-   Em geral, não existe uma justificativa racional (plausibilidade biológica) para assumir que as categorias artificiais subjacentes existam.[@Altman2006; @Royston2006; @Collins2016]

-   Caso exista um ponto de corte ou limiar verdadeiro que discrimine três ou mais grupos independentes, identificar tal ponto de corte ainda é um desafio.[@Prince2017]

-   Categorização de variáveis contínuas aumenta a quantidade de testes de hipótese para comparações pareadas entre os quantis, inflando portanto o erro tipo I.[@Bennette2012]

- Categorização de variáveis contínuas requer uma função teórica que pressupõe a homogeneidade da varia'vel dentro dos grupos, levando tanto a uma perda de poder como a uma estimativa imprecisa.[@Bennette2012]

- Categorização de variáveis contínuas pode dificultar a comparação d resultados entre estudos devido aos pontos de corte baseados em dados de um banco usados para definir as categorias.[@Bennette2012]

<br>

### Quais são as alternativas à categorização de variáveis contínuas?

- Análise com os dados das variável na escala de medida original .[@MacCallum2002]

- Análise com modelos de regressão com pesos locais (*lowess*) tais como *splines* e polinômios fracionais.[@MacCallum2002]

<br>

## Dicotomização de variáveis contínuas {#dicotomizacao}

<br>

### O que são variáveis dicotômicas?

-   Variáveis dicotômicas (ou binárias) podem representar categorias naturais tipo "presente/ausente", "sim/não".[REF]

-   Variáveis dicotômicas podem representar categorias fictícias, criadas a partir de variáveis multinominais, em que cada nível é convertido em uma variável dicotômica *dummy*.[REF]

-   Geralmente são representadas por "1" e "0".[REF]

<br>

### Quais argumentos são usados para defender a categorização ou dicotomização de variáveis contínuas?

-   O argumento principal para dicotomização de variáveis é que tal procedimento facilita e simplifica a apresentação dos resultados, principalmente para o público em geral.[@Fedorov2009]

-   Os pesquisadores não conhecem as consequências estatísticas da dicotomização.[@MacCallum2002]

-   Os pesquisadores não conhecem os métodos adequados de análise não-paramétrica, não-linear e robusta.[@MacCallum2002]

-   As categorias representam características existentes dos participantes da pesquisa, de modo que as análises devam ser feitas por grupos e não por indivíduos.[@MacCallum2002]

-   A confiabilidade da(s) variável(eis) medida(s) é baixa e, portanto, categorizar os participantes resultaria em uma medida mais confiável.[@MacCallum2002]

<br>

### Por que não é recomendado dicotomizar variáveis contínuas?

-   Nenhum dos argumentos usados para defender a dicotomização de variáveis se sustenta sob uma análise técnica rigorosa.[@MacCallum2002]

-   Dicotomizar variáveis não é necessário para conduzir análises estatísticas. Ao invés de dicotomizar, priorize as variáveis contínuas.[@Altman2006; @Royston2006; @Collins2016]

-   Em geral, não existe uma justificativa racional (plausibilidade biológica) para assumir que as categorias artificiais subjacentes existam.[@Altman2006; @Royston2006; @Collins2016]

-   Dicotomização causa perda de informação e consequentemente perda de poder estatístico para detectar efeitos.[@MacCallum2002; @Altman2006]

-   Dicotomização também classifica indivíduos com valores próximos na variável contínua como indivíduos em pontos opostos e extremos, artificialmente sugerindo que são muito diferentes.[@Altman2006]

-   Dicotomização pode diminuir a variabilidade das variáveis.[@Altman2006]

-   Dicotomização pode ocultar não-linearidades presentes na variável contínua.[@MacCallum2002; @Altman2006]

-   A média ou a mediana, embora amplamente utilizadas, não são bons parâmetros para dicotomizar variáveis.[@Altman2006; @Fedorov2009]

-   Caso exista um ponto de corte ou limiar verdadeiro que discrimine dois grupos independentes, identificar tal ponto de corte ainda é um desafio.[@Prince2017]

<br>

### Quais cenários legitimam a dicotomização das variáveis contínuas?

-   Quando existem dados e/ou análises que suportem a existência - não apenas a suposição ou teorização - de categorias com um ponto de corte claro e com significado entre elas.[@MacCallum2002]

-   Quando a distribuição da variável contínua é muito assimétrica, de modo que uma grande quantidade de observações está em um dos extremos da escala.[@MacCallum2002]

<br>

### Quais métodos são usados para dicotomizar variáveis contínuas?

-   Em termos de tabelas de contingência 2x2, os seguintes métodos permitem[@Prince2017] a identificação do limiar verdadeiro:

    -   Youden.[@YOUDEN1950]

    -   Gini Index.[@strobl2007]

    -   Estatística qui-quadrado ($\chi^2$).[@pearson1900]

    -   Risco relativo ($RR$).[@Greiner2000]

    -   Kappa ($\kappa$).[@fleiss1971].

<br>

## Fatores {#fatores}

<br>

### O que são fatores?

-   Fator é um sinônimo de variável categórica.[REF]

-   Na modelagem, fator é sinônimo de variável preditora, em particular quando se refere à modelagem de efeitos fixos e aleatórios -- os fatores (variáveis) são fatores fixos ou fatores aleatórios.[REF]

<br>

### O que são níveis de um fator?

-   Níveis de um fator são as possíveis categorias que descrevem um fator.[REF]

<br>

::: {.infobox .Rlogo data-latex="{Rlogo}"}
**Atenção!**

O pacote *forcats*[@forcats] fornece a função [*as_factor*](https://www.rdocumentation.org/packages/forcats/versions/1.0.0/topics/as_factor) para converter uma variável em fator.

:::

<br>
